/**
 * Migration framework inventory — the canonical taxonomy of jobs-to-be-done,
 * features, and entities that any ADO → GitHub migration touches.
 *
 * Sourced from the Migration Framework standalone document (T26 §02). This
 * file is the program-wide spine; per-team relevance is derived in
 * `src/server/inventory.ts` from cohort characteristics + seeded JTBDs.
 *
 * Replace with a Prisma-backed model when M2 lands.
 */

export type StaysInAdo = "ado" | "gh" | "both" | "na";

export type Pattern = "P1" | "P2" | "P3" | "P4" | "P5" | "P6";

export type JtbdCategory =
  | "code"
  | "pull-requests"
  | "work-planning"
  | "ci-cd"
  | "deploy"
  | "testing"
  | "security"
  | "identity"
  | "automation"
  | "knowledge"
  | "reporting"
  | "code-comprehension"
  | "onboarding"
  | "review-workflow"
  | "admin"
  | "policy"
  | "incident"
  | "release"
  | "release-events";

export type Persona =
  | "Developer"
  | "Tech Lead"
  | "PM"
  | "Release Manager"
  | "QA"
  | "Security"
  | "Platform Engineer";

export type Frequency =
  | "Daily"
  | "Weekly"
  | "Per-sprint"
  | "Per-release"
  | "Per-project"
  | "Per-audit"
  | "Rare";

export type Jtbd = {
  id: string;
  name: string;
  category: JtbdCategory;
  categoryLabel: string;
  persona: Persona;
  frequency: Frequency;
  staysInAdo: StaysInAdo;
  staysReason: string;
  impact: string;
  /** Feature IDs this JTBD depends on. */
  features: string[];
};

export type Feature = {
  id: string;
  name: string;
  category: string;
  staysInAdo: StaysInAdo;
  pattern: Pattern;
  preservationStrategy: string;
  /** Entity IDs this feature depends on. */
  entities: string[];
};

export type Entity = {
  id: string;
  name: string;
  service:
    | "boards"
    | "repos"
    | "pipelines"
    | "test-plans"
    | "artifacts"
    | "platform";
  serviceLabel: string;
  staysInAdo: StaysInAdo;
  pattern: Pattern;
  dataPreservation: "high" | "medium" | "low" | "gap" | "na";
  capabilityPreservation: "high" | "medium" | "low" | "gap" | "na";
  note: string;
  /** Field count (informational). */
  fieldCount: number;
};

export const ENTITIES: Entity[] = [
  // Boards (E01-E13)
  {
    id: "E01",
    name: "Work Item",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "low",
    note: "Hybrid keeps Boards in ADO; work items don't migrate.",
    fieldCount: 39,
  },
  {
    id: "E02",
    name: "Work Item Type",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Custom types are a primary reason teams stay in hybrid.",
    fieldCount: 6,
  },
  {
    id: "E03",
    name: "Process Template",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Meta-entity with no GitHub equivalent.",
    fieldCount: 8,
  },
  {
    id: "E04",
    name: "Area Path",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "low",
    note: "Hierarchy lost if migrated.",
    fieldCount: 4,
  },
  {
    id: "E05",
    name: "Iteration Path",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Maps to Milestone or Project iteration.",
    fieldCount: 5,
  },
  {
    id: "E06",
    name: "Board (Kanban)",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Projects board lacks swimlanes / column limits.",
    fieldCount: 7,
  },
  {
    id: "E07",
    name: "Sprint",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Capacity tracking is lost.",
    fieldCount: 6,
  },
  {
    id: "E08",
    name: "Backlog",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Hierarchical backlog UX is composed, not native.",
    fieldCount: 4,
  },
  {
    id: "E09",
    name: "Query (WIQL)",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "GitHub search is much thinner than WIQL.",
    fieldCount: 3,
  },
  {
    id: "E10",
    name: "Tag",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Maps 1:1 to Issue labels.",
    fieldCount: 2,
  },
  {
    id: "E11",
    name: "Comment / Discussion",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Maps cleanly to Issue comments.",
    fieldCount: 4,
  },
  {
    id: "E12",
    name: "Attachment",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Size limits differ but supported.",
    fieldCount: 4,
  },
  {
    id: "E13",
    name: "Link",
    service: "boards",
    serviceLabel: "Boards",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Typed link semantics collapse on GitHub.",
    fieldCount: 5,
  },

  // Repos (E14-E20)
  {
    id: "E14",
    name: "Pull Request",
    service: "repos",
    serviceLabel: "Repos",
    staysInAdo: "gh",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "GEI preserves PRs cleanly.",
    fieldCount: 17,
  },
  {
    id: "E15",
    name: "Repository",
    service: "repos",
    serviceLabel: "Repos",
    staysInAdo: "gh",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Full history migrates via GEI.",
    fieldCount: 16,
  },
  {
    id: "E16",
    name: "Branch",
    service: "repos",
    serviceLabel: "Repos",
    staysInAdo: "gh",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Git refs preserved.",
    fieldCount: 5,
  },
  {
    id: "E17",
    name: "Branch Policy",
    service: "repos",
    serviceLabel: "Repos",
    staysInAdo: "gh",
    pattern: "P4",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Decomposes to branch protection + status checks + CODEOWNERS.",
    fieldCount: 8,
  },
  {
    id: "E18",
    name: "PR Review / Vote",
    service: "repos",
    serviceLabel: "Repos",
    staysInAdo: "gh",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "5-state ADO votes collapse to 3 GitHub states.",
    fieldCount: 4,
  },
  {
    id: "E19",
    name: "PR Thread / Comment",
    service: "repos",
    serviceLabel: "Repos",
    staysInAdo: "gh",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "GEI preserves threads.",
    fieldCount: 6,
  },
  {
    id: "E20",
    name: "Fork",
    service: "repos",
    serviceLabel: "Repos",
    staysInAdo: "gh",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Fork relationships transfer with both ends in scope.",
    fieldCount: 3,
  },

  // Pipelines (E21-E34)
  {
    id: "E21",
    name: "Pipeline / Build Definition",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P4",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Stays in Pipelines under hybrid.",
    fieldCount: 22,
  },
  {
    id: "E22",
    name: "Release Definition",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Classic UI-based releases stay in ADO.",
    fieldCount: 15,
  },
  {
    id: "E23",
    name: "YAML Pipeline",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Source trigger rewires to GitHub repo.",
    fieldCount: 12,
  },
  {
    id: "E24",
    name: "Classic Build Definition",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "Legacy UI builds stay in ADO.",
    fieldCount: 14,
  },
  {
    id: "E25",
    name: "Pipeline Run / Build",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P5",
    dataPreservation: "na",
    capabilityPreservation: "high",
    note: "Run history stays in ADO.",
    fieldCount: 8,
  },
  {
    id: "E26",
    name: "Release / Deployment",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P5",
    dataPreservation: "na",
    capabilityPreservation: "medium",
    note: "Release instances stay in ADO.",
    fieldCount: 9,
  },
  {
    id: "E27",
    name: "Agent Pool",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "high",
    note: "Pools stay; tag-demand routing preserved.",
    fieldCount: 6,
  },
  {
    id: "E28",
    name: "Agent",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Agents stay registered to Pipelines.",
    fieldCount: 5,
  },
  {
    id: "E29",
    name: "Environment",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P4",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Environments + check coverage stay in ADO.",
    fieldCount: 8,
  },
  {
    id: "E30",
    name: "Variable Group / Library",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Grouped variables stay in ADO.",
    fieldCount: 4,
  },
  {
    id: "E31",
    name: "Secure File",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Certs and signing keys stay.",
    fieldCount: 4,
  },
  {
    id: "E32",
    name: "Service Connection",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "OIDC federations stay.",
    fieldCount: 7,
  },
  {
    id: "E33",
    name: "Task Group",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Reusable task groups remain.",
    fieldCount: 5,
  },
  {
    id: "E34",
    name: "Deployment Group",
    service: "pipelines",
    serviceLabel: "Pipelines",
    staysInAdo: "ado",
    pattern: "P5",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Push-style deploy groups stay.",
    fieldCount: 4,
  },

  // Test Plans (E35-E43)
  {
    id: "E35",
    name: "Test Case / Test Plan",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "No GitHub equivalent.",
    fieldCount: 21,
  },
  {
    id: "E36",
    name: "Test Suite",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Hierarchical suites have no GH model.",
    fieldCount: 6,
  },
  {
    id: "E37",
    name: "Test Point",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "ADO-specific concept.",
    fieldCount: 4,
  },
  {
    id: "E38",
    name: "Test Run",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Manual test runs unsupported on GH.",
    fieldCount: 5,
  },
  {
    id: "E39",
    name: "Test Result",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "Automated results surface via Checks API.",
    fieldCount: 6,
  },
  {
    id: "E40",
    name: "Test Configuration",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P5",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Matrix strategy substitutes for automated.",
    fieldCount: 4,
  },
  {
    id: "E41",
    name: "Test Variable",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Parameterization variables tied to Test Plans.",
    fieldCount: 3,
  },
  {
    id: "E42",
    name: "Shared Step",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Reusable steps are pure Test Plans.",
    fieldCount: 3,
  },
  {
    id: "E43",
    name: "Exploratory Session",
    service: "test-plans",
    serviceLabel: "Test Plans",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Session-based testing has no GH twin.",
    fieldCount: 4,
  },

  // Artifacts (E44-E48)
  {
    id: "E44",
    name: "Artifact / Package",
    service: "artifacts",
    serviceLabel: "Artifacts",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Universal/Python/Cargo aren't GH Packages-native.",
    fieldCount: 12,
  },
  {
    id: "E45",
    name: "Feed",
    service: "artifacts",
    serviceLabel: "Artifacts",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Feed-scoped permissions stay.",
    fieldCount: 6,
  },
  {
    id: "E46",
    name: "Package Version",
    service: "artifacts",
    serviceLabel: "Artifacts",
    staysInAdo: "ado",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Versions remain published on ADO Artifacts.",
    fieldCount: 5,
  },
  {
    id: "E47",
    name: "Upstream Source",
    service: "artifacts",
    serviceLabel: "Artifacts",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "medium",
    capabilityPreservation: "low",
    note: "Universal upstream proxying gap on GH.",
    fieldCount: 4,
  },
  {
    id: "E48",
    name: "Retention Policy",
    service: "artifacts",
    serviceLabel: "Artifacts",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "GH Packages retention is simpler.",
    fieldCount: 3,
  },

  // Platform (E49-E63)
  {
    id: "E49",
    name: "User / Identity",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "gh",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "high",
    note: "EMU bridges identity from Entra.",
    fieldCount: 14,
  },
  {
    id: "E50",
    name: "Team",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "gh",
    pattern: "P3",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Recreated as GitHub teams.",
    fieldCount: 11,
  },
  {
    id: "E51",
    name: "Organization / Project",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "gh",
    pattern: "P4",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "ADO 2-level hierarchy flattens on GH.",
    fieldCount: 16,
  },
  {
    id: "E52",
    name: "Wiki",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "both",
    pattern: "P5",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "Project wikis preserved if kept on ADO.",
    fieldCount: 9,
  },
  {
    id: "E53",
    name: "Group (Security)",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "gh",
    pattern: "P4",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Custom permission groups remap.",
    fieldCount: 5,
  },
  {
    id: "E54",
    name: "Permission / ACL",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "both",
    pattern: "P4",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "Major design effort in identity-heavy migrations.",
    fieldCount: 6,
  },
  {
    id: "E55",
    name: "Extension",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "both",
    pattern: "P5",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "Each extension evaluated individually.",
    fieldCount: 4,
  },
  {
    id: "E56",
    name: "Service Hook / Webhook",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "both",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "Event schemas differ.",
    fieldCount: 5,
  },
  {
    id: "E57",
    name: "Audit Log Entry",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "ado",
    pattern: "P2",
    dataPreservation: "medium",
    capabilityPreservation: "medium",
    note: "ADO audit stays for retention overlap.",
    fieldCount: 7,
  },
  {
    id: "E58",
    name: "Personal Access Token",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "gh",
    pattern: "P5",
    dataPreservation: "na",
    capabilityPreservation: "high",
    note: "Users regenerate on GitHub.",
    fieldCount: 5,
  },
  {
    id: "E59",
    name: "Service Principal / App Registration",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "both",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "medium",
    note: "GitHub Apps + OIDC federation rebuild.",
    fieldCount: 6,
  },
  {
    id: "E60",
    name: "Notification Subscription",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "both",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "Filter-based subscriptions don't translate.",
    fieldCount: 4,
  },
  {
    id: "E61",
    name: "Dashboard",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "ado",
    pattern: "P3",
    dataPreservation: "low",
    capabilityPreservation: "low",
    note: "ADO dashboards stay; no native GH composer.",
    fieldCount: 5,
  },
  {
    id: "E62",
    name: "Widget (Dashboard)",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "ado",
    pattern: "P6",
    dataPreservation: "gap",
    capabilityPreservation: "gap",
    note: "Widgets have no GH target.",
    fieldCount: 4,
  },
  {
    id: "E63",
    name: "Wiki Page",
    service: "platform",
    serviceLabel: "Platform",
    staysInAdo: "both",
    pattern: "P1",
    dataPreservation: "high",
    capabilityPreservation: "high",
    note: "Markdown migrates cleanly.",
    fieldCount: 4,
  },
];

export const FEATURES: Feature[] = [
  // Source Control & Collaboration
  {
    id: "F01",
    name: "Git commit & push",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "GEI 1:1; commit SHAs preserved.",
    entities: ["E15"],
  },
  {
    id: "F02",
    name: "Branch management",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Branches migrate; default preserved.",
    entities: ["E15", "E16"],
  },
  {
    id: "F03",
    name: "Branch policies",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P2",
    preservationStrategy: "Map to branch protection rules.",
    entities: ["E15", "E14", "E17"],
  },
  {
    id: "F04",
    name: "Required reviewers",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P2",
    preservationStrategy: "CODEOWNERS + branch protection.",
    entities: ["E14", "E50"],
  },
  {
    id: "F05",
    name: "Pull request review",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "GEI migrates PR threads, iterations.",
    entities: ["E14", "E18", "E19", "E49"],
  },
  {
    id: "F06",
    name: "Code review comments",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P2",
    preservationStrategy: "Threads preserved; rich-text degrades.",
    entities: ["E14", "E19"],
  },
  {
    id: "F07",
    name: "Merge strategies",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Per-repo config maps.",
    entities: ["E15", "E14"],
  },
  {
    id: "F08",
    name: "Suggested changes in review",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Native GitHub UX.",
    entities: ["E14"],
  },
  {
    id: "F09",
    name: "Draft pull requests",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Direct feature parity.",
    entities: ["E14"],
  },
  {
    id: "F10",
    name: "Auto-complete PR",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P2",
    preservationStrategy: "GH auto-merge approximates.",
    entities: ["E14"],
  },
  {
    id: "F11",
    name: "Git LFS",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Pointers + git-lfs migrate.",
    entities: ["E15"],
  },
  {
    id: "F12",
    name: "Repository forks",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P2",
    preservationStrategy: "Internal forks if both ends in scope.",
    entities: ["E15", "E20"],
  },
  {
    id: "F13",
    name: "Submodules",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P2",
    preservationStrategy: "URLs in .gitmodules rewrite.",
    entities: ["E15"],
  },
  {
    id: "F75",
    name: "Code search",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "GitHub code search natively.",
    entities: ["E15"],
  },
  {
    id: "F76",
    name: "Codespaces",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "Net-new capability via migration.",
    entities: ["E15"],
  },
  {
    id: "F78",
    name: "Git history rewrite tooling",
    category: "Source control",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Tools work on any Git repo.",
    entities: ["E15"],
  },

  // Work Planning & Tracking
  {
    id: "F14",
    name: "Work item creation",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO Boards.",
    entities: ["E01"],
  },
  {
    id: "F15",
    name: "Sprint planning",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in Boards.",
    entities: ["E01", "E07", "E50"],
  },
  {
    id: "F16",
    name: "Backlog grooming",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in Boards.",
    entities: ["E01", "E08"],
  },
  {
    id: "F17",
    name: "Area path hierarchy",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO; structural foundation.",
    entities: ["E01", "E04", "E51"],
  },
  {
    id: "F18",
    name: "Iteration path hierarchy",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO.",
    entities: ["E01", "E05", "E50"],
  },
  {
    id: "F19",
    name: "Work item ↔ PR linking",
    category: "Work planning",
    staysInAdo: "both",
    pattern: "P5",
    preservationStrategy: "AB#12345 syntax + ADO-GitHub app.",
    entities: ["E01", "E14"],
  },
  {
    id: "F20",
    name: "Work item hierarchies (parent/child)",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO.",
    entities: ["E01", "E13"],
  },
  {
    id: "F21",
    name: "Query builder / saved queries",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO.",
    entities: ["E01", "E09"],
  },
  {
    id: "F22",
    name: "Kanban / sprint boards",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in Boards.",
    entities: ["E01", "E06"],
  },
  {
    id: "F23",
    name: "Dashboards & widgets",
    category: "Work planning",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Dashboards stay with Boards/Pipelines.",
    entities: ["E01", "E21", "E61", "E62"],
  },

  // CI / CD & Build
  {
    id: "F24",
    name: "CI pipeline (YAML)",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Pipelines stays; webhook trigger from GitHub.",
    entities: ["E21", "E15", "E23"],
  },
  {
    id: "F25",
    name: "Classic (UI) pipelines",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO without rewrite.",
    entities: ["E21", "E24"],
  },
  {
    id: "F26",
    name: "Build triggers (CI/PR)",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Source triggers rewire to GitHub repo.",
    entities: ["E21", "E15", "E56"],
  },
  {
    id: "F27",
    name: "Variable groups",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays intact in ADO.",
    entities: ["E21", "E30"],
  },
  {
    id: "F28",
    name: "Service connections",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "OIDC federation preferred over PAT.",
    entities: ["E21", "E32", "E15"],
  },
  {
    id: "F29",
    name: "Agent pools & self-hosted agents",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Agents stay registered.",
    entities: ["E21", "E27", "E28"],
  },
  {
    id: "F30",
    name: "Release gates & approvals",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Release Definitions remain intact.",
    entities: ["E22", "E29"],
  },
  {
    id: "F31",
    name: "Environments",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Deployment targets stay.",
    entities: ["E21", "E22", "E29"],
  },
  {
    id: "F32",
    name: "Deployment history & traceability",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Records live in ADO.",
    entities: ["E21", "E22", "E26", "E01"],
  },
  {
    id: "F33",
    name: "Build artifacts",
    category: "CI / CD",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Artifacts stay in ADO Artifacts.",
    entities: ["E21", "E44"],
  },

  // Security & Compliance
  {
    id: "F34",
    name: "Secret scanning",
    category: "Security",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "GHAS native + push protection.",
    entities: ["E15"],
  },
  {
    id: "F35",
    name: "Push protection for secrets",
    category: "Security",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "GHAS native; no ADO equivalent.",
    entities: ["E15"],
  },
  {
    id: "F36",
    name: "Dependency scanning (Dependabot)",
    category: "Security",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "EPSS-integrated SCA.",
    entities: ["E15"],
  },
  {
    id: "F37",
    name: "Code scanning (CodeQL)",
    category: "Security",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "Autofix accelerates remediation.",
    entities: ["E15"],
  },
  {
    id: "F38",
    name: "Security advisories",
    category: "Security",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Private vulnerability reporting.",
    entities: ["E15"],
  },
  {
    id: "F39",
    name: "Branch protection for compliance",
    category: "Security",
    staysInAdo: "gh",
    pattern: "P2",
    preservationStrategy: "Rulesets preferred over classic.",
    entities: ["E15", "E14", "E17"],
  },
  {
    id: "F40",
    name: "Audit logs",
    category: "Security",
    staysInAdo: "both",
    pattern: "P2",
    preservationStrategy: "Streams to Azure for compliance overlap.",
    entities: ["E51", "E49", "E57"],
  },
  {
    id: "F41",
    name: "SBOM generation",
    category: "Security",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Native dependency graph + export.",
    entities: ["E15"],
  },
  {
    id: "F42",
    name: "SDL gate enforcement",
    category: "Security",
    staysInAdo: "both",
    pattern: "P3",
    preservationStrategy: "Composes rulesets + GHAS + ADO gates.",
    entities: ["E15", "E21", "E29"],
  },

  // Identity, Teams & Permissions
  {
    id: "F43",
    name: "User authentication (SSO)",
    category: "Identity",
    staysInAdo: "both",
    pattern: "P1",
    preservationStrategy: "Entra SAML/OIDC SSO to GH EMU.",
    entities: ["E49"],
  },
  {
    id: "F44",
    name: "Group/team membership",
    category: "Identity",
    staysInAdo: "both",
    pattern: "P2",
    preservationStrategy: "Team structure remapped per platform.",
    entities: ["E50", "E49"],
  },
  {
    id: "F45",
    name: "Permission levels",
    category: "Identity",
    staysInAdo: "both",
    pattern: "P4",
    preservationStrategy: "Decomposes across enterprise + org + repo.",
    entities: ["E51", "E15", "E50", "E54"],
  },
  {
    id: "F46",
    name: "CODEOWNERS",
    category: "Identity",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "File-based, version-controlled review routing.",
    entities: ["E15", "E50"],
  },
  {
    id: "F47",
    name: "Service principals / workload identity",
    category: "Identity",
    staysInAdo: "both",
    pattern: "P4",
    preservationStrategy: "GitHub Apps + OIDC.",
    entities: ["E49", "E59"],
  },
  {
    id: "F48",
    name: "PAT (personal access tokens)",
    category: "Identity",
    staysInAdo: "both",
    pattern: "P2",
    preservationStrategy: "Tokens regenerate at cutover.",
    entities: ["E49", "E58"],
  },

  // Automation & Extensibility
  {
    id: "F49",
    name: "Webhooks",
    category: "Automation",
    staysInAdo: "both",
    pattern: "P2",
    preservationStrategy: "Re-register URLs; payload shapes differ.",
    entities: ["E15", "E51", "E56"],
  },
  {
    id: "F50",
    name: "Service hooks / integrations",
    category: "Automation",
    staysInAdo: "both",
    pattern: "P4",
    preservationStrategy: "Decomposes across GH Apps + OAuth + webhooks.",
    entities: ["E51", "E55", "E56"],
  },
  {
    id: "F51",
    name: "REST API consumers",
    category: "Automation",
    staysInAdo: "both",
    pattern: "P2",
    preservationStrategy: "Every internal tool rewrites for GH REST/GraphQL.",
    entities: ["E15", "E01"],
  },
  {
    id: "F52",
    name: "Marketplace extensions",
    category: "Automation",
    staysInAdo: "both",
    pattern: "P4",
    preservationStrategy: "GitHub Apps / Actions Marketplace / custom.",
    entities: ["E51", "E55"],
  },
  {
    id: "F53",
    name: "Custom pipeline tasks",
    category: "Automation",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO task library.",
    entities: ["E21", "E33"],
  },
  {
    id: "F54",
    name: "Policy as code",
    category: "Automation",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "GitHub rulesets at org-level.",
    entities: ["E15", "E51"],
  },
  {
    id: "F79",
    name: "Copilot Chat in IDE",
    category: "Automation",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "New capability enabled by migration.",
    entities: ["E15", "E49"],
  },

  // Knowledge & Documentation
  {
    id: "F55",
    name: "Wiki (project wiki)",
    category: "Knowledge",
    staysInAdo: "both",
    pattern: "P2",
    preservationStrategy: "Project wiki migrates; hierarchy flattens.",
    entities: ["E52", "E63"],
  },
  {
    id: "F56",
    name: "Wiki (code wiki)",
    category: "Knowledge",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Code wikis are git-backed.",
    entities: ["E52", "E15"],
  },
  {
    id: "F57",
    name: "README & markdown",
    category: "Knowledge",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Direct migration.",
    entities: ["E15"],
  },
  {
    id: "F58",
    name: "Attachments on work items",
    category: "Knowledge",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays with work items in ADO.",
    entities: ["E01", "E12"],
  },

  // Testing
  {
    id: "F59",
    name: "Manual test cases & test plans",
    category: "Testing",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO Test Plans.",
    entities: ["E35", "E36", "E37"],
  },
  {
    id: "F60",
    name: "Test runs & results",
    category: "Testing",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO.",
    entities: ["E35", "E38", "E39", "E21"],
  },
  {
    id: "F61",
    name: "Test automation results in PR",
    category: "Testing",
    staysInAdo: "both",
    pattern: "P5",
    preservationStrategy: "GitHub Checks API surfaces results from any CI.",
    entities: ["E21", "E14", "E39"],
  },
  {
    id: "F62",
    name: "Code coverage",
    category: "Testing",
    staysInAdo: "both",
    pattern: "P2",
    preservationStrategy: "Codecov/Coveralls work both sides.",
    entities: ["E21", "E15"],
  },

  // Packages & Artifacts
  {
    id: "F63",
    name: "NuGet feeds",
    category: "Packages",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Artifacts stays.",
    entities: ["E44", "E45"],
  },
  {
    id: "F64",
    name: "npm feeds",
    category: "Packages",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Artifacts stays.",
    entities: ["E44", "E45"],
  },
  {
    id: "F65",
    name: "Maven feeds",
    category: "Packages",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Artifacts stays.",
    entities: ["E44", "E45"],
  },
  {
    id: "F66",
    name: "Python feeds",
    category: "Packages",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "GH Packages has no Python; Artifacts stays.",
    entities: ["E44", "E45"],
  },
  {
    id: "F67",
    name: "Universal packages",
    category: "Packages",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "No GH equivalent; Artifacts stays.",
    entities: ["E44", "E45"],
  },
  {
    id: "F68",
    name: "Container registry",
    category: "Packages",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Container images stay on ACR / Artifacts.",
    entities: ["E44"],
  },
  {
    id: "F69",
    name: "Upstream sources",
    category: "Packages",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Cached upstream feeds stay.",
    entities: ["E44", "E47"],
  },

  // Reporting & Analytics
  {
    id: "F70",
    name: "Delivery plans",
    category: "Reporting",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in ADO.",
    entities: ["E01", "E50"],
  },
  {
    id: "F71",
    name: "Velocity / burndown charts",
    category: "Reporting",
    staysInAdo: "ado",
    pattern: "P6",
    preservationStrategy: "Stays in Boards.",
    entities: ["E01", "E50", "E07"],
  },
  {
    id: "F72",
    name: "Code activity metrics",
    category: "Reporting",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "GitHub Insights provides richer code analytics.",
    entities: ["E15", "E49"],
  },
  {
    id: "F73",
    name: "Copilot usage metrics",
    category: "Reporting",
    staysInAdo: "gh",
    pattern: "P1",
    preservationStrategy: "Copilot Business/Enterprise admin metrics.",
    entities: ["E49"],
  },
  {
    id: "F74",
    name: "Compliance reporting",
    category: "Reporting",
    staysInAdo: "both",
    pattern: "P4",
    preservationStrategy: "Aggregates ADO + GitHub + security tooling.",
    entities: ["E51"],
  },

  // Release Events
  {
    id: "F77",
    name: "GitHub Releases",
    category: "Release events",
    staysInAdo: "gh",
    pattern: "P5",
    preservationStrategy: "Tag + notes + artifacts in one event.",
    entities: ["E15"],
  },
];

const FEATURE_INDEX: Record<string, Feature> = Object.fromEntries(
  FEATURES.map((f) => [f.id, f]),
);

function f(...ids: string[]): string[] {
  return ids.filter((id) => FEATURE_INDEX[id]);
}

export const JTBDS: Jtbd[] = [
  // Code work
  {
    id: "J01",
    name: "Commit and push code",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact:
      "Direct migration via GEI. Git CLI workflow unchanged; remote URL updates at cutover.",
    features: f("F01"),
  },
  {
    id: "J02",
    name: "Create a feature branch",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact:
      "Branch protection may differ from ADO branch policies — discovery verifies.",
    features: f("F02"),
  },
  {
    id: "J03",
    name: "Rebase or merge from main",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Unchanged. Git semantics are identical.",
    features: f("F01", "F02"),
  },
  {
    id: "J04",
    name: "Cherry-pick a commit",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Unchanged. Pure git operation.",
    features: f("F01"),
  },
  {
    id: "J05",
    name: "Revert a bad commit",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Unchanged. Git revert semantics hold.",
    features: f("F01"),
  },
  {
    id: "J06",
    name: "Resolve a merge conflict",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "GitHub web UI for conflicts differs from ADO but functional.",
    features: f("F01", "F05"),
  },
  {
    id: "J07",
    name: "Tag a release",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Linking tags to Releases follows GitHub conventions.",
    features: f("F01"),
  },
  {
    id: "J08",
    name: "Clone a repository locally",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "New clone URLs post-migration.",
    features: f("F01"),
  },
  {
    id: "J09",
    name: "Use Git LFS for large files",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "LFS pointers migrate via GEI; objects need separate verification.",
    features: f("F11"),
  },
  {
    id: "J10",
    name: "Update a submodule reference",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "URL rewrites required in .gitmodules across consuming repos.",
    features: f("F13"),
  },
  {
    id: "J11",
    name: "Search for code across repos",
    category: "code",
    categoryLabel: "Code work",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "GitHub code search is richer than ADO search; net gain.",
    features: f("F75"),
  },

  // Pull requests & review
  {
    id: "J12",
    name: "Open a pull request",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "GitHub PR UX is different from ADO but widely recognized.",
    features: f("F05", "F09"),
  },
  {
    id: "J13",
    name: "Review a pull request",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Tech Lead",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "GitHub review ergonomics are a net gain.",
    features: f("F05", "F06", "F08"),
  },
  {
    id: "J14",
    name: "Request changes on a PR",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Tech Lead",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "ADO Reject/Wait maps to GitHub Request changes; some enum loss.",
    features: f("F06"),
  },
  {
    id: "J15",
    name: "Approve and merge a PR",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Tech Lead",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Auto-merge differs on conflict handling.",
    features: f("F07", "F10", "F04", "F03"),
  },
  {
    id: "J16",
    name: "Link a PR to a work item",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Critical hybrid friction point. AB#12345 syntax bridges to ADO.",
    features: f("F19"),
  },
  {
    id: "J17",
    name: "Check branch policy compliance",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Enforced via branch protection + CODEOWNERS + required checks.",
    features: f("F03", "F04"),
  },
  {
    id: "J18",
    name: "Assign required reviewers",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Tech Lead",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "CODEOWNERS file becomes the source of truth.",
    features: f("F04"),
  },
  {
    id: "J19",
    name: "Convert a draft PR to ready",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Direct feature parity.",
    features: f("F09"),
  },
  {
    id: "J20",
    name: "Reply to PR comments",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact:
      "Threaded comment experience preserved with minor formatting changes.",
    features: f("F06"),
  },
  {
    id: "J21",
    name: "Close a PR without merging",
    category: "pull-requests",
    categoryLabel: "Pull requests & review",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Unchanged workflow; PR history preserved.",
    features: f("F05"),
  },

  // Work planning & tracking
  {
    id: "J22",
    name: "Create a work item",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "No workflow change for Boards users.",
    features: f("F14"),
  },
  {
    id: "J23",
    name: "Update work-item status",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Stays in ADO. Cross-platform context switch.",
    features: f("F14"),
  },
  {
    id: "J24",
    name: "View my assigned work",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Stays in ADO.",
    features: f("F21"),
  },
  {
    id: "J25",
    name: "Plan a sprint",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Tech Lead",
    frequency: "Per-sprint",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Iteration paths, capacity planning preserved.",
    features: f("F15", "F17", "F18"),
  },
  {
    id: "J26",
    name: "Groom the backlog",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Tech Lead",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Hierarchical parent/child preserved.",
    features: f("F16", "F20"),
  },
  {
    id: "J27",
    name: "Write a WIQL query",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Tech Lead",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Query-driven views preserved.",
    features: f("F21"),
  },
  {
    id: "J28",
    name: "Update Kanban board",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Tech Lead",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Column config, swimlanes preserved.",
    features: f("F22"),
  },
  {
    id: "J29",
    name: "Create a work-item hierarchy",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "PM",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Epic/Feature/Story rollup preserved.",
    features: f("F20"),
  },
  {
    id: "J30",
    name: "Attach a file to a work item",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Attachment UI unchanged.",
    features: f("F58"),
  },
  {
    id: "J31",
    name: "Run a team retrospective",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Tech Lead",
    frequency: "Per-sprint",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Velocity charts preserved.",
    features: f("F21", "F71"),
  },
  {
    id: "J32",
    name: "Report a bug",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Bug work-item type preserved.",
    features: f("F14"),
  },
  {
    id: "J33",
    name: "View team velocity",
    category: "work-planning",
    categoryLabel: "Work planning & tracking",
    persona: "PM",
    frequency: "Per-sprint",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Charts and trend views unchanged.",
    features: f("F71", "F15", "F18"),
  },

  // CI / CD & builds
  {
    id: "J34",
    name: "Trigger a CI build",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Webhook from GitHub push triggers ADO.",
    features: f("F26", "F28", "F29", "F49"),
  },
  {
    id: "J35",
    name: "View build logs",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Cross-platform context switch to ADO for logs.",
    features: f("F26", "F28"),
  },
  {
    id: "J36",
    name: "Debug a failing build",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Friction point when build is in different platform than code.",
    features: f("F26", "F28", "F29"),
  },
  {
    id: "J37",
    name: "Edit a pipeline YAML",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "ADO YAML and GH Actions YAML differ significantly.",
    features: f("F24"),
  },
  {
    id: "J38",
    name: "Configure a build trigger",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "New service connection if Pipelines stays and code moves.",
    features: f("F26"),
  },
  {
    id: "J39",
    name: "Manage variable groups",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Platform Engineer",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Stays in ADO if Pipelines stays.",
    features: f("F27"),
  },
  {
    id: "J40",
    name: "Manage service connections",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Credentials don't migrate; OIDC re-registered.",
    features: f("F28"),
  },
  {
    id: "J41",
    name: "Manage a self-hosted agent",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Platform Engineer",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Reinstall as GH runners or keep as ADO agents.",
    features: f("F29"),
  },
  {
    id: "J42",
    name: "Install a custom pipeline task",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Platform Engineer",
    frequency: "Rare",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Custom tasks require rewrite as composite actions if migrating.",
    features: f("F53"),
  },
  {
    id: "J43",
    name: "Manage build artifacts",
    category: "ci-cd",
    categoryLabel: "CI / CD & builds",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Stays in Artifacts if Pipelines stays.",
    features: f("F33"),
  },

  // Deploy & release
  {
    id: "J44",
    name: "Deploy to staging",
    category: "deploy",
    categoryLabel: "Deploy & release",
    persona: "Release Manager",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Release Definitions stay in ADO under hybrid.",
    features: f("F31", "F47", "F28"),
  },
  {
    id: "J45",
    name: "Deploy to production",
    category: "deploy",
    categoryLabel: "Deploy & release",
    persona: "Release Manager",
    frequency: "Per-release",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Release gates stay in ADO if Pipelines stays.",
    features: f("F31", "F32", "F47", "F28"),
  },
  {
    id: "J46",
    name: "Approve a release",
    category: "deploy",
    categoryLabel: "Deploy & release",
    persona: "Tech Lead",
    frequency: "Per-release",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Approval UX unchanged.",
    features: f("F30"),
  },
  {
    id: "J47",
    name: "Roll back a deployment",
    category: "deploy",
    categoryLabel: "Deploy & release",
    persona: "Release Manager",
    frequency: "Rare",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Rollback mechanics differ in Actions.",
    features: f("F31", "F47", "F28"),
  },
  {
    id: "J48",
    name: "Deploy a hotfix",
    category: "deploy",
    categoryLabel: "Deploy & release",
    persona: "Developer",
    frequency: "Per-release",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Code on GitHub; deployment per hybrid decision.",
    features: f("F01", "F07", "F31", "F47", "F28"),
  },
  {
    id: "J49",
    name: "View deployment history",
    category: "deploy",
    categoryLabel: "Deploy & release",
    persona: "Release Manager",
    frequency: "Weekly",
    staysInAdo: "ado",
    staysReason: "Pipelines stays in ADO",
    impact: "Historical records stay in ADO.",
    features: f("F32"),
  },
  {
    id: "J50",
    name: "Schedule a release window",
    category: "deploy",
    categoryLabel: "Deploy & release",
    persona: "Release Manager",
    frequency: "Per-release",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Branch freeze on GH; release in ADO Pipelines.",
    features: f("F03"),
  },

  // Testing & QA
  {
    id: "J51",
    name: "Run automated tests in CI",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "both",
    staysReason: "tests run in ADO; results in GH PR",
    impact: "Test results surface in GitHub PR via Checks API.",
    features: f("F61"),
  },
  {
    id: "J52",
    name: "Review test results in PR",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "both",
    staysReason: "tests run in ADO; results in GH PR",
    impact: "Checks API displays results natively.",
    features: f("F61"),
  },
  {
    id: "J53",
    name: "Run a manual test plan",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "QA",
    frequency: "Per-release",
    staysInAdo: "ado",
    staysReason: "Test Plans stays in ADO",
    impact: "No GitHub equivalent for structured test plans.",
    features: f("F59", "F60"),
  },
  {
    id: "J54",
    name: "Log a test result manually",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "QA",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Test Plans stays in ADO",
    impact: "Manual test execution UI preserved.",
    features: f("F60", "F59"),
  },
  {
    id: "J55",
    name: "Run an exploratory test session",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "QA",
    frequency: "Per-release",
    staysInAdo: "ado",
    staysReason: "Test Plans stays in ADO",
    impact: "No GitHub equivalent for exploratory sessions.",
    features: f("F59"),
  },
  {
    id: "J56",
    name: "Track code coverage",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "Tech Lead",
    frequency: "Weekly",
    staysInAdo: "both",
    staysReason: "coverage from ADO; surfaced on GH PR",
    impact: "Codecov/Coveralls work both sides.",
    features: f("F62", "F61"),
  },
  {
    id: "J57",
    name: "Link a bug to a test case",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "QA",
    frequency: "Per-release",
    staysInAdo: "ado",
    staysReason: "Boards + Test Plans both in ADO",
    impact: "Linking preserved within ADO.",
    features: f("F59"),
  },
  {
    id: "J58",
    name: "File a regression report",
    category: "testing",
    categoryLabel: "Testing & QA",
    persona: "QA",
    frequency: "Per-release",
    staysInAdo: "ado",
    staysReason: "Boards + Test Plans both in ADO",
    impact: "No cross-platform boundary.",
    features: f("F59"),
  },

  // Security & compliance
  {
    id: "J59",
    name: "Respond to a secret-scanning alert",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "GHAS native on GitHub",
    impact:
      "Push protection prevents commits with secrets. Net capability gain.",
    features: f("F34", "F35"),
  },
  {
    id: "J60",
    name: "Review a Dependabot alert",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "GHAS native on GitHub",
    impact: "GHAS native; broader coverage with EPSS.",
    features: f("F36"),
  },
  {
    id: "J61",
    name: "Fix a code-scanning finding",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "GHAS native on GitHub",
    impact: "CodeQL + Autofix in PR flow. Net capability gain.",
    features: f("F37", "F01"),
  },
  {
    id: "J62",
    name: "Respond to a security advisory",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Rare",
    staysInAdo: "gh",
    staysReason: "GHAS native on GitHub",
    impact: "Private vulnerability reporting natively supported.",
    features: f("F38", "F01"),
  },
  {
    id: "J63",
    name: "Enforce SDL gates on a PR",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Daily",
    staysInAdo: "both",
    staysReason: "spans rulesets + ADO gates",
    impact: "Composes GitHub rulesets + GHAS + ADO checks.",
    features: f("F42", "F39"),
  },
  {
    id: "J64",
    name: "Audit permission changes",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Weekly",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Audit logs on both sides; event taxonomies differ.",
    features: f("F40", "F45"),
  },
  {
    id: "J65",
    name: "Generate a compliance report",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Per-audit",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Aggregates ADO + GitHub audit + security tooling.",
    features: f("F74", "F40"),
  },
  {
    id: "J66",
    name: "Respond to a regulatory audit",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Rare",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Evidence spans ADO and GitHub. Cross-system gather required.",
    features: f("F74", "F40", "F59"),
  },
  {
    id: "J67",
    name: "Generate an SBOM",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Per-release",
    staysInAdo: "gh",
    staysReason: "lives on GitHub",
    impact: "Native dependency graph + export. Net capability gain.",
    features: f("F41"),
  },
  {
    id: "J68",
    name: "Enforce branch protection for compliance",
    category: "security",
    categoryLabel: "Security & compliance",
    persona: "Security",
    frequency: "Per-project",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Rulesets preferred over classic branch protection.",
    features: f("F39", "F03"),
  },

  // Identity & access
  {
    id: "J69",
    name: "Sign in with SSO",
    category: "identity",
    categoryLabel: "Identity & access",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Entra SAML/OIDC to GitHub EMU; users org-scoped.",
    features: f("F43"),
  },
  {
    id: "J70",
    name: "Grant repo access to a team",
    category: "identity",
    categoryLabel: "Identity & access",
    persona: "Tech Lead",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Team structure remapped; nesting may flatten.",
    features: f("F44", "F45"),
  },
  {
    id: "J71",
    name: "Request access to a repo",
    category: "identity",
    categoryLabel: "Identity & access",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "New request flow via GitHub.",
    features: f("F45"),
  },
  {
    id: "J72",
    name: "Rotate a personal access token",
    category: "identity",
    categoryLabel: "Identity & access",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "both",
    staysReason: "PATs needed on both platforms",
    impact: "Tokens don't migrate; users recreate at cutover.",
    features: f("F48"),
  },
  {
    id: "J73",
    name: "Register a service principal",
    category: "identity",
    categoryLabel: "Identity & access",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "GitHub Apps + OIDC to Azure.",
    features: f("F47"),
  },
  {
    id: "J74",
    name: "Audit cross-org permissions",
    category: "identity",
    categoryLabel: "Identity & access",
    persona: "Security",
    frequency: "Per-audit",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Decomposed into enterprise + org + repo + ruleset roles.",
    features: f("F45", "F40"),
  },
  {
    id: "J75",
    name: "Configure CODEOWNERS",
    category: "identity",
    categoryLabel: "Identity & access",
    persona: "Tech Lead",
    frequency: "Per-project",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Substitution for ADO path-based required reviewers.",
    features: f("F46", "F04"),
  },

  // Integrations & automation
  {
    id: "J76",
    name: "Configure a webhook",
    category: "automation",
    categoryLabel: "Integrations & automation",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Re-register URLs; payload shapes differ.",
    features: f("F49"),
  },
  {
    id: "J77",
    name: "Install a marketplace app",
    category: "automation",
    categoryLabel: "Integrations & automation",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Different marketplace; per-platform install.",
    features: f("F52"),
  },
  {
    id: "J78",
    name: "Write automation against the API",
    category: "automation",
    categoryLabel: "Integrations & automation",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "REST/GraphQL rewrite per consumer.",
    features: f("F51"),
  },
  {
    id: "J79",
    name: "Integrate with Slack/Teams",
    category: "automation",
    categoryLabel: "Integrations & automation",
    persona: "Tech Lead",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "GitHub native integrations; reconfigure per repo/org.",
    features: f("F50"),
  },
  {
    id: "J80",
    name: "Set up a ChatOps bot",
    category: "automation",
    categoryLabel: "Integrations & automation",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Webhook payloads differ; bot logic may update.",
    features: f("F50", "F49"),
  },

  // Reporting & metrics
  {
    id: "J81",
    name: "View a team dashboard",
    category: "reporting",
    categoryLabel: "Reporting & metrics",
    persona: "Tech Lead",
    frequency: "Daily",
    staysInAdo: "ado",
    staysReason: "Boards/Pipelines dashboards stay",
    impact: "Decomposes ADO Boards dashboards + GH Insights + BI.",
    features: f("F23"),
  },
  {
    id: "J82",
    name: "Check DORA metrics",
    category: "reporting",
    categoryLabel: "Reporting & metrics",
    persona: "PM",
    frequency: "Weekly",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Code-side in GH Insights; work-side spans both.",
    features: f("F72", "F32"),
  },
  {
    id: "J83",
    name: "View Copilot adoption",
    category: "reporting",
    categoryLabel: "Reporting & metrics",
    persona: "PM",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Copilot admin console",
    impact: "New capability unlocked by migration.",
    features: f("F73"),
  },
  {
    id: "J84",
    name: "Pull a portfolio rollup for execs",
    category: "reporting",
    categoryLabel: "Reporting & metrics",
    persona: "PM",
    frequency: "Rare",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Delivery plans stay in ADO; rollup aggregates.",
    features: f("F23", "F33", "F70"),
  },
  {
    id: "J85",
    name: "Track security posture",
    category: "reporting",
    categoryLabel: "Reporting & metrics",
    persona: "Security",
    frequency: "Weekly",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Aggregates ADO audit + GitHub audit + GHAS findings.",
    features: f("F74", "F40"),
  },

  // Code comprehension & navigation
  {
    id: "J86",
    name: "Orient in an unfamiliar codebase",
    category: "code-comprehension",
    categoryLabel: "Code comprehension",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "code on GH; some wikis in ADO",
    impact: "GitHub code search + Copilot Chat are net-new.",
    features: f("F01", "F55", "F56", "F57", "F75"),
  },
  {
    id: "J87",
    name: "Find a specific PR or commit",
    category: "code-comprehension",
    categoryLabel: "Code comprehension",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Search syntax differs; PR history migrates via GEI.",
    features: f("F01", "F75"),
  },
  {
    id: "J88",
    name: "Locate a repository",
    category: "code-comprehension",
    categoryLabel: "Code comprehension",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Enterprise search across orgs and repos.",
    features: f("F75"),
  },
  {
    id: "J89",
    name: "Understand who owns a file",
    category: "code-comprehension",
    categoryLabel: "Code comprehension",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "gh",
    staysReason: "lives on GitHub",
    impact: "CODEOWNERS at repo root is grep-able.",
    features: f("F46"),
  },
  {
    id: "J90",
    name: "Read repository documentation",
    category: "code-comprehension",
    categoryLabel: "Code comprehension",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "wikis on both",
    impact: "Project wiki migrates; hierarchy flattens.",
    features: f("F55", "F56", "F57"),
  },
  {
    id: "J91",
    name: "Ask a question about the codebase",
    category: "code-comprehension",
    categoryLabel: "Code comprehension",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Copilot admin console",
    impact: "Net-new capability. Copilot Chat is native.",
    features: f("F79"),
  },

  // Onboarding & environment
  {
    id: "J92",
    name: "Receive platform access (new hire)",
    category: "onboarding",
    categoryLabel: "Onboarding & environment",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "users provisioned on both via Entra",
    impact: "EMU account via SCIM; team membership syncs from Entra.",
    features: f("F43", "F44"),
  },
  {
    id: "J93",
    name: "Set up a local dev environment",
    category: "onboarding",
    categoryLabel: "Onboarding & environment",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Devcontainer-first approach in GitHub; clone path preserved.",
    features: f("F01"),
  },
  {
    id: "J94",
    name: "Open a Codespace",
    category: "onboarding",
    categoryLabel: "Onboarding & environment",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Net-new capability. Cloud dev environment in minutes.",
    features: f("F76"),
  },
  {
    id: "J95",
    name: "Find a starter or good-first-issue task",
    category: "onboarding",
    categoryLabel: "Onboarding & environment",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "ado",
    staysReason: "Boards stays in ADO",
    impact: "Work items stay in Boards; query pattern unchanged.",
    features: f("F21"),
  },
  {
    id: "J96",
    name: "Learn team workflow conventions",
    category: "onboarding",
    categoryLabel: "Onboarding & environment",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Some on GH (rulesets, templates); some in ADO.",
    features: f("F52", "F49", "F57"),
  },
  {
    id: "J97",
    name: "Complete first PR as onboarding milestone",
    category: "onboarding",
    categoryLabel: "Onboarding & environment",
    persona: "Developer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "PR on GH; first work item in ADO",
    impact: "GitHub contribution graph as activity signal.",
    features: f("F01", "F12", "F15"),
  },

  // Review workflow
  {
    id: "J98",
    name: "View my review queue",
    category: "review-workflow",
    categoryLabel: "Review workflow",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "CODEOWNERS auto-requests reviewers more predictably.",
    features: f("F04"),
  },
  {
    id: "J99",
    name: "Receive a CI failure notification",
    category: "review-workflow",
    categoryLabel: "Review workflow",
    persona: "Developer",
    frequency: "Daily",
    staysInAdo: "both",
    staysReason: "build runs in ADO; failure routes to GH or chat",
    impact: "Notification source follows the pipeline.",
    features: f("F49"),
  },
  {
    id: "J100",
    name: "Reproduce a failing build locally",
    category: "review-workflow",
    categoryLabel: "Review workflow",
    persona: "Developer",
    frequency: "Weekly",
    staysInAdo: "both",
    staysReason: "config in ADO; clone from GH",
    impact: "Local-tooling concern largely unaffected.",
    features: f("F01", "F29"),
  },
  {
    id: "J101",
    name: "Investigate a regression via git bisect",
    category: "review-workflow",
    categoryLabel: "Review workflow",
    persona: "Developer",
    frequency: "Per-release",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Pure git operation; no platform delta.",
    features: f("F01"),
  },

  // Admin & platform
  {
    id: "J102",
    name: "Create a new repository",
    category: "admin",
    categoryLabel: "Admin & platform",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "GH repo creation; ADO team association",
    impact: "Default rulesets and templates shape the baseline.",
    features: f("F01"),
  },
  {
    id: "J103",
    name: "Configure repo policies at creation",
    category: "admin",
    categoryLabel: "Admin & platform",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Org-level rulesets vs ADO branch policies.",
    features: f("F03", "F39", "F54"),
  },
  {
    id: "J104",
    name: "Invite a user to a repo",
    category: "admin",
    categoryLabel: "Admin & platform",
    persona: "Tech Lead",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Team-based grant preferred; EMU enforces scoping.",
    features: f("F44", "F45"),
  },
  {
    id: "J105",
    name: "Transfer a repo between orgs",
    category: "admin",
    categoryLabel: "Admin & platform",
    persona: "Platform Engineer",
    frequency: "Rare",
    staysInAdo: "both",
    staysReason: "GH transfer; ADO links update",
    impact: "URL redirects preserve links; webhooks reconfigure.",
    features: f("F01"),
  },
  {
    id: "J106",
    name: "Archive a repo",
    category: "admin",
    categoryLabel: "Admin & platform",
    persona: "Platform Engineer",
    frequency: "Rare",
    staysInAdo: "both",
    staysReason: "GH archive; ADO links noted",
    impact: "Recoverable decision; read-only access preserved.",
    features: f("F01"),
  },
  {
    id: "J107",
    name: "Offboard / deactivate a user",
    category: "admin",
    categoryLabel: "Admin & platform",
    persona: "Platform Engineer",
    frequency: "Per-project",
    staysInAdo: "both",
    staysReason: "deactivate via Entra to both",
    impact: "SCIM deprovisioning flows to GH EMU.",
    features: f("F43", "F44"),
  },
  {
    id: "J108",
    name: "Transfer ownership of orphan resources",
    category: "admin",
    categoryLabel: "Admin & platform",
    persona: "Platform Engineer",
    frequency: "Rare",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Repos, PRs, bots reassigned post-offboard.",
    features: f("F44", "F45"),
  },

  // Policy & governance
  {
    id: "J109",
    name: "Roll out a policy across many repos",
    category: "policy",
    categoryLabel: "Policy & governance",
    persona: "Security",
    frequency: "Per-audit",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact: "Org-level rulesets — single biggest improvement over ADO.",
    features: f("F54", "F39"),
  },
  {
    id: "J110",
    name: "Verify policy coverage",
    category: "policy",
    categoryLabel: "Policy & governance",
    persona: "Security",
    frequency: "Per-audit",
    staysInAdo: "gh",
    staysReason: "lives on GitHub",
    impact: "Ruleset evaluation reports — richer than ADO.",
    features: f("F54"),
  },
  {
    id: "J111",
    name: "Grant a policy exception",
    category: "policy",
    categoryLabel: "Policy & governance",
    persona: "Security",
    frequency: "Rare",
    staysInAdo: "gh",
    staysReason: "lives on GitHub",
    impact: "Bypass actors on rulesets; auditable.",
    features: f("F54"),
  },

  // Incident response
  {
    id: "J112",
    name: "Receive an on-call page",
    category: "incident",
    categoryLabel: "Incident response",
    persona: "Release Manager",
    frequency: "Rare",
    staysInAdo: "both",
    staysReason: "pages from either platform",
    impact: "Webhook integration reconfigured at cutover.",
    features: f("F49", "F50"),
  },
  {
    id: "J113",
    name: "Rotate a credential urgently",
    category: "incident",
    categoryLabel: "Incident response",
    persona: "Platform Engineer",
    frequency: "Rare",
    staysInAdo: "both",
    staysReason: "rotate on both",
    impact: "OIDC federation reduces rotation urgency.",
    features: f("F48", "F47"),
  },
  {
    id: "J114",
    name: "Purge sensitive data from git history",
    category: "incident",
    categoryLabel: "Incident response",
    persona: "Security",
    frequency: "Rare",
    staysInAdo: "gh",
    staysReason: "Repos moves to GitHub",
    impact:
      "BFG/filter-repo platform-agnostic; push protection prevents recurrence.",
    features: f("F01", "F35", "F78"),
  },
  {
    id: "J115",
    name: "Run a postmortem",
    category: "incident",
    categoryLabel: "Incident response",
    persona: "Tech Lead",
    frequency: "Rare",
    staysInAdo: "both",
    staysReason: "spans both platforms",
    impact: "Postmortem record in Boards; code refs in GitHub.",
    features: f("F57"),
  },

  // Release events
  {
    id: "J116",
    name: "Create a formal release",
    category: "release-events",
    categoryLabel: "Release events",
    persona: "Release Manager",
    frequency: "Per-release",
    staysInAdo: "both",
    staysReason: "release on GH; publish in ADO",
    impact: "GitHub Releases is richer than ADO's tag-only approach.",
    features: f("F01", "F77"),
  },
  {
    id: "J117",
    name: "Generate release notes / changelog",
    category: "release-events",
    categoryLabel: "Release events",
    persona: "Release Manager",
    frequency: "Per-release",
    staysInAdo: "ado",
    staysReason: "generated by ADO Pipelines",
    impact: "GitHub auto-generated notes from PRs is net-new.",
    features: f("F77"),
  },
  {
    id: "J118",
    name: "Publish release artifacts",
    category: "release-events",
    categoryLabel: "Release events",
    persona: "Release Manager",
    frequency: "Per-release",
    staysInAdo: "both",
    staysReason: "publish from ADO; release on GH",
    impact: "GH Releases supports artifacts; Packages for feeds.",
    features: f("F33", "F77"),
  },
];

// ── Quick lookups ─────────────────────────────────────────────────────────────

export const ENTITY_BY_ID: Record<string, Entity> = Object.fromEntries(
  ENTITIES.map((e) => [e.id, e]),
);
export const FEATURE_BY_ID: Record<string, Feature> = Object.fromEntries(
  FEATURES.map((f) => [f.id, f]),
);
export const JTBD_BY_ID: Record<string, Jtbd> = Object.fromEntries(
  JTBDS.map((j) => [j.id, j]),
);

/** All JTBDs that depend on a given feature. Used for M:N reverse lookup. */
export const JTBDS_BY_FEATURE: Record<string, string[]> = (() => {
  const map: Record<string, string[]> = {};
  for (const j of JTBDS) {
    for (const fid of j.features) {
      if (!map[fid]) map[fid] = [];
      map[fid].push(j.id);
    }
  }
  return map;
})();

/** All features that depend on a given entity. */
export const FEATURES_BY_ENTITY: Record<string, string[]> = (() => {
  const map: Record<string, string[]> = {};
  for (const f of FEATURES) {
    for (const eid of f.entities) {
      if (!map[eid]) map[eid] = [];
      map[eid].push(f.id);
    }
  }
  return map;
})();
