/**
 * Field-level inventory — the atoms layer of the migration framework.
 *
 * Every field defined on the entities in `inventory-framework.ts` is
 * catalogued here with: name, data type, GitHub target, migration pattern,
 * data-preservation rating, preservation strategy, and notes.
 *
 * Source: P.14 §02.3 of the Migration Framework standalone doc. Verbatim
 * encoding — discovery validates each row, but the structure is settled.
 */

import type { Pattern } from "./inventory-framework";

export type FieldFidelity = "high" | "medium" | "low" | "gap" | "na";

export type Field = {
  id: string; // e.g. "FLD-E01-01"
  entityId: string; // e.g. "E01"
  name: string;
  dataType: string;
  githubTarget: string;
  pattern: Pattern | "na";
  dataPreservation: FieldFidelity;
  strategy: string;
  notes: string;
};

const f = (
  entityId: string,
  index: number,
  name: string,
  dataType: string,
  githubTarget: string,
  pattern: Pattern | "na",
  dataPreservation: FieldFidelity,
  strategy: string,
  notes: string,
): Field => ({
  id: `FLD-${entityId}-${String(index).padStart(2, "0")}`,
  entityId,
  name,
  dataType,
  githubTarget,
  pattern,
  dataPreservation,
  strategy,
  notes,
});

export const FIELDS: Field[] = [
  // ============ E01 Work Item (38 fields) ============
  f(
    "E01",
    1,
    "Title",
    "string(255)",
    "*Issue.title* → `string`",
    "P1",
    "high",
    "1:1 direct copy",
    "Clean mapping. No transformation.",
  ),
  f(
    "E01",
    2,
    "Description",
    "HTML/markdown",
    "*Issue.body* → `markdown`",
    "P2",
    "medium",
    "HTML → markdown conversion",
    "HTML formatting often lossy. Embedded images require re-upload.",
  ),
  f(
    "E01",
    3,
    "AssignedTo",
    "identity ref",
    "*Issue.assignees* → `user[]`",
    "P1",
    "high",
    "Identity mapping via Entra ID",
    "GitHub allows multiple assignees; ADO allows one. 1:1 mapping still works.",
  ),
  f(
    "E01",
    4,
    "State",
    "enum",
    "*Issue.state* + *Project column* + *Labels*",
    "P4",
    "medium",
    "Decompose: state → open/closed + assignee + column",
    "ADO's Active/Resolved/Closed conflates workflow-state and ownership.",
  ),
  f(
    "E01",
    5,
    "Reason",
    "enum (state-dependent)",
    "*Issue.state_reason* → *limited values*",
    "P2",
    "low",
    "Map to closest enum or drop",
    "ADO has rich state-transition reasons; GitHub has only completed/not_planned/reopened.",
  ),
  f(
    "E01",
    6,
    "AreaPath",
    "hierarchical tree",
    "*Labels* + *CODEOWNERS* + *Repo*",
    "P4",
    "low",
    "Decompose: hierarchy → flat labels; ownership → CODEOWNERS",
    "Hierarchy lost. Queries by parent area must be rewritten.",
  ),
  f(
    "E01",
    7,
    "IterationPath",
    "hierarchical tree",
    "*Milestone* + *Project column*",
    "P3",
    "medium",
    "Compose: iteration → milestone + date-range label",
    "Sprint structure preserved via composition.",
  ),
  f(
    "E01",
    8,
    "Priority",
    "enum (1–4)",
    "*Label* → `priority:1` etc.",
    "P2",
    "medium",
    "Enum → label values",
    "Works but changes querying pattern.",
  ),
  f(
    "E01",
    9,
    "Severity",
    "enum",
    "*Label* → `severity:critical` etc.",
    "P2",
    "medium",
    "Enum → label values",
    "Same treatment as Priority.",
  ),
  f(
    "E01",
    10,
    "Tags",
    "string (semicolon-separated)",
    "*Issue.labels*",
    "P1",
    "high",
    "Split by delimiter → individual labels",
    "Clean. Tag governance may tighten on GitHub side.",
  ),
  f(
    "E01",
    11,
    "History",
    "append-only audit log",
    "*Issue comments* + *Issue events*",
    "P2",
    "medium",
    "Append as read-only migration comment",
    "GitHub events are system-generated only; historical ADO changes become comments.",
  ),
  f(
    "E01",
    12,
    "CreatedBy",
    "identity ref",
    "*Issue.user* (creator)",
    "P1",
    "high",
    "Identity mapping",
    "Via mannequin reclamation if identity doesn't pre-exist.",
  ),
  f(
    "E01",
    13,
    "CreatedDate",
    "datetime",
    "*Issue.created_at*",
    "P1",
    "high",
    "1:1 direct copy",
    "ISO datetime, trivial mapping.",
  ),
  f(
    "E01",
    14,
    "ChangedBy",
    "identity ref",
    "*Last commenter / event actor*",
    "P2",
    "low",
    "Implicit via last event",
    "GitHub doesn't track a 'last changed by' field directly.",
  ),
  f(
    "E01",
    15,
    "ChangedDate",
    "datetime",
    "*Issue.updated_at*",
    "P1",
    "high",
    "1:1 direct copy",
    "System-maintained on GitHub side.",
  ),
  f(
    "E01",
    16,
    "Parent (link)",
    "work item ref",
    "*Sub-issue* or *Task list checkbox*",
    "P2",
    "medium",
    "Convert to sub-issue or checklist",
    "GitHub now supports sub-issues natively (2024+).",
  ),
  f(
    "E01",
    17,
    "Child (link)",
    "work item ref",
    "*Sub-issue*",
    "P2",
    "medium",
    "Convert to sub-issue",
    "Inverse relationship of Parent.",
  ),
  f(
    "E01",
    18,
    "Related (link)",
    "work item ref",
    "*Issue cross-reference*",
    "P1",
    "high",
    "Convert to #reference in body",
    "GitHub's #123 syntax creates automatic cross-reference.",
  ),
  f(
    "E01",
    19,
    "Predecessor/Successor",
    "work item ref",
    "*No direct equivalent*",
    "P5",
    "gap",
    "Rebuild via Projects dependencies field",
    "GitHub Projects supports dependency relationships between items.",
  ),
  f(
    "E01",
    20,
    "Attached File",
    "binary blob",
    "*Issue attachments*",
    "P1",
    "high",
    "Re-upload via API",
    "Migration tool must re-upload each file; URLs change.",
  ),
  f(
    "E01",
    21,
    "Hyperlink",
    "URL + description",
    "*In Issue body as markdown link*",
    "P2",
    "medium",
    "Append as markdown link in body",
    "No dedicated field on GitHub side; becomes prose.",
  ),
  f(
    "E01",
    22,
    "Tested By (link)",
    "test case ref",
    "*No direct equivalent*",
    "P6",
    "gap",
    "Lost unless Test Plans stays in hybrid",
    "Test-case-to-work-item linkage is hybrid-protected.",
  ),
  f(
    "E01",
    23,
    "Story Points (Agile)",
    "decimal",
    "*Label* `points:5` or *Projects custom field*",
    "P3",
    "medium",
    "Compose: number field in Projects + label for visibility",
    "GitHub Projects supports custom fields since 2023.",
  ),
  f(
    "E01",
    24,
    "Effort (Scrum)",
    "integer",
    "*Projects custom field*",
    "P3",
    "medium",
    "Number field in Projects",
    "Same pattern as Story Points; template-specific naming.",
  ),
  f(
    "E01",
    25,
    "Original Estimate (CMMI)",
    "decimal hours",
    "*Projects custom field*",
    "P3",
    "medium",
    "Number field in Projects",
    "Hours tracking rarely migrates cleanly. Consider retiring.",
  ),
  f(
    "E01",
    26,
    "Remaining Work (CMMI)",
    "decimal hours",
    "*Projects custom field*",
    "P3",
    "medium",
    "Number field in Projects",
    "Dynamic value; usually recalculated rather than migrated.",
  ),
  f(
    "E01",
    27,
    "Completed Work (CMMI)",
    "decimal hours",
    "*Projects custom field*",
    "P3",
    "medium",
    "Number field in Projects",
    "Historical value; migration preserves point-in-time snapshot.",
  ),
  f(
    "E01",
    28,
    "Activity (Scrum)",
    "enum",
    "*Label*",
    "P2",
    "medium",
    "Enum → label values",
    "Dev/Design/Testing/Documentation/Requirements → flatten to labels.",
  ),
  f(
    "E01",
    29,
    "Discipline (CMMI)",
    "enum",
    "*Label*",
    "P2",
    "medium",
    "Enum → label values",
    "Similar to Activity; template-specific naming.",
  ),
  f(
    "E01",
    30,
    "Risk (CMMI)",
    "enum",
    "*Label*",
    "P2",
    "medium",
    "Enum → label values",
    "High/Medium/Low → labels.",
  ),
  f(
    "E01",
    31,
    "Value Area (SAFe/Agile)",
    "enum",
    "*Label*",
    "P2",
    "medium",
    "Enum → label values",
    "Business/Architectural categorization.",
  ),
  f(
    "E01",
    32,
    "Business Value (Agile)",
    "integer",
    "*Projects custom field*",
    "P3",
    "medium",
    "Number field in Projects",
    "WSJF inputs often needed together.",
  ),
  f(
    "E01",
    33,
    "Time Criticality (SAFe)",
    "integer",
    "*Projects custom field*",
    "P3",
    "medium",
    "Number field in Projects",
    "One WSJF component.",
  ),
  f(
    "E01",
    34,
    "WSJF (SAFe)",
    "computed decimal",
    "*Projects custom field* or *computed*",
    "P3",
    "low",
    "Recompute from migrated components",
    "Computed field; re-derive after migration if components available.",
  ),
  f(
    "E01",
    35,
    "Acceptance Criteria (Agile)",
    "rich text",
    "*Issue body section*",
    "P2",
    "medium",
    "Append to Issue body with heading",
    "Lose the distinct field; embed in description.",
  ),
  f(
    "E01",
    36,
    "Repro Steps (Bug)",
    "rich text",
    "*Issue body section*",
    "P2",
    "medium",
    "Append to Issue body with heading",
    "Same pattern as Acceptance Criteria.",
  ),
  f(
    "E01",
    37,
    "Found In (Build)",
    "string or build ref",
    "*Label* or *body text*",
    "P2",
    "low",
    "Label for current release, text for older",
    "Build references break; label or prose is the pragmatic target.",
  ),
  f(
    "E01",
    38,
    "Integrated In (Build)",
    "string or build ref",
    "*Label* or *body text*",
    "P2",
    "low",
    "Label for current release, text for older",
    "Same treatment as Found In.",
  ),

  // ============ E14 Pull Request (16 fields) ============
  f(
    "E14",
    1,
    "Title",
    "string",
    "*PR.title*",
    "P1",
    "high",
    "1:1 direct copy",
    "GEI handles this.",
  ),
  f(
    "E14",
    2,
    "Description",
    "markdown",
    "*PR.body*",
    "P1",
    "high",
    "1:1 direct copy",
    "ADO markdown is GitHub-compatible for most cases.",
  ),
  f(
    "E14",
    3,
    "Source Branch",
    "git ref",
    "*PR.head.ref*",
    "P1",
    "high",
    "1:1 direct copy",
    "Branch names preserved.",
  ),
  f(
    "E14",
    4,
    "Target Branch",
    "git ref",
    "*PR.base.ref*",
    "P1",
    "high",
    "1:1 direct copy",
    "Branch names preserved.",
  ),
  f(
    "E14",
    5,
    "Status",
    "enum",
    "*PR.state* + *PR.merged*",
    "P4",
    "high",
    "Decompose: Active→open, Completed→closed+merged, Abandoned→closed",
    "Similar shape to Work Item.State decomposition.",
  ),
  f(
    "E14",
    6,
    "Reviewers (optional)",
    "identity list",
    "*PR.requested_reviewers*",
    "P1",
    "high",
    "Identity mapping",
    "Direct mapping through mannequin reclamation.",
  ),
  f(
    "E14",
    7,
    "Required Reviewers",
    "identity list",
    "*Branch protection rule* + *review request*",
    "P3",
    "medium",
    "Move enforcement to branch protection, not PR-level",
    "ADO enforces at PR; GitHub enforces at branch. Semantic shift.",
  ),
  f(
    "E14",
    8,
    "Work Item Links",
    "work item refs",
    "*PR body keyword links* (`Fixes #123`)",
    "P2",
    "high",
    "Convert to markdown reference syntax",
    "GEI handles this automatically.",
  ),
  f(
    "E14",
    9,
    "Commits",
    "commit list",
    "*PR.commits*",
    "P1",
    "high",
    "Git-native",
    "Nothing to migrate separately; lives in the repo.",
  ),
  f(
    "E14",
    10,
    "Iterations (PR update history)",
    "iteration list",
    "*Force-push events*",
    "P2",
    "medium",
    "Implicit in force-push history",
    "GitHub doesn't have explicit 'iteration' concept; force-pushes are equivalent.",
  ),
  f(
    "E14",
    11,
    "Threads (code comments)",
    "position-pinned discussion",
    "*PR.review_comments*",
    "P1",
    "high",
    "1:1 direct copy",
    "GEI preserves these.",
  ),
  f(
    "E14",
    12,
    "General Comments",
    "discussion",
    "*PR.comments*",
    "P1",
    "high",
    "1:1 direct copy",
    "GEI preserves these.",
  ),
  f(
    "E14",
    13,
    "Policies Applied",
    "policy config snapshot",
    "*Branch protection rule*",
    "P3",
    "medium",
    "Translate policy rules to branch protection",
    "Per-repo branch policies migrate; user-scoped and cross-repo don't.",
  ),
  f(
    "E14",
    14,
    "Auto-Complete",
    "boolean + conditions",
    "*Auto-merge*",
    "P2",
    "medium",
    "Enable auto-merge if conditions met",
    "Feature parity close but config syntax differs.",
  ),
  f(
    "E14",
    15,
    "Merge Strategy",
    "enum (merge/squash/rebase)",
    "*Merge method (repo setting)*",
    "P2",
    "medium",
    "Repo-level default",
    "GitHub sets at repo level; ADO sets per-PR.",
  ),
  f(
    "E14",
    16,
    "Created/Closed By + Date",
    "identity + datetime",
    "*PR.user, PR.created_at, PR.closed_at*",
    "P1",
    "high",
    "1:1 direct copy",
    "Standard metadata.",
  ),

  // ============ E15 Repository (15 fields) ============
  f(
    "E15",
    1,
    "Name",
    "string",
    "*Repo.name*",
    "P1",
    "high",
    "1:1 (may need renaming for conflicts)",
    "Naming collisions common at scale; plan a scheme.",
  ),
  f(
    "E15",
    2,
    "Default Branch",
    "git ref",
    "*Repo.default_branch*",
    "P1",
    "high",
    "1:1 direct copy",
    "Often renamed from master→main during migration.",
  ),
  f(
    "E15",
    3,
    "Branches",
    "git refs",
    "*Repo branches*",
    "P1",
    "high",
    "Git-native",
    "Full branch graph migrates.",
  ),
  f(
    "E15",
    4,
    "Tags",
    "git refs",
    "*Repo tags*",
    "P1",
    "high",
    "Git-native",
    "Full tag list migrates.",
  ),
  f(
    "E15",
    5,
    "Size",
    "bytes",
    "*Repo.size*",
    "P1",
    "high",
    "Implicit post-migration",
    "Recalculated on GitHub side.",
  ),
  f(
    "E15",
    6,
    "Is Disabled",
    "boolean",
    "*Repo.archived*",
    "P1",
    "high",
    "Archive on GitHub",
    "Semantics close but not identical; archived allows read-only access.",
  ),
  f(
    "E15",
    7,
    "Is Fork",
    "boolean",
    "*Repo.fork*",
    "P1",
    "high",
    "1:1 direct copy",
    "Fork relationship needs both source and target in scope.",
  ),
  f(
    "E15",
    8,
    "Parent (for forks)",
    "repo ref",
    "*Repo.parent*",
    "P2",
    "medium",
    "Requires parent already migrated",
    "Migration ordering matters.",
  ),
  f(
    "E15",
    9,
    "Branch Policies (per branch)",
    "policy object",
    "*Branch protection rule*",
    "P2",
    "medium",
    "Translate policy → protection",
    "Most policies map cleanly; path-scoped do not.",
  ),
  f(
    "E15",
    10,
    "Path-Scoped Branch Policies",
    "policy object with path filter",
    "*CODEOWNERS* + *Required reviews*",
    "P3",
    "low",
    "Compose: path ownership via CODEOWNERS, reviews via protection",
    "Common source of migration friction.",
  ),
  f(
    "E15",
    11,
    "Webhooks",
    "URL + events",
    "*Repo webhooks*",
    "P1",
    "high",
    "1:1 (re-authenticate)",
    "Secrets must be re-provided at destination.",
  ),
  f(
    "E15",
    12,
    "Service Hooks",
    "named integrations",
    "*Marketplace apps* / *webhook*",
    "P2",
    "medium",
    "Re-establish via GitHub App or webhook",
    "Per-service; see Third-Party Integrations page.",
  ),
  f(
    "E15",
    13,
    "Repo-Level Permissions",
    "ACL list",
    "*Repo collaborators* + *Team access*",
    "P4",
    "medium",
    "Decompose: individual → collaborators; group → team access",
    "Identity mapping required; see Identity page.",
  ),
  f(
    "E15",
    14,
    "Security Advisories",
    "advisory records",
    "*Repo security advisories*",
    "P2",
    "medium",
    "Recreate via API if needed",
    "Rarely migrated; usually start fresh.",
  ),
  f(
    "E15",
    15,
    "Imported (from elsewhere)",
    "boolean",
    "*N/A*",
    "P6",
    "na",
    "Not preserved",
    "Metadata-only.",
  ),

  // ============ E21 Pipeline / Build Definition (21 fields) ============
  f(
    "E21",
    1,
    "Name",
    "string",
    "*Workflow file name*",
    "P1",
    "high",
    "1:1",
    "Stored as .yml filename.",
  ),
  f(
    "E21",
    2,
    "Path",
    "string",
    "`.github/workflows/*.yml`",
    "P1",
    "high",
    "1:1",
    "GitHub Actions convention.",
  ),
  f(
    "E21",
    3,
    "Folder (logical grouping)",
    "string",
    "*Filename convention*",
    "P2",
    "low",
    "Encode in workflow name prefix",
    "GitHub has no folder concept; convention-based.",
  ),
  f(
    "E21",
    4,
    "YAML Definition",
    "yaml",
    "*Workflow yaml*",
    "P2",
    "medium",
    "Syntax conversion via Actions Importer",
    "~80% automated; 20% manual cleanup per GitHub docs.",
  ),
  f(
    "E21",
    5,
    "Variables (pipeline-scoped)",
    "key-value pairs",
    "*env* + *Repository variables*",
    "P2",
    "high",
    "Repository-scoped env vars",
    "Standard mapping; plaintext vars only.",
  ),
  f(
    "E21",
    6,
    "Variable Groups",
    "shared variable set",
    "*Environment variables* + *Org variables*",
    "P3",
    "medium",
    "Compose: env for dev/stage/prod; org vars for cross-repo",
    "Shared variable group concept doesn't exist; composed via scoping.",
  ),
  f(
    "E21",
    7,
    "Secrets",
    "encrypted values",
    "*Repository secrets* + *Environment secrets*",
    "P2",
    "medium",
    "Re-provide via API or UI",
    "Secrets cannot be extracted; must be re-entered.",
  ),
  f(
    "E21",
    8,
    "CI Triggers",
    "branch/path filters",
    "*on.push* + filters",
    "P1",
    "high",
    "YAML conversion",
    "Standard translation.",
  ),
  f(
    "E21",
    9,
    "PR Triggers",
    "branch filters",
    "*on.pull_request*",
    "P1",
    "high",
    "YAML conversion",
    "Standard translation.",
  ),
  f(
    "E21",
    10,
    "Scheduled Triggers",
    "cron",
    "*on.schedule.cron*",
    "P1",
    "high",
    "YAML conversion",
    "Cron syntax identical.",
  ),
  f(
    "E21",
    11,
    "Build Validation Policies (PR)",
    "PR-level required check",
    "*Branch protection required checks*",
    "P3",
    "medium",
    "Compose: action workflow + branch protection",
    "Enforcement location shifts.",
  ),
  f(
    "E21",
    12,
    "Agent Pool",
    "pool name + demands",
    "*runs-on* + *labels*",
    "P2",
    "medium",
    "GitHub-hosted or self-hosted with labels",
    "Agent pool concept doesn't map directly; runners + labels do.",
  ),
  f(
    "E21",
    13,
    "Demands",
    "capability requirements",
    "*Self-hosted runner labels*",
    "P2",
    "medium",
    "Self-hosted runner labels",
    "Fine-grained demands require labeled runners.",
  ),
  f(
    "E21",
    14,
    "Service Connections",
    "external system auth",
    "*OIDC* + *Secrets* + *Marketplace apps*",
    "P4",
    "low",
    "Decompose: auth → OIDC; creds → secrets",
    "Often the hardest pipeline migration step.",
  ),
  f(
    "E21",
    15,
    "Approvals (deployment)",
    "approver list + conditions",
    "*Environment required reviewers*",
    "P2",
    "medium",
    "Environment protection rules",
    "Concept exists; config is different.",
  ),
  f(
    "E21",
    16,
    "Gates (pre/post deployment)",
    "check function list",
    "*Deployment checks* + *Workflow steps*",
    "P3",
    "medium",
    "Compose: deployment checks + custom step logic",
    "Gates are often custom-built on GitHub.",
  ),
  f(
    "E21",
    17,
    "Environments",
    "deployment targets",
    "*Deployment environments*",
    "P1",
    "high",
    "1:1 conceptual",
    "Feature exists on GitHub; config differs.",
  ),
  f(
    "E21",
    18,
    "Stages",
    "parallel/sequential containers",
    "*Jobs with needs*",
    "P2",
    "high",
    "Translate to needs-based job graph",
    "Actions Importer handles this.",
  ),
  f(
    "E21",
    19,
    "Jobs",
    "step containers",
    "*Jobs*",
    "P1",
    "high",
    "1:1",
    "Direct concept.",
  ),
  f(
    "E21",
    20,
    "Steps",
    "atomic tasks",
    "*Steps*",
    "P1",
    "high",
    "1:1 or task→action translation",
    "Common ADO tasks → Marketplace actions mapping.",
  ),
  f(
    "E21",
    21,
    "Retention Policies",
    "keep-days config",
    "*Repo retention settings*",
    "P2",
    "medium",
    "Repo or org-level retention",
    "Less granular on GitHub side.",
  ),

  // ============ E22 Release Definition (14 fields) ============
  f(
    "E22",
    1,
    "Stages",
    "sequential stages",
    "*Actions jobs with needs*",
    "P3",
    "medium",
    "Rebuild as workflow dependency graph",
    "Classic UI-based releases often have complex stage logic.",
  ),
  f(
    "E22",
    2,
    "Environments",
    "deployment targets",
    "*Actions Environments*",
    "P1",
    "high",
    "1:1 conceptual",
    "Same concept.",
  ),
  f(
    "E22",
    3,
    "Pre-Deployment Approvals",
    "approver list",
    "*Environment required reviewers (pre)*",
    "P2",
    "medium",
    "Environment protection rules",
    "Reviewers list maps directly.",
  ),
  f(
    "E22",
    4,
    "Post-Deployment Approvals",
    "approver list",
    "*Manual post-check workflow*",
    "P3",
    "low",
    "Compose: manual trigger after deploy",
    "GitHub lacks built-in post-deploy gate; requires workflow design.",
  ),
  f(
    "E22",
    5,
    "Artifacts (input)",
    "build output linkage",
    "*Actions artifacts* or *Packages*",
    "P2",
    "medium",
    "Artifact download action or package pull",
    "Workflow artifacts or releases serve similar role.",
  ),
  f(
    "E22",
    6,
    "Deployment Conditions",
    "condition rules",
    "*if: expressions* on jobs",
    "P2",
    "medium",
    "Translate to workflow conditionals",
    "Syntax conversion needed.",
  ),
  f(
    "E22",
    7,
    "Deployment Queue Settings",
    "concurrency rules",
    "*concurrency.group*",
    "P1",
    "high",
    "1:1 concept",
    "Actions has concurrency control.",
  ),
  f(
    "E22",
    8,
    "Variables (release-scoped)",
    "key-value",
    "*Environment variables*",
    "P1",
    "high",
    "Per-environment vars",
    "Standard mapping.",
  ),
  f(
    "E22",
    9,
    "Tasks (within stages)",
    "task list",
    "*Steps within jobs*",
    "P1",
    "high",
    "1:1 translation",
    "Via Actions Importer.",
  ),
  f(
    "E22",
    10,
    "Retention",
    "retention policy",
    "*Repo retention settings*",
    "P2",
    "medium",
    "Repo-level config",
    "Less granular on GitHub.",
  ),
  f(
    "E22",
    11,
    "Trigger (CD)",
    "artifact availability",
    "*workflow_run* trigger or *on.release*",
    "P2",
    "medium",
    "Workflow-run or release event",
    "Event-based trigger.",
  ),
  f(
    "E22",
    12,
    "Auto-redeploy on failure",
    "boolean",
    "*Manual re-run*",
    "P5",
    "low",
    "Re-architect: retry action or manual re-run",
    "No built-in auto-redeploy; design a retry step.",
  ),
  f(
    "E22",
    13,
    "Pipeline-to-release linkage",
    "ID references",
    "*workflow_run* event",
    "P2",
    "medium",
    "Event-based workflow chaining",
    "Chained workflows pattern.",
  ),
  f(
    "E22",
    14,
    "Release-level permissions",
    "ACL",
    "*Environment access rules*",
    "P2",
    "medium",
    "Environment protection",
    "Permissions live on environment.",
  ),

  // ============ E49 User / Identity (13 fields) ============
  f(
    "E49",
    1,
    "DisplayName",
    "string",
    "*User.name*",
    "P1",
    "high",
    "Entra ID sync",
    "Via EMU.",
  ),
  f(
    "E49",
    2,
    "UniqueName (UPN)",
    "email-format string",
    "*User.email* via SCIM",
    "P1",
    "high",
    "SCIM provisioning",
    "Primary identity key.",
  ),
  f(
    "E49",
    3,
    "Mail",
    "email",
    "*User.email*",
    "P1",
    "high",
    "1:1 via SCIM",
    "Same source of truth (Entra).",
  ),
  f(
    "E49",
    4,
    "Directory Alias",
    "string",
    "*User.login*",
    "P2",
    "medium",
    "Configurable via EMU policy",
    "GitHub login often has org prefix in EMU.",
  ),
  f(
    "E49",
    5,
    "Entra ID Object ID",
    "GUID",
    "*SCIM externalId*",
    "P1",
    "high",
    "SCIM attribute",
    "The canonical join key.",
  ),
  f(
    "E49",
    6,
    "Member Of (groups)",
    "group refs",
    "*Team membership*",
    "P2",
    "medium",
    "Re-map groups → teams",
    "Group-to-team mapping requires design.",
  ),
  f(
    "E49",
    7,
    "Licenses (Basic/Stakeholder/VS)",
    "enum",
    "*Seat type* (Member/Outside collaborator)",
    "P4",
    "medium",
    "Decompose: Basic→Member; Stakeholder→varies",
    "ADO Stakeholder has no direct GitHub equivalent.",
  ),
  f(
    "E49",
    8,
    "Access Level",
    "enum",
    "*Role*",
    "P2",
    "medium",
    "Role-based mapping",
    "Admin/Member/Outside collaborator.",
  ),
  f(
    "E49",
    9,
    "Last Access Date",
    "datetime",
    "*User last activity*",
    "P2",
    "medium",
    "Audit log-derived",
    "Preserved as metadata only; no user-facing field.",
  ),
  f(
    "E49",
    10,
    "Is Active",
    "boolean",
    "*User.suspended* (inverse)",
    "P1",
    "high",
    "1:1 inverse mapping",
    "Inactive ADO users → suspended on GitHub.",
  ),
  f(
    "E49",
    11,
    "Descriptor",
    "composite identity ref",
    "*N/A (internal)*",
    "P6",
    "na",
    "Not preserved",
    "ADO-internal concept.",
  ),
  f(
    "E49",
    12,
    "Origin",
    "enum (aad/vsts/msa)",
    "*N/A (EMU vs standard)*",
    "P4",
    "medium",
    "Design EMU vs standard decision",
    "Implicit in enterprise model choice.",
  ),
  f(
    "E49",
    13,
    "OriginId",
    "external ref",
    "*SCIM externalId*",
    "P1",
    "high",
    "SCIM attribute",
    "Similar to Entra Object ID.",
  ),

  // ============ E50 Team (10 fields) ============
  f(
    "E50",
    1,
    "Name",
    "string",
    "*Team.name*",
    "P1",
    "high",
    "1:1",
    "Direct mapping.",
  ),
  f(
    "E50",
    2,
    "Description",
    "string",
    "*Team.description*",
    "P1",
    "high",
    "1:1",
    "Direct mapping.",
  ),
  f(
    "E50",
    3,
    "Members",
    "identity list",
    "*Team.members*",
    "P1",
    "high",
    "Via Entra sync",
    "Via SCIM.",
  ),
  f(
    "E50",
    4,
    "Administrators",
    "identity list",
    "*Team.maintainers*",
    "P2",
    "medium",
    "Role-based mapping",
    "Admin role maps to maintainer role.",
  ),
  f(
    "E50",
    5,
    "Area Paths Owned",
    "area path list",
    "*No direct equivalent*",
    "P3",
    "low",
    "Compose: labels + CODEOWNERS + project filters",
    "See AreaPath on Work Item. Ownership reconstructed.",
  ),
  f(
    "E50",
    6,
    "Iteration Paths Owned",
    "iteration list",
    "*Project iterations*",
    "P3",
    "low",
    "Projects + milestones",
    "Sprint ownership at team level.",
  ),
  f(
    "E50",
    7,
    "Team Settings (backlog/board)",
    "config",
    "*Project view/filter config*",
    "P3",
    "medium",
    "Rebuild as Projects views",
    "Projects v2 has rich view config.",
  ),
  f(
    "E50",
    8,
    "Dashboards",
    "widget layout",
    "*No direct equivalent*",
    "P5",
    "gap",
    "Rebuild via Projects insights or external BI",
    "ADO has dedicated dashboards feature; GitHub does not.",
  ),
  f(
    "E50",
    9,
    "Boards Configuration",
    "kanban config",
    "*Project board config*",
    "P2",
    "medium",
    "Projects v2 board view",
    "Rough parity; some customizations lost.",
  ),
  f(
    "E50",
    10,
    "Capacity",
    "hours-per-iteration",
    "*No direct equivalent*",
    "P5",
    "gap",
    "External tool or retire capability",
    "Sprint capacity planning often abandoned post-migration.",
  ),

  // ============ E51 Organization / Project (15 fields) ============
  f(
    "E51",
    1,
    "Organization Name",
    "string",
    "*Enterprise / Organization.login*",
    "P1",
    "high",
    "1:1",
    "Top-level GitHub container.",
  ),
  f(
    "E51",
    2,
    "Project Name",
    "string",
    "*Repo prefix* or *Sub-org*",
    "P4",
    "medium",
    "Decompose: naming convention or sub-organization",
    "ADO Projects have no GitHub equivalent; topology decision.",
  ),
  f(
    "E51",
    3,
    "Project Description",
    "string",
    "*Repo description* or *Org readme*",
    "P2",
    "medium",
    "Per-repo or org-level",
    "Distributed across repos.",
  ),
  f(
    "E51",
    4,
    "Project State",
    "enum",
    "*Repo archived flag*",
    "P2",
    "medium",
    "Per-repo archive state",
    "Granularity shifts.",
  ),
  f(
    "E51",
    5,
    "Project Visibility",
    "enum (private/public)",
    "*Repo visibility*",
    "P2",
    "medium",
    "Per-repo setting",
    "Also distributed.",
  ),
  f(
    "E51",
    6,
    "Process Template (Agile/Scrum/CMMI)",
    "template name",
    "*Issue types* + *labels* + *templates*",
    "P4",
    "low",
    "Decompose: template → Issue templates + labels + Projects fields",
    "Process template concept doesn't exist; simulate via GitHub features.",
  ),
  f(
    "E51",
    7,
    "Source Control Type",
    "enum (Git/TFVC)",
    "*Always git*",
    "P6",
    "na",
    "TFVC requires conversion first",
    "TFVC-only repos must convert before migration.",
  ),
  f(
    "E51",
    8,
    "Capabilities (enabled services)",
    "service list",
    "*Features enabled on repo*",
    "P2",
    "medium",
    "Per-repo feature toggles",
    "Issues, wiki, projects, pages.",
  ),
  f(
    "E51",
    9,
    "Properties (metadata)",
    "key-value",
    "*Repo topics*",
    "P2",
    "low",
    "Metadata → topics",
    "Lossy; topics are flat strings.",
  ),
  f(
    "E51",
    10,
    "Project Administrators",
    "identity list",
    "*Org owners* or *team maintainers*",
    "P2",
    "medium",
    "Role mapping",
    "Depends on org topology decision.",
  ),
  f(
    "E51",
    11,
    "Security Groups",
    "identity list",
    "*Teams*",
    "P2",
    "medium",
    "Group → team mapping",
    "See Team fields.",
  ),
  f(
    "E51",
    12,
    "Project-Scoped Policies",
    "policy set",
    "*Org-level branch protection rulesets*",
    "P3",
    "medium",
    "Rulesets for cross-repo policies",
    "Rulesets (2023+) enable org-wide policy.",
  ),
  f(
    "E51",
    13,
    "Billing info",
    "billing record",
    "*Enterprise billing*",
    "P4",
    "medium",
    "Enterprise-level billing",
    "Billing unit changes.",
  ),
  f(
    "E51",
    14,
    "Process customizations",
    "custom work-item-type definitions",
    "*Issue types + Projects custom fields*",
    "P4",
    "low",
    "Rebuild as Issue types + custom fields",
    "Issue types (2024+) partially close this gap.",
  ),
  f(
    "E51",
    15,
    "Extensions installed",
    "extension list",
    "*Marketplace apps*",
    "P5",
    "low",
    "Re-install per-extension basis",
    "See Third-Party Integrations page.",
  ),

  // ============ E52 Wiki (8 fields) ============
  f(
    "E52",
    1,
    "Name",
    "string",
    "*Wiki name* (via filename)",
    "P1",
    "high",
    "Convention",
    "GitHub wiki is a repo.",
  ),
  f(
    "E52",
    2,
    "Type (Project vs Code)",
    "enum",
    "*GitHub Wiki* or *docs repo*",
    "P2",
    "medium",
    "Choose target per type",
    "Project wikis → GitHub Wiki; Code wikis → docs repo.",
  ),
  f(
    "E52",
    3,
    "Version (branch for code wiki)",
    "git ref",
    "*Branch*",
    "P1",
    "high",
    "Git-native for code wikis",
    "Project wikis don't version.",
  ),
  f(
    "E52",
    4,
    "Pages (markdown)",
    "markdown content",
    "*Wiki pages*",
    "P2",
    "medium",
    "Markdown conversion",
    "ADO wiki markdown has extensions (mermaid, mathjax) that may need adaptation.",
  ),
  f(
    "E52",
    5,
    "Page Hierarchy",
    "tree structure",
    "*Flat with naming convention*",
    "P2",
    "low",
    "Flatten; encode hierarchy in filenames",
    "GitHub wiki is flat.",
  ),
  f(
    "E52",
    6,
    "Attachments",
    "binary blobs",
    "*Git LFS* or *repo files*",
    "P2",
    "medium",
    "Commit to wiki repo or docs repo",
    "Storage shifts; URLs change.",
  ),
  f(
    "E52",
    7,
    "Permissions",
    "ACL",
    "*Repo collaborators*",
    "P2",
    "medium",
    "Repo-level permissions",
    "Granular wiki permissions lost.",
  ),
  f(
    "E52",
    8,
    "Embedded work-item references",
    "ADO-specific links",
    "*GitHub issue links*",
    "P4",
    "low",
    "Rewrite URLs",
    "Breaks silently; requires link audit.",
  ),

  // ============ E35 Test Case / Test Plan (20 fields) ============
  f(
    "E35",
    1,
    "Test Plan",
    "container object",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Explicit hybrid-protected entity.",
  ),
  f(
    "E35",
    2,
    "Test Suite (hierarchical)",
    "test container",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Same.",
  ),
  f(
    "E35",
    3,
    "Test Case",
    "test definition",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Same.",
  ),
  f(
    "E35",
    4,
    "Test Steps",
    "step list",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Same.",
  ),
  f(
    "E35",
    5,
    "Expected Result (per step)",
    "rich text",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Same.",
  ),
  f(
    "E35",
    6,
    "Parameters",
    "parameter definition",
    "*Actions matrix strategy*",
    "P5",
    "gap",
    "Rebuild via matrix strategy for automated tests",
    "P5 substitution: different mechanism preserves parameterized-testing capability for automated tests only.",
  ),
  f(
    "E35",
    7,
    "Shared Steps",
    "reusable step set",
    "*No equivalent (for manual)*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Manual-test reusability concept.",
  ),
  f(
    "E35",
    8,
    "Shared Parameters",
    "reusable parameter set",
    "*Workflow-level env or reusable workflows*",
    "P5",
    "low",
    "Reusable workflows for automated",
    "Automated only.",
  ),
  f(
    "E35",
    9,
    "Configurations",
    "browser/OS matrix",
    "*Actions matrix strategy*",
    "P5",
    "medium",
    "Matrix strategy in workflow",
    "Automated test matrix.",
  ),
  f(
    "E35",
    10,
    "Test Runs",
    "execution record",
    "*Checks API runs*",
    "P5",
    "low",
    "Check runs for automated",
    "Manual test runs have no target.",
  ),
  f(
    "E35",
    11,
    "Test Results",
    "pass/fail/block record",
    "*Check run conclusion*",
    "P5",
    "low",
    "Check conclusion for automated",
    "Automated only.",
  ),
  f(
    "E35",
    12,
    "Test Points",
    "instance of case in config",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "ADO-specific concept.",
  ),
  f(
    "E35",
    13,
    "Requirement Links",
    "work item refs",
    "*Issue cross-reference*",
    "P2",
    "medium",
    "If work items migrated, #refs",
    "Only works if target exists.",
  ),
  f(
    "E35",
    14,
    "Automation Status",
    "enum",
    "*Workflow presence*",
    "P2",
    "low",
    "Implicit via workflow existence",
    "Loose association.",
  ),
  f(
    "E35",
    15,
    "Automated Test Reference",
    "method-to-test-case link",
    "*Test file path in repo*",
    "P2",
    "medium",
    "Convention-based linkage",
    "Doc-based link only.",
  ),
  f(
    "E35",
    16,
    "Exploratory Session Recording",
    "session log",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Classic exploratory-testing UX.",
  ),
  f(
    "E35",
    17,
    "Bug-from-test linkage",
    "automatic work-item creation",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Manual-test to bug workflow.",
  ),
  f(
    "E35",
    18,
    "Test charts & reports",
    "dashboard widgets",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "ADO dashboards.",
  ),
  f(
    "E35",
    19,
    "Test case traceability",
    "matrix views",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Regulated-industry requirement.",
  ),
  f(
    "E35",
    20,
    "Test case acceptance/approval",
    "approval workflow",
    "*No equivalent*",
    "P6",
    "gap",
    "Stay in ADO Test Plans",
    "Same.",
  ),

  // ============ E44 Artifact / Package (11 fields) ============
  f(
    "E44",
    1,
    "Feed (container)",
    "named container",
    "*Package namespace*",
    "P2",
    "medium",
    "Org or user scope",
    "GitHub Packages flatter than ADO Feeds.",
  ),
  f(
    "E44",
    2,
    "Package Name",
    "string",
    "*Package.name*",
    "P1",
    "high",
    "1:1",
    "Standard.",
  ),
  f(
    "E44",
    3,
    "Version",
    "semver or custom",
    "*Package version*",
    "P1",
    "high",
    "1:1",
    "Standard.",
  ),
  f(
    "E44",
    4,
    "Package Type: nuget",
    "enum",
    "*GitHub Packages nuget*",
    "P1",
    "high",
    "1:1",
    "Supported.",
  ),
  f(
    "E44",
    5,
    "Package Type: npm",
    "enum",
    "*GitHub Packages npm*",
    "P1",
    "high",
    "1:1",
    "Supported.",
  ),
  f(
    "E44",
    6,
    "Package Type: maven",
    "enum",
    "*GitHub Packages maven*",
    "P1",
    "high",
    "1:1",
    "Supported.",
  ),
  f(
    "E44",
    7,
    "Package Type: Python",
    "enum",
    "*NOT supported*",
    "P6",
    "gap",
    "External registry (PyPI, Artifactory)",
    "GitHub Packages does not support Python.",
  ),
  f(
    "E44",
    8,
    "Package Type: Universal",
    "ADO-proprietary",
    "*NOT supported*",
    "P6",
    "gap",
    "Stay in ADO Artifacts or rebuild",
    "No generic binary package type on GitHub.",
  ),
  f(
    "E44",
    9,
    "Package Type: Cargo",
    "enum",
    "*NOT supported*",
    "P6",
    "gap",
    "External registry (crates.io or private)",
    "Not in GitHub Packages.",
  ),
  f(
    "E44",
    10,
    "Upstream Sources",
    "feed chain config",
    "*No equivalent*",
    "P5",
    "gap",
    "Rebuild via explicit dependency resolution",
    "Proxying upstream is ADO-specific.",
  ),
  f(
    "E44",
    11,
    "Retention Policies",
    "keep-N config",
    "*Package versions settings*",
    "P2",
    "medium",
    "Per-package retention",
    "Less granular.",
  ),
];

export const FIELDS_BY_ENTITY: Record<string, Field[]> = (() => {
  const out: Record<string, Field[]> = {};
  for (const fld of FIELDS) {
    if (!out[fld.entityId]) out[fld.entityId] = [];
    out[fld.entityId]!.push(fld);
  }
  return out;
})();
