import { jtbdOverridesFor } from "./jtbd-scoping";

import {
  adoProject,
  anomaly,
  customization,
  daysAgo,
  daysFromNow,
  extension,
  hoursAgo,
  allJtbds,
  member,
  needsInput,
  releaseDefinition,
  repo,
  serviceConnection,
  workflow,
  type CohortShape,
} from "./_helpers";

export function bravoConfig(orgId: string): CohortShape {
  return {
    orgId,
    name: "Bravo Services",
    slug: "bravo",
    tagline: "The typical healthy team",
    description:
      "Eight repos, a YAML-first pipeline stack with two classic release definitions, normal-cadence JTBDs, a couple of extensions without direct GitHub equivalents. A few review items but no blockers.",
    cohort: "BRAVO",
    wave: 1,
    migrationState: "DISCOVERING",
    engineerCount: 6,
    tier: "TIER_2",
    securityClassification: null,
    healthStatus: "ON_TRACK",
    effortEstimateLowWeeks: 8,
    effortEstimateHighWeeks: 12,
    effortConfidence: "MEDIUM",
    effortProgressWeeks: 2.5,
    targetCutoverAt: daysFromNow(70),
    slackWeeks: 1,
    workItemsActive: 58,
    workItemsClosed90d: 184,
    buildArtifactCount: 142,
    wikiPageCount: 34,
    championEmail: "jordan.kim@contoso.com",
    members: [
      member("Jordan Kim", "jordan.kim@contoso.com", "Staff Engineer"),
      member("Priya Patel", "priya.patel@contoso.com", "Senior Engineer"),
      member("Devon Wilson", "devon.wilson@contoso.com", "Engineer"),
      member("Noor Hassan", "noor.hassan@contoso.com", "Senior SRE"),
      member("Theo Brandt", "theo.brandt@contoso.com", "Engineer"),
      member("Mei Lin", "mei.lin@contoso.com", "Engineering Manager"),
    ],
    codebase: {
      primaryLang: "Python",
      usesLfs: false,
      totalSizeGb: 8.4,
    },
    repos: [
      repo("bravo-api", {
        sizeGb: 2.1,
        loc: 78000,
        languageBreakdown: {
          Python: 72,
          YAML: 12,
          Dockerfile: 6,
          Markdown: 10,
        },
        contributorCount: 6,
        hasWiki: true,
        wikiPageCount: 18,
        commits90d: 412,
        primaryOwner: "jordan.kim@contoso.com",
        lastCommitAt: hoursAgo(9),
      }),
      repo("bravo-web", {
        sizeGb: 1.8,
        loc: 54200,
        languageBreakdown: {
          TypeScript: 68,
          CSS: 12,
          HTML: 8,
          YAML: 6,
          Markdown: 6,
        },
        contributorCount: 5,
        hasWiki: true,
        wikiPageCount: 9,
        commits90d: 328,
        primaryOwner: "priya.patel@contoso.com",
        lastCommitAt: daysAgo(1),
      }),
      repo("bravo-sdk", {
        sizeGb: 1.5,
        loc: 68000,
        languageBreakdown: { Python: 84, YAML: 8, Markdown: 8 },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 24,
        commits90d: 142,
        primaryOwner: "devon.wilson@contoso.com",
        lastCommitAt: daysAgo(3),
      }),
      repo("bravo-docs", {
        sizeGb: 0.3,
        loc: 9800,
        languageBreakdown: { Markdown: 92, YAML: 5, CSS: 3 },
        contributorCount: 6,
        hasWiki: false,
        commits90d: 48,
        primaryOwner: "mei.lin@contoso.com",
        lastCommitAt: daysAgo(7),
      }),
      repo("bravo-fixtures", {
        sizeGb: 0.9,
        loc: 12400,
        languageBreakdown: { Python: 68, JSON: 28, YAML: 4 },
        contributorCount: 2,
        hasWiki: false,
        commits90d: 0,
        primaryOwner: "devon.wilson@contoso.com",
        lastCommitAt: daysAgo(112),
      }),
      repo("bravo-cli", {
        sizeGb: 0.6,
        loc: 22400,
        languageBreakdown: { Python: 88, YAML: 8, Markdown: 4 },
        contributorCount: 3,
        hasWiki: false,
        commits90d: 92,
        primaryOwner: "theo.brandt@contoso.com",
        lastCommitAt: daysAgo(4),
      }),
      repo("bravo-examples", {
        sizeGb: 0.4,
        loc: 8800,
        languageBreakdown: { Python: 62, Jupyter: 28, YAML: 10 },
        contributorCount: 3,
        hasWiki: false,
        commits90d: 36,
        primaryOwner: "priya.patel@contoso.com",
        lastCommitAt: daysAgo(8),
      }),
      repo("bravo-ops", {
        sizeGb: 0.8,
        loc: 18200,
        languageBreakdown: {
          "HCL (Terraform)": 58,
          Shell: 22,
          YAML: 18,
          Markdown: 2,
        },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 14,
        commits90d: 78,
        primaryOwner: "noor.hassan@contoso.com",
        lastCommitAt: daysAgo(2),
      }),
    ],
    workflows: [
      workflow("bravo-api-build", "BUILD", {
        averageDurationMin: 12,
        triggersPerWeek: 68,
        failsLast30d: 4,
        stageCount: 3,
      }),
      workflow("bravo-web-build", "BUILD", {
        averageDurationMin: 8,
        triggersPerWeek: 54,
        failsLast30d: 2,
      }),
      workflow("bravo-sdk-build", "BUILD", {
        averageDurationMin: 14,
        triggersPerWeek: 28,
        failsLast30d: 1,
        stageCount: 2,
      }),
      workflow("bravo-cli-build", "BUILD", {
        averageDurationMin: 6,
        triggersPerWeek: 22,
        failsLast30d: 1,
      }),
      workflow("bravo-ops-plan", "BUILD", {
        averageDurationMin: 7,
        triggersPerWeek: 18,
        failsLast30d: 0,
        stageCount: 2,
        usesVariableGroups: true,
      }),
      workflow("bravo-sdk-test", "TEST", {
        averageDurationMin: 22,
        triggersPerWeek: 28,
        failsLast30d: 3,
        stageCount: 2,
      }),
      workflow("bravo-api-test", "TEST", {
        averageDurationMin: 18,
        triggersPerWeek: 68,
        failsLast30d: 4,
      }),
      workflow("bravo-nightly-integration", "TEST", {
        averageDurationMin: 52,
        triggersPerWeek: 7,
        failsLast30d: 2,
      }),
      workflow("bravo-release-staging", "RELEASE", {
        averageDurationMin: 18,
        triggersPerWeek: 8,
        failsLast30d: 0,
        stageCount: 3,
        usesVariableGroups: true,
      }),
      workflow("bravo-release-prod", "RELEASE", {
        averageDurationMin: 26,
        triggersPerWeek: 0,
        failsLast30d: 0,
        stageCount: 4,
        usesVariableGroups: true,
      }),
      workflow("bravo-docs-deploy", "DEPLOY", {
        averageDurationMin: 5,
        triggersPerWeek: 6,
        failsLast30d: 0,
      }),
      workflow("bravo-sdk-publish", "DEPLOY", {
        averageDurationMin: 7,
        triggersPerWeek: 4,
        failsLast30d: 1,
      }),
    ],
    jtbds: allJtbds(jtbdOverridesFor("BRAVO")),
    // Bravo = "typical healthy team" — standard catalog mix plus a couple of
    // team-specific quirks the agent has detected.
    customizations: [
      customization("C09", { status: "AGENT_HANDLED" }),
      customization("C13", { status: "AGENT_HANDLED" }),
      customization("C16", { status: "AGENT_HANDLED" }),
      customization("C24", { status: "UNKNOWN" }),
      customization("C32", {
        name: "Custom semver tagger script",
        description:
          "Custom semver tagger script invoked from release pipeline.",
        status: "UNKNOWN",
      }),
      customization("C13", {
        name: "Bravo keyvault variable group",
        description:
          "Shared variable group 'bravo-keyvault-secrets' referenced by 3 pipelines.",
        status: "AGENT_HANDLED",
      }),
    ],
    risks: [
      {
        title: "Secret rotation is manual",
        detail:
          "Secrets live in Azure Key Vault; rotation is a quarterly manual process. GitHub Actions equivalent needs designed.",
        confidence: "MEDIUM",
        mitigation: null,
        status: "OPEN",
        category: "Auth",
      },
    ],
    ownership: {
      primaryOwnerEmail: "jordan.kim@contoso.com",
      onCallGroup: "#bravo-oncall",
      escalationContact: "mei.lin@contoso.com",
    },
    adoProjects: [
      adoProject("BravoPlatform", {
        description: "Core Bravo services + SDK",
        repoCount: 6,
        pipelineCount: 10,
        boardCount: 2,
      }),
      adoProject("BravoInfra", {
        description: "Infrastructure as code",
        repoCount: 2,
        pipelineCount: 2,
        boardCount: 1,
      }),
    ],
    serviceConnections: [
      serviceConnection("bravo-azure-prod", "AZURE_RM", {
        targetService: "Azure RM · bravo-prod-eastus",
        authMethod: "service-principal",
        usedByCount: 4,
        lastRotatedAt: daysAgo(78),
      }),
      serviceConnection("bravo-azure-staging", "AZURE_RM", {
        targetService: "Azure RM · bravo-staging",
        authMethod: "service-principal",
        usedByCount: 2,
        lastRotatedAt: daysAgo(78),
      }),
      serviceConnection("bravo-acr", "AZURE_CONTAINER_REGISTRY", {
        targetService: "contosobravoacr.azurecr.io",
        authMethod: "managed-identity",
        usedByCount: 3,
        lastRotatedAt: daysAgo(12),
      }),
      serviceConnection("bravo-nuget-internal", "NUGET_FEED", {
        targetService: "Contoso internal NuGet feed",
        authMethod: "PAT",
        usedByCount: 2,
        lastRotatedAt: null,
      }),
      serviceConnection("bravo-sonar", "GENERIC", {
        targetService: "SonarCloud",
        authMethod: "PAT",
        usedByCount: 2,
        lastRotatedAt: daysAgo(210),
      }),
    ],
    releaseDefinitions: [
      releaseDefinition("bravo-sdk-release", {
        stages: 3,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["manual-approval"],
        deployTargets: ["nuget-prod", "internal-feed"],
        lastRunAt: daysAgo(11),
      }),
      releaseDefinition("bravo-infra-release", {
        stages: 2,
        isClassic: true,
        hasManualGates: false,
        gateTypes: [],
        deployTargets: ["tfstate-eastus"],
        lastRunAt: daysAgo(4),
      }),
    ],
    extensions: [
      extension("Azure Artifacts", "Microsoft", "artifacts", {
        hasGitHubEquivalent: true,
      }),
      extension("SonarCloud", "SonarSource", "code-quality", {
        hasGitHubEquivalent: true,
        notes: "Connects natively to GitHub; re-link required",
      }),
      extension("Veracode", "Veracode", "security", {
        hasGitHubEquivalent: false,
        notes:
          "Veracode has a GH Action but existing ADO-specific scan policies won't port directly.",
      }),
    ],
    agentRun: {
      startedAt: hoursAgo(5),
      completedAt: new Date(hoursAgo(5).getTime() + 72_000),
      durationMs: 72_000,
    },
    curatedFindings: [
      needsInput(
        "Auth & security",
        "secrets.rotationFrequency",
        "Secret rotation frequency",
        "Agent found Azure Key Vault references but could not determine rotation cadence from pipeline metadata.",
      ),
      needsInput(
        "Customizations",
        "customizations.semver-tagger.approach",
        "Semver tagger migration approach",
        "Custom tagger script detected but migration preference (rewrite vs lift-and-shift) requires Champion input.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.bravo-nuget-internal.rotation",
        "NuGet PAT rotation cadence",
        "PAT has no recorded rotation date. Unclear whether the team rotates quarterly or not at all.",
      ),
      needsInput(
        "Pipelines",
        "workflows.bravo-release-prod.environments",
        "Prod release pipeline environment mapping",
        "bravo-release-prod has 4 stages but environment names are parameter-driven; can't statically enumerate targets.",
      ),
      needsInput(
        "Organization",
        "extensions.veracode.approach",
        "Veracode migration approach",
        "Veracode ADO extension has a GH Action equivalent but scan policies are configured in extension-specific UI. Champion to decide: re-create policies or adopt GH Advanced Security.",
      ),
      needsInput(
        "JTBDs",
        "jtbds.publish-sdk.feeds",
        "SDK publish target feeds",
        "SDK publishes to an internal feed and public PyPI; agent couldn't verify credentials for both in GH environment secrets.",
      ),
      needsInput(
        "Ownership",
        "ownership.secondaryEscalation",
        "Secondary escalation contact",
        "Only one escalation contact captured. For Tier 2 team, a secondary is recommended.",
      ),
      needsInput(
        "Code & repos",
        "repos.bravo-fixtures.status",
        "bravo-fixtures repo status",
        "No commits in 112 days. Champion to confirm if this should be archived pre-migration or remains active.",
      ),
      anomaly(
        "Pipelines",
        "workflows.bravo-release-prod.triggersPerWeek",
        "bravo-release-prod has zero triggers",
        "0 / week",
        "Pipeline defined but has not run in 30+ days. May be orphaned — or may be waiting on a scheduled deploy window.",
      ),
      anomaly(
        "Auth & security",
        "serviceConnections.bravo-sonar.rotation",
        "SonarCloud PAT stale",
        "210 days old",
        "PAT last rotated 210 days ago; Contoso policy is 90d.",
      ),
      anomaly(
        "Code & repos",
        "repos.bravo-fixtures.commits90d",
        "bravo-fixtures inactivity",
        "0 commits in 90d",
        "Repository appears inactive. Pattern differs from other bravo-* repos (all active).",
      ),
      anomaly(
        "Organization",
        "extensions.veracode.ghEquivalent",
        "Veracode migration path unclear",
        "has-equivalent: no",
        "Veracode has a GH Action but team's existing scan policies don't port automatically. Worth a closer look before cutover.",
      ),
      needsInput(
        "Work items",
        "workItems.typesToLabels",
        "Work item types collapse to labels",
        "Bravo uses custom ADO types (Feature / Epic / Tech Debt) with distinct state-transition workflows. GitHub Issues is flat type-wise; only labels survive. Champion to decide: recreate the state machine via Projects v2 custom fields, or flatten?",
      ),
      needsInput(
        "Work items",
        "workItems.iterationPathsToMilestones",
        "Iteration paths don't map to Milestones",
        "Bravo's hierarchy (PI → Sprint → Week) flattens to single-level Milestones + Project field. Cross-team rollups break. Champion to pick canonical mapping.",
      ),

      // Inferred findings (source=INFERRED, confidence=LOW).

      anomaly(
        "Work items",
        "workItems.prLinkingBreakage",
        "Existing PR↔work-item auto-linking rules may break on type collapse",
        "rules: custom (Feature / Epic / Tech Debt)",
        "INFERRED adjacency from 'work item types collapse to labels'. Bravo's existing PRs reference work items by type-qualified ID (e.g. 'Epic 1234'). After type collapse, those references resolve to labeled Issues but the type-based auto-linking rules don't carry. Not independently documented for Bravo's setup but a standard consequence of type flattening.",
      ),
      anomaly(
        "Work items",
        "workItems.iterationAutomationTriggers",
        "Automations keyed to 'iteration = current' lose their trigger",
        "automations: inferred ~4",
        "INFERRED chain from 'iteration paths don't map to milestones'. Bravo has automations (notifications, auto-assignment) that fire when an item moves into the current iteration. GH milestones have no equivalent 'current' concept — each automation needs manual re-wiring. Not independently documented but follows from GitHub's milestone model.",
      ),
    ],
  };
}
