import { jtbdOverridesFor } from "./jtbd-scoping";

import {
  adoProject,
  anomaly,
  daysAgo,
  daysFromNow,
  ev,
  extension,
  hoursAgo,
  allJtbds,
  member,
  needsInput,
  releaseDefinition,
  repo,
  serviceConnection,
  workflow,
  type CohortShape,
} from "./_helpers";

export function charlieConfig(orgId: string): CohortShape {
  return {
    orgId,
    name: "Charlie Toolkit",
    slug: "charlie",
    tagline: "The interesting one",
    description:
      "Mid-size engineering team straddling a modern C# platform and a legacy PowerShell tooling surface. Classic build pipelines, an on-prem signing service, FedRAMP High classification, and a dozen real-world migration decisions the Champion will need to make.",
    cohort: "CHARLIE",
    wave: 2,
    migrationState: "REVIEWING",
    engineerCount: 11,
    tier: "TIER_1",
    securityClassification: "FedRAMP High",
    healthStatus: "AT_RISK",
    effortEstimateLowWeeks: 18,
    effortEstimateHighWeeks: 24,
    effortConfidence: "MEDIUM",
    effortProgressWeeks: 12.4,
    targetCutoverAt: daysFromNow(98),
    slackWeeks: -2,
    workItemsActive: 284,
    workItemsClosed90d: 612,
    buildArtifactCount: 468,
    wikiPageCount: 92,
    championEmail: "rory.mcdonald@contoso.com",
    members: [
      member(
        "Rory McDonald",
        "rory.mcdonald@contoso.com",
        "Principal Engineer",
      ),
      member("Aisha Mohammed", "aisha.mohammed@contoso.com", "Senior Engineer"),
      member("Ben Novak", "ben.novak@contoso.com", "Engineer"),
      member("Carlos Rivera", "carlos.rivera@contoso.com", "Engineer"),
      member("Diana Park", "diana.park@contoso.com", "Senior Engineer"),
      member("Ethan Brooks", "ethan.brooks@contoso.com", "Staff Engineer"),
      member("Fatima Okafor", "fatima.okafor@contoso.com", "Senior SRE"),
      member("Greg Ito", "greg.ito@contoso.com", "Engineer"),
      member(
        "Hanna Nilsson",
        "hanna.nilsson@contoso.com",
        "Engineering Manager",
      ),
      member("Ivan Dvorak", "ivan.dvorak@contoso.com", "Engineer"),
      member("Julia Reyes", "julia.reyes@contoso.com", "Senior Engineer"),
    ],
    codebase: {
      primaryLang: "C#",
      usesLfs: true,
      totalSizeGb: 58.4,
    },
    repos: [
      repo("charlie-core", {
        sizeGb: 8.2,
        loc: 284000,
        languageBreakdown: { "C#": 88, YAML: 6, PowerShell: 4, Markdown: 2 },
        contributorCount: 11,
        hasWiki: true,
        wikiPageCount: 34,
        commits90d: 612,
        primaryOwner: "rory.mcdonald@contoso.com",
        lastCommitAt: hoursAgo(4),
      }),
      repo("charlie-signer", {
        sizeGb: 1.2,
        loc: 28400,
        languageBreakdown: { "C#": 72, PowerShell: 22, YAML: 6 },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 12,
        commits90d: 88,
        primaryOwner: "ethan.brooks@contoso.com",
        lastCommitAt: daysAgo(2),
      }),
      repo("charlie-ui", {
        sizeGb: 3.4,
        loc: 124000,
        languageBreakdown: {
          TypeScript: 62,
          CSS: 16,
          HTML: 8,
          YAML: 8,
          Markdown: 6,
        },
        contributorCount: 6,
        hasWiki: true,
        wikiPageCount: 18,
        commits90d: 418,
        primaryOwner: "aisha.mohammed@contoso.com",
        lastCommitAt: daysAgo(1),
      }),
      repo("charlie-legacy-tools", {
        sizeGb: 4.5,
        loc: 92000,
        languageBreakdown: { PowerShell: 78, "C#": 14, Batch: 6, Markdown: 2 },
        contributorCount: 2,
        hasWiki: false,
        commits90d: 6,
        defaultBranch: "master",
        primaryOwner: "ben.novak@contoso.com",
        lastCommitAt: daysAgo(41),
        branchProtected: false,
        submoduleUrls: [
          "https://dev.azure.com/contoso/Legacy/_git/shared-signing",
        ],
      }),
      repo("charlie-cli", {
        sizeGb: 0.8,
        loc: 38000,
        languageBreakdown: { "C#": 84, YAML: 8, Markdown: 8 },
        contributorCount: 5,
        hasWiki: true,
        wikiPageCount: 8,
        commits90d: 182,
        primaryOwner: "carlos.rivera@contoso.com",
        lastCommitAt: daysAgo(2),
      }),
      repo("charlie-telemetry", {
        sizeGb: 1.1,
        loc: 42000,
        languageBreakdown: { "C#": 92, YAML: 6, Markdown: 2 },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 14,
        commits90d: 226,
        primaryOwner: "fatima.okafor@contoso.com",
        lastCommitAt: hoursAgo(18),
      }),
      repo("charlie-sdk", {
        sizeGb: 1.2,
        loc: 54000,
        languageBreakdown: { "C#": 82, YAML: 10, Markdown: 8 },
        contributorCount: 7,
        hasWiki: true,
        wikiPageCount: 22,
        commits90d: 264,
        primaryOwner: "diana.park@contoso.com",
        lastCommitAt: daysAgo(1),
        hasSubmodules: true,
        submoduleUrls: [
          "https://dev.azure.com/contoso/SharedLibs/_git/core-dto",
        ],
      }),
      repo("charlie-sdk-py", {
        sizeGb: 0.6,
        loc: 22000,
        languageBreakdown: { Python: 88, YAML: 8, Markdown: 4 },
        contributorCount: 3,
        hasWiki: false,
        commits90d: 78,
        primaryOwner: "julia.reyes@contoso.com",
        lastCommitAt: daysAgo(6),
      }),
      repo("charlie-sdk-cs", {
        sizeGb: 0.9,
        loc: 32000,
        languageBreakdown: { "C#": 92, YAML: 6, Markdown: 2 },
        contributorCount: 4,
        hasWiki: false,
        commits90d: 112,
        primaryOwner: "diana.park@contoso.com",
        lastCommitAt: daysAgo(3),
      }),
      repo("charlie-integration-tests", {
        sizeGb: 2.4,
        loc: 68000,
        languageBreakdown: { "C#": 72, YAML: 18, JSON: 10 },
        contributorCount: 8,
        hasWiki: true,
        wikiPageCount: 10,
        commits90d: 184,
        primaryOwner: "greg.ito@contoso.com",
        lastCommitAt: daysAgo(2),
      }),
      repo("charlie-perf-tests", {
        sizeGb: 24.6,
        loc: 18000,
        languageBreakdown: { "C#": 54, JSON: 28, YAML: 12, Binary: 6 },
        contributorCount: 3,
        hasWiki: true,
        wikiPageCount: 6,
        commits90d: 42,
        primaryOwner: "fatima.okafor@contoso.com",
        lastCommitAt: daysAgo(7),
        hasLfs: true,
        lfsSizeGb: 18.4,
      }),
      repo("charlie-docs", {
        sizeGb: 0.4,
        loc: 14800,
        languageBreakdown: { Markdown: 92, YAML: 6, CSS: 2 },
        contributorCount: 9,
        hasWiki: false,
        commits90d: 126,
        primaryOwner: "hanna.nilsson@contoso.com",
        lastCommitAt: daysAgo(1),
      }),
      repo("charlie-examples", {
        sizeGb: 0.5,
        loc: 12400,
        languageBreakdown: { "C#": 58, Python: 22, JSON: 14, Markdown: 6 },
        contributorCount: 5,
        hasWiki: false,
        commits90d: 52,
        primaryOwner: "julia.reyes@contoso.com",
        lastCommitAt: daysAgo(8),
      }),
      repo("charlie-infra", {
        sizeGb: 0.8,
        loc: 18200,
        languageBreakdown: {
          "HCL (Terraform)": 68,
          YAML: 18,
          Shell: 12,
          Markdown: 2,
        },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 16,
        commits90d: 94,
        primaryOwner: "fatima.okafor@contoso.com",
        lastCommitAt: daysAgo(3),
      }),
      repo("charlie-deploy-scripts", {
        sizeGb: 0.6,
        loc: 11200,
        languageBreakdown: { PowerShell: 76, Shell: 14, YAML: 10 },
        contributorCount: 3,
        hasWiki: false,
        commits90d: 22,
        defaultBranch: "master",
        primaryOwner: "ben.novak@contoso.com",
        lastCommitAt: daysAgo(18),
        branchProtected: false,
      }),
      repo("charlie-internal-tools", {
        sizeGb: 0.3,
        loc: 8400,
        languageBreakdown: { PowerShell: 82, Batch: 12, Markdown: 6 },
        contributorCount: 2,
        hasWiki: false,
        commits90d: 0,
        isArchived: true,
        primaryOwner: "ben.novak@contoso.com",
        lastCommitAt: daysAgo(198),
        branchProtected: false,
      }),
      repo("charlie-release-scripts", {
        sizeGb: 0.2,
        loc: 6200,
        languageBreakdown: { PowerShell: 88, YAML: 8, Markdown: 4 },
        contributorCount: 3,
        hasWiki: false,
        commits90d: 14,
        primaryOwner: "ivan.dvorak@contoso.com",
        lastCommitAt: daysAgo(9),
      }),
      repo("charlie-samples", {
        sizeGb: 0.2,
        loc: 4800,
        languageBreakdown: { "C#": 72, Markdown: 28 },
        contributorCount: 2,
        hasWiki: false,
        commits90d: 0,
        isArchived: true,
        primaryOwner: "rory.mcdonald@contoso.com",
        lastCommitAt: daysAgo(168),
        branchProtected: false,
      }),
    ],
    workflows: [
      workflow("charlie-core-build", "BUILD", {
        isClassic: true,
        customTasks: [
          "PowerShell@2 — custom signing",
          "FileTransform@1",
          "NuGetCommand@2 — internal feed",
        ],
        deprecatedTasks: ["PowerShell@1"],
        runnerType: "SELF_HOSTED",
        agentPool: "contoso-signing-pool",
        stageCount: 5,
        averageDurationMin: 38,
        triggersPerWeek: 52,
        failsLast30d: 14,
      }),
      workflow("charlie-core-test", "TEST", {
        averageDurationMin: 26,
        triggersPerWeek: 52,
        failsLast30d: 8,
        stageCount: 3,
      }),
      workflow("charlie-signer-build", "BUILD", {
        isClassic: true,
        customTasks: ["PowerShell@2 — signing-service-bootstrap"],
        runnerType: "SELF_HOSTED",
        agentPool: "contoso-signing-pool",
        stageCount: 3,
        averageDurationMin: 22,
        triggersPerWeek: 12,
        failsLast30d: 3,
      }),
      workflow("charlie-ui-build", "BUILD", {
        averageDurationMin: 14,
        triggersPerWeek: 68,
        failsLast30d: 4,
        stageCount: 3,
      }),
      workflow("charlie-ui-test", "TEST", {
        averageDurationMin: 18,
        triggersPerWeek: 68,
        failsLast30d: 6,
      }),
      workflow("charlie-cli-build", "BUILD", {
        averageDurationMin: 9,
        triggersPerWeek: 22,
        failsLast30d: 2,
      }),
      workflow("charlie-telemetry-build", "BUILD", {
        averageDurationMin: 7,
        triggersPerWeek: 34,
        failsLast30d: 1,
      }),
      workflow("charlie-sdk-build", "BUILD", {
        averageDurationMin: 16,
        triggersPerWeek: 32,
        failsLast30d: 2,
        stageCount: 3,
      }),
      workflow("charlie-sdk-py-build", "BUILD", {
        averageDurationMin: 8,
        triggersPerWeek: 12,
        failsLast30d: 0,
      }),
      workflow("charlie-sdk-cs-build", "BUILD", {
        averageDurationMin: 11,
        triggersPerWeek: 18,
        failsLast30d: 1,
      }),
      workflow("charlie-integration", "TEST", {
        averageDurationMin: 68,
        triggersPerWeek: 14,
        failsLast30d: 9,
        stageCount: 4,
        usesVariableGroups: true,
      }),
      workflow("charlie-perf-nightly", "TEST", {
        averageDurationMin: 142,
        triggersPerWeek: 7,
        failsLast30d: 4,
        stageCount: 2,
        agentPool: "contoso-perf-pool",
        runnerType: "SELF_HOSTED",
      }),
      workflow("charlie-release-staging", "RELEASE", {
        isClassic: true,
        customTasks: ["AzureFileCopy@4", "PowerShell@2 — deploy-orchestrator"],
        deprecatedTasks: ["AzureFileCopy@3"],
        stageCount: 4,
        averageDurationMin: 28,
        triggersPerWeek: 4,
        failsLast30d: 2,
        usesVariableGroups: true,
      }),
      workflow("charlie-release-prod", "RELEASE", {
        isClassic: true,
        customTasks: [
          "AzureFileCopy@4",
          "PowerShell@2 — deploy-orchestrator",
          "ServiceNowApproval@1",
        ],
        deprecatedTasks: ["AzureFileCopy@3", "PowerShell@1"],
        stageCount: 6,
        averageDurationMin: 72,
        triggersPerWeek: 1,
        failsLast30d: 0,
        usesVariableGroups: true,
      }),
      workflow("charlie-deploy-scripts", "DEPLOY", {
        isClassic: true,
        customTasks: ["PowerShell@2 — legacy-deploy"],
        deprecatedTasks: ["PowerShell@1"],
        stageCount: 2,
        averageDurationMin: 18,
        triggersPerWeek: 2,
        failsLast30d: 1,
      }),
      workflow("charlie-docs-deploy", "DEPLOY", {
        averageDurationMin: 6,
        triggersPerWeek: 6,
        failsLast30d: 0,
      }),
      workflow("charlie-sdk-publish", "DEPLOY", {
        stageCount: 3,
        averageDurationMin: 14,
        triggersPerWeek: 3,
        failsLast30d: 1,
        usesVariableGroups: true,
      }),
      workflow("charlie-sdk-cs-publish", "DEPLOY", {
        averageDurationMin: 12,
        triggersPerWeek: 2,
        failsLast30d: 0,
        usesVariableGroups: true,
      }),
      workflow("charlie-sdk-py-publish", "DEPLOY", {
        averageDurationMin: 8,
        triggersPerWeek: 2,
        failsLast30d: 0,
      }),
      workflow("charlie-infra-plan", "BUILD", {
        averageDurationMin: 9,
        triggersPerWeek: 16,
        failsLast30d: 0,
        usesVariableGroups: true,
      }),
      workflow("charlie-infra-apply", "DEPLOY", {
        stageCount: 3,
        averageDurationMin: 14,
        triggersPerWeek: 4,
        failsLast30d: 1,
        usesVariableGroups: true,
      }),
      workflow("charlie-security-scan", "TEST", {
        averageDurationMin: 42,
        triggersPerWeek: 7,
        failsLast30d: 2,
      }),
      workflow("charlie-compliance-check", "TEST", {
        averageDurationMin: 18,
        triggersPerWeek: 14,
        failsLast30d: 0,
      }),
      workflow("charlie-legacy-build", "BUILD", {
        isClassic: true,
        customTasks: ["PowerShell@2"],
        deprecatedTasks: ["PowerShell@1"],
        stageCount: 2,
        averageDurationMin: 11,
        triggersPerWeek: 0,
        failsLast30d: 0,
      }),
      workflow("charlie-release-scripts-build", "BUILD", {
        isClassic: true,
        stageCount: 2,
        averageDurationMin: 8,
        triggersPerWeek: 1,
        failsLast30d: 0,
      }),
      workflow("charlie-samples-build", "BUILD", {
        averageDurationMin: 4,
        triggersPerWeek: 0,
        failsLast30d: 0,
      }),
      workflow("charlie-dependency-scan", "TEST", {
        averageDurationMin: 14,
        triggersPerWeek: 7,
        failsLast30d: 0,
      }),
      workflow("charlie-fedramp-audit", "TEST", {
        averageDurationMin: 52,
        triggersPerWeek: 1,
        failsLast30d: 0,
        usesVariableGroups: true,
      }),
    ],
    jtbds: allJtbds(jtbdOverridesFor("CHARLIE")),
    customizations: [
      {
        category: "Pipelines",
        description:
          "Custom PowerShell signing task invokes on-prem signing service via agent token.",
        migrationApproach: null,
        status: "NEEDS_HUMAN",
      },
      {
        category: "Release",
        description:
          "Legacy build-number scheme (yy.mm.dd.build) — agent mapped to GitHub Actions run number expression.",
        migrationApproach: "rewrite-as-github-action",
        status: "AGENT_HANDLED",
      },
      {
        category: "Pipelines",
        description:
          "Classic pipeline YAML conversion has 3 unsupported task types; manual remediation required.",
        migrationApproach: null,
        status: "NEEDS_HUMAN",
      },
      {
        category: "Release",
        description:
          "ServiceNow approval gate on prod release — no direct GH Actions equivalent.",
        migrationApproach: null,
        status: "NEEDS_HUMAN",
      },
      {
        category: "Pipelines",
        description:
          "Self-hosted agent pool in private VLAN — required for signing service connectivity.",
        migrationApproach: "github-self-hosted-runners",
        status: "NEEDS_HUMAN",
      },
      {
        category: "Pipelines",
        description:
          "FileTransform@1 usage across 4 pipelines — maps to envsubst or a GH action replacement.",
        migrationApproach: "rewrite-as-github-action",
        status: "AGENT_HANDLED",
      },
    ],
    risks: [
      {
        title: "Classic pipeline cannot be converted 1:1",
        detail:
          "Charlie's classic build pipeline uses 3 custom task types that have no direct GitHub Actions equivalent. Manual rewrite required, estimated 3–5 days of engineering time.",
        confidence: "HIGH",
        mitigation: null,
        status: "OPEN",
        category: "Pipelines",
      },
      {
        title: "Custom signing task has no GitHub equivalent",
        detail:
          "PowerShell signing task calls an on-prem signing service via an agent token. Moving off ADO means designing a new signing flow (likely reusable workflow + OIDC).",
        confidence: "HIGH",
        mitigation: null,
        status: "OPEN",
        category: "Auth",
      },
      {
        title: "charlie-legacy-tools has stale linked artifacts",
        detail:
          "Repository links to build artifacts from a decommissioned feed. Build will fail after migration unless artifact sources are re-pointed.",
        confidence: "MEDIUM",
        mitigation: null,
        status: "OPEN",
        category: "Code & repos",
      },
      {
        title: "ServiceNow approval gate on prod releases",
        detail:
          "Prod release pipeline uses ServiceNowApproval@1 task. No direct GH equivalent; requires redesign (manual approval via GH environment protection rules + ServiceNow webhook).",
        confidence: "HIGH",
        mitigation: null,
        status: "OPEN",
        category: "Pipelines",
      },
      {
        title: "Self-hosted agent pool in private VLAN",
        detail:
          "Signing pipelines require access to on-prem signing service. Requires GH self-hosted runners with equivalent network access.",
        confidence: "MEDIUM",
        mitigation:
          "Network team spinning up an equivalent GH runner pool in the same VLAN. Target delivery: 3 weeks.",
        status: "MITIGATED",
        category: "Auth",
      },
    ],
    ownership: {
      primaryOwnerEmail: "rory.mcdonald@contoso.com",
      onCallGroup: "#charlie-oncall",
      escalationContact: "hanna.nilsson@contoso.com",
    },
    adoProjects: [
      adoProject("CharlieCore", {
        description: "Core Charlie platform + signing",
        repoCount: 10,
        pipelineCount: 18,
        boardCount: 3,
      }),
      adoProject("CharlieSDK", {
        description: "Public and internal SDKs",
        repoCount: 5,
        pipelineCount: 8,
        boardCount: 2,
      }),
      adoProject("CharlieLegacy", {
        description:
          "Legacy PowerShell tooling — archived but still in migration scope",
        visibility: "private",
        repoCount: 3,
        pipelineCount: 2,
        boardCount: 1,
      }),
    ],
    serviceConnections: [
      serviceConnection("charlie-azure-prod", "AZURE_RM", {
        targetService: "Azure RM · charlie-prod-eastus-fedramp",
        authMethod: "service-principal",
        usedByCount: 6,
        lastRotatedAt: daysAgo(52),
      }),
      serviceConnection("charlie-azure-gov", "AZURE_RM", {
        targetService: "Azure Gov · charlie-prod-usgov",
        authMethod: "service-principal",
        usedByCount: 4,
        lastRotatedAt: daysAgo(52),
      }),
      serviceConnection("charlie-acr", "AZURE_CONTAINER_REGISTRY", {
        targetService: "contosocharlieacr.azurecr.io",
        authMethod: "managed-identity",
        usedByCount: 5,
        lastRotatedAt: daysAgo(18),
      }),
      serviceConnection("charlie-signing-svc", "GENERIC", {
        targetService: "On-prem signing service (signing.contoso.local)",
        authMethod: "service-account",
        hasStoredCredential: true,
        usedByCount: 3,
        lastRotatedAt: daysAgo(148),
      }),
      serviceConnection("charlie-nuget-internal", "NUGET_FEED", {
        targetService: "Contoso internal NuGet",
        authMethod: "PAT",
        usedByCount: 4,
        lastRotatedAt: null,
      }),
      serviceConnection("charlie-npm-internal", "NPM_FEED", {
        targetService: "Contoso internal NPM",
        authMethod: "PAT",
        usedByCount: 2,
        lastRotatedAt: daysAgo(112),
      }),
      serviceConnection("charlie-servicenow", "GENERIC", {
        targetService: "ServiceNow instance (contoso.service-now.com)",
        authMethod: "service-account",
        usedByCount: 2,
        lastRotatedAt: daysAgo(94),
      }),
      serviceConnection("charlie-snyk", "GENERIC", {
        targetService: "Snyk org: contoso-charlie",
        authMethod: "PAT",
        usedByCount: 1,
        lastRotatedAt: daysAgo(82),
      }),
      serviceConnection("charlie-sonar", "GENERIC", {
        targetService: "SonarCloud org: contoso",
        authMethod: "PAT",
        usedByCount: 2,
        lastRotatedAt: daysAgo(180),
      }),
    ],
    releaseDefinitions: [
      releaseDefinition("charlie-core-release", {
        stages: 5,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["servicenow-approval", "manual-approval"],
        deployTargets: [
          "prod-eastus",
          "prod-westus2",
          "gov-virginia",
          "gov-arizona",
        ],
        lastRunAt: daysAgo(8),
      }),
      releaseDefinition("charlie-signer-release", {
        stages: 3,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["manual-approval"],
        deployTargets: ["signing-prod-vlan"],
        lastRunAt: daysAgo(14),
      }),
      releaseDefinition("charlie-legacy-maintenance", {
        stages: 2,
        isClassic: true,
        hasManualGates: false,
        gateTypes: [],
        deployTargets: ["legacy-infra"],
        lastRunAt: daysAgo(62),
      }),
      releaseDefinition("charlie-ui-release", {
        stages: 4,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["manual-approval", "azure-monitor"],
        deployTargets: ["cdn-edge", "prod-eastus", "prod-westus2"],
        lastRunAt: daysAgo(4),
      }),
    ],
    extensions: [
      extension("Azure Artifacts", "Microsoft", "artifacts", {
        hasGitHubEquivalent: true,
      }),
      extension("SonarCloud", "SonarSource", "code-quality", {
        hasGitHubEquivalent: true,
        notes: "Native GitHub integration available.",
      }),
      extension("Snyk Security", "Snyk", "security", {
        hasGitHubEquivalent: true,
        notes: "Snyk has a GH App; ADO scan policies don't carry over.",
      }),
      extension(
        "ServiceNow Change Management",
        "ServiceNow",
        "release-approval",
        {
          hasGitHubEquivalent: false,
          notes:
            "No GH equivalent. Workaround: workflow_dispatch + webhook to ServiceNow.",
        },
      ),
      extension("Compliance Reporter", "Contoso Internal", "reporting", {
        hasGitHubEquivalent: false,
        notes:
          "Internal tool — needs to be reimplemented as a reusable workflow.",
      }),
      extension("Veracode Static Analysis", "Veracode", "security", {
        hasGitHubEquivalent: true,
        notes:
          "GH Action exists; scan policies configured in Veracode UI must be re-linked.",
      }),
    ],
    agentRun: {
      startedAt: hoursAgo(8),
      completedAt: new Date(hoursAgo(8).getTime() + 178_000),
      durationMs: 178_000,
    },
    curatedFindings: [
      // Needs-input (persona: many decisions to make)
      // Ordered so Champion sees one-of-each input type on first review visit
      // (multi-select, then single-select, then free-text — satisfies M1 AC #4).
      needsInput(
        "Pipelines",
        "workflows.charlie-core-build.customTasks",
        "Custom tasks in charlie-core-build",
        "Agent found 3 custom task types (PowerShell@2 signing, FileTransform@1, NuGetCommand@2) but could not determine GitHub Actions migration mapping.",
      ),
      needsInput(
        "Customizations",
        "customizations.classic-yaml.approach",
        "Classic YAML conversion approach",
        "3 unsupported task types in classic pipeline. Manual rewrite vs lift-and-shift requires Champion decision.",
      ),
      needsInput(
        "Auth & security",
        "secrets.signingServiceToken",
        "Signing service token storage",
        "Signing service expects a service account token; new credential flow (OIDC?) requires design.",
      ),
      needsInput(
        "Customizations",
        "customizations.signing.approach",
        "Signing customization migration approach",
        "PowerShell signing task invokes on-prem service. No GH equivalent; Champion must confirm approach.",
      ),
      needsInput(
        "Customizations",
        "customizations.servicenow-gate.approach",
        "ServiceNow gate replacement approach",
        "ServiceNowApproval@1 task has no GH Action equivalent. Options: workflow_dispatch + webhook, OR manual GH environment approval pointing to ServiceNow URL.",
      ),
      needsInput(
        "Pipelines",
        "workflows.charlie-release-prod.environments",
        "Prod release environment mapping",
        "6-stage prod release references 4 deploy targets via parameter-driven environment names. Can't statically map to GH environments.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.signing-svc.authMigration",
        "Signing service auth migration",
        "Signing service uses a service-account token rotated via Contoso IAM. Champion to confirm: keep same token in GH secret, OR move to OIDC?",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.nuget-internal.rotation",
        "NuGet PAT rotation",
        "PAT has no recorded rotation date. Policy is 90d; Champion to confirm current cadence.",
      ),
      needsInput(
        "Code & repos",
        "repos.charlie-legacy-tools.migration",
        "charlie-legacy-tools migration decision",
        "Repository has master branch, minimal activity, and references decommissioned artifact feed. Champion to decide: archive pre-migration, migrate as-is, or retire entirely.",
      ),
      needsInput(
        "Code & repos",
        "repos.charlie-deploy-scripts.migration",
        "charlie-deploy-scripts migration decision",
        "Similar pattern to legacy-tools: master branch, infrequent commits, PowerShell-heavy. Migrate or consolidate?",
      ),
      needsInput(
        "Pipelines",
        "workflows.charlie-legacy-build.status",
        "charlie-legacy-build pipeline status",
        "Pipeline hasn't run in 30 days. Orphaned or parked? Affects whether we migrate or retire.",
      ),
      needsInput(
        "Pipelines",
        "agentPools.contoso-signing-pool.migration",
        "Self-hosted pool migration plan",
        "3 pipelines require the signing pool. Network team must provision GH runners in the same VLAN; Champion to confirm timeline.",
      ),
      needsInput(
        "Code & repos",
        "repos.charlie-perf-tests.lfsMigration",
        "LFS migration for charlie-perf-tests",
        "18.4 GB of LFS data. Champion to confirm: migrate LFS in-place with git-lfs-migrate, OR restart LFS tracking in GH (lose history)?",
      ),
      needsInput(
        "Code & repos",
        "repos.charlie-core.submoduleRewrite",
        "Submodule URL rewriting for charlie-sdk",
        "Submodule points to dev.azure.com/contoso/SharedLibs. After migration, this needs to rewrite to the new GH URL — Champion to confirm canonical URL pattern.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.servicenow.rotation",
        "ServiceNow service account rotation",
        "Credential is 94 days old; outside 90-day policy. Rotate before or during cutover?",
      ),
      needsInput(
        "Organization",
        "extensions.compliance-reporter.migration",
        "Compliance Reporter replacement",
        "Internal ADO extension — needs to be reimplemented as a reusable GH workflow. Scope + owner unknown.",
      ),
      needsInput(
        "Organization",
        "extensions.servicenow.approach",
        "ServiceNow change mgmt migration",
        "Choose between: workflow_dispatch webhook, manual approval with ServiceNow link, OR third-party GH App.",
      ),
      needsInput(
        "JTBDs",
        "jtbds.sign-artifact.environment",
        "Signing workflow environment",
        "sign-artifact JTBD stays tied to on-prem signing; Champion to confirm which GH environment (prod-signing?) governs access.",
      ),
      needsInput(
        "JTBDs",
        "jtbds.audit-fedramp.scope",
        "FedRAMP audit scope",
        "Audit pipelines touch many compliance scanners. Champion to confirm which must run pre-merge vs nightly vs pre-release.",
      ),
      needsInput(
        "Ownership",
        "ownership.secondaryEscalation",
        "Secondary escalation contact",
        "Only primary (Hanna) captured. Tier 1 / FedRAMP team needs a secondary.",
      ),
      needsInput(
        "Work items",
        "workItems.processTemplate",
        "Work item template migration",
        "ADO process template has 14 custom fields. Mapping to GH Issues + labels requires Champion-approved field-by-field decisions.",
      ),
      needsInput(
        "Pipelines",
        "workflows.charlie-release-prod.approvers",
        "Prod release approvers",
        "Current approval list includes 4 people; GH environment protection rules cap at ~6. Champion to confirm current list is accurate.",
      ),
      needsInput(
        "Auth & security",
        "variableGroups.charlie-secrets.migration",
        "Variable group migration",
        "5 variable groups reference Key Vault. Champion to decide: replicate in GH environment secrets, OR keep Key Vault and pull via OIDC?",
      ),
      needsInput(
        "Pipelines",
        "workflows.charlie-perf-nightly.schedule",
        "Perf nightly schedule",
        "Agent found a scheduled trigger but cron expression references ADO-specific timezones. Champion to confirm target schedule in UTC.",
      ),
      needsInput(
        "Code & repos",
        "repos.charlie-internal-tools.archiveDecision",
        "Archive charlie-internal-tools?",
        "Already archived in ADO with no commits in 6 months. Champion to confirm whether to bring over or leave behind.",
      ),
      needsInput(
        "Code & repos",
        "repos.charlie-samples.archiveDecision",
        "Archive charlie-samples?",
        "Archived; samples consolidated into charlie-examples. Champion to confirm we can leave this behind.",
      ),
      needsInput(
        "Pipelines",
        "releaseDefinitions.charlie-legacy-maintenance.retirement",
        "Retire legacy maintenance release?",
        "62 days since last run. Scope seems retired; Champion to confirm we can skip migration.",
      ),
      needsInput(
        "Auth & security",
        "secrets.fedrampAudit.secretStorage",
        "FedRAMP audit tool credentials",
        "charlie-fedramp-audit workflow pulls secrets from Key Vault. Champion to decide secret storage strategy in GH.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.sonar.rotation",
        "SonarCloud PAT rotation",
        "PAT is 180 days old; policy is 90. Rotate before cutover and store in GH secrets with the new value.",
      ),
      needsInput(
        "Pipelines",
        "workflows.deprecated-tasks.policy",
        "Deprecated task policy",
        "6 pipelines use PowerShell@1 or AzureFileCopy@3. Champion to confirm: upgrade all in-place before cutover, or carry forward and upgrade post-migration?",
      ),
      needsInput(
        "JTBDs",
        "jtbds.onboard-dev.workflow",
        "Dev onboarding workflow",
        "Current onboarding includes ADO-specific steps (PAT creation, org join). Champion to sign off on GH-equivalent runbook.",
      ),
      needsInput(
        "Work items",
        "workItems.bulkMigration.batchSize",
        "Work item migration batch size",
        "612 closed items in 90d. Champion to confirm: migrate all history, or only open + last-90d?",
      ),

      // Anomalies (persona: classic pipelines, legacy tooling, compliance edges)
      anomaly(
        "Pipelines",
        "workflows.charlie-core-build.unsupportedTasks",
        "3 unsupported task types in charlie-core-build",
        "count: 3 · HIGH impact",
        "Severity inferred from count of unsupported tasks; Champion should confirm impact.",
        [
          ev.file(
            "charlie-core/azure-pipelines.yml",
            "- task: PowerShell@2\n  displayName: 'Custom code signing'\n  inputs:\n    filePath: 'scripts/sign.ps1'\n- task: FileTransform@1\n  inputs:\n    folderPath: '$(Build.SourcesDirectory)/config'\n- task: NuGetCommand@2\n  inputs:\n    command: 'restore'\n    feedsToUse: 'config'\n    nugetConfigPath: 'nuget.config'",
            "scanned: 2026-04-22T22:58:03Z · line refs: 42, 64, 78",
            "https://dev.azure.com/contoso/CharlieCore/_git/charlie-core?path=/azure-pipelines.yml",
          ),
          ev.url(
            "https://docs.github.com/en/actions/tutorials/migrate-to-github-actions/automated-migrations/azure-devops-migration",
            "Actions Importer targets 80% conversion; custom PowerShell/FileTransform/NuGet tasks are among the common manual-rewrite cases.",
            "GitHub Docs",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.charlie-legacy-tools.artifactFeed",
        "charlie-legacy-tools artifact feed status",
        "decommissioned?",
        "Build references an artifact feed that returned 404 during probe. Could be decommissioned or temporarily unavailable.",
        [
          ev.log(
            "ado-discovery-agent.log",
            "[2026-04-22T22:58:11Z] GET https://pkgs.dev.azure.com/contoso/_packaging/legacy-artifacts/nuget/v3/index.json\n[2026-04-22T22:58:11Z] → 404 Not Found (retry 1/3)\n[2026-04-22T22:58:13Z] → 404 Not Found (retry 2/3)\n[2026-04-22T22:58:17Z] → 404 Not Found (retry 3/3)\n[2026-04-22T22:58:17Z] ABORT: feed appears unreachable",
            "status: 404 · retries: 3 · elapsed: 6.2s",
          ),
          ev.config(
            "charlie-legacy-tools/nuget.config",
            '<packageSources>\n  <add key="legacy-artifacts" value="https://pkgs.dev.azure.com/contoso/_packaging/legacy-artifacts/nuget/v3/index.json" />\n</packageSources>',
            "last-modified: 2023-11-14 · not updated since",
          ),
        ],
      ),
      anomaly(
        "Pipelines",
        "workflows.charlie-release-prod.deployTargets",
        "charlie-release-prod deploy targets",
        "unclear",
        "AzureFileCopy@4 task references multiple destinations; agent could not enumerate all.",
        [
          ev.config(
            "charlie-release-prod/stages/deploy.yml:stage-4",
            "- task: AzureFileCopy@4\n  inputs:\n    SourcePath: '$(Pipeline.Workspace)/drop/**'\n    azureSubscription: '$(prodSubscription)'\n    Destination: 'AzureBlob'\n    storage: '$(storageAccount)'\n    ContainerName: '$(containerName)'",
            "parameterized targets: prodSubscription, storageAccount, containerName · can't statically enumerate",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.charlie-legacy-tools.defaultBranch",
        "charlie-legacy-tools default branch",
        "master (non-standard)",
        "Default branch is 'master' while rest of org uses 'main'. Migration may want to rename or preserve.",
        [
          ev.api(
            "GET /_apis/git/repositories/charlie-legacy-tools",
            '{\n  "id": "af3b1c82-...",\n  "name": "charlie-legacy-tools",\n  "defaultBranch": "refs/heads/master",\n  "size": 4831838208,\n  "isArchived": false\n}',
            "ADO REST v7.1 · retrieved: 2026-04-22T22:58:24Z",
            "https://dev.azure.com/contoso/CharlieLegacy/_apis/git/repositories/charlie-legacy-tools",
          ),
        ],
      ),
      anomaly(
        "Customizations",
        "customizations.build-number.scheme",
        "Build number scheme mapping",
        "mapped to GH run number expression",
        "Mapping from yy.mm.dd.build to GitHub Actions is heuristic; semantic equivalence not guaranteed.",
        [
          ev.config(
            "charlie-core/azure-pipelines.yml:name",
            "name: $(Year:yy).$(Month).$(DayOfMonth).$(Rev:r)",
            "current ADO scheme",
          ),
          ev.config(
            ".github/workflows/charlie-core.yml:run-name (proposed)",
            "run-name: \"${{ format('{0:yy}.{0:MM}.{0:dd}', github.event.repository.pushed_at) }}.${{ github.run_number }}\"",
            "proposed GH mapping · semantic match to Rev:r is approximate",
          ),
        ],
      ),
      anomaly(
        "Pipelines",
        "workflows.charlie-deploy-scripts.deprecated",
        "Deprecated PowerShell@1 task in active use",
        "task: PowerShell@1",
        "Task marked deprecated by Microsoft but still referenced. Works today; may break in a future ADO update even before migration.",
        [
          ev.file(
            "charlie-deploy-scripts/azure-pipelines.yml:14",
            "- task: PowerShell@1\n  displayName: 'Legacy deploy orchestrator'\n  inputs:\n    scriptName: 'scripts/deploy-legacy.ps1'",
            "active · last run: 18 days ago",
          ),
          ev.url(
            "https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/",
            "Task reference catalog — PowerShell@1 marked deprecated; @2 is current.",
            "Microsoft Learn",
          ),
        ],
      ),
      anomaly(
        "Auth & security",
        "serviceConnections.charlie-signing-svc.rotation",
        "Signing service token 148 days old",
        "148 days · policy: 90d",
        "Token is well past rotation policy. May pre-date current policy; or rotation may have silently failed.",
        [
          ev.api(
            "GET /_apis/serviceendpoint/endpoints/charlie-signing-svc",
            '{\n  "id": "7a2d...",\n  "name": "charlie-signing-svc",\n  "type": "Generic",\n  "authorization": { "scheme": "Token" },\n  "modifiedOn": "2025-11-27T09:14:22Z",\n  "isReady": true\n}',
            "modifiedOn + 148 days = today · Contoso IAM policy: rotate every 90d",
            "https://dev.azure.com/contoso/CharlieCore/_settings/adminservices",
          ),
        ],
      ),
      anomaly(
        "Pipelines",
        "workflows.charlie-release-staging.parallelism",
        "charlie-release-staging parallelism inferred",
        "stages: 4 · inferred: sequential",
        "Stage dependency graph is implicit; can't confirm if stages run sequentially or in parallel.",
        [
          ev.config(
            "charlie-release-staging/stages.yml",
            "stages:\n  - stage: Build\n  - stage: Test\n  - stage: Package\n  - stage: DeployStaging\n# dependsOn omitted — ADO defaults to sequential",
            "no explicit dependsOn clauses · sequential assumed",
          ),
        ],
      ),
      anomaly(
        "Auth & security",
        "variableGroups.charlie-secrets.leakageScan",
        "Secrets possibly in committed .env files",
        "matches: 2 (in charlie-legacy-tools)",
        "Pattern match found in 2 legacy files. Could be actual secrets or placeholder values; Champion to confirm.",
        [
          ev.file(
            "charlie-legacy-tools/scripts/.env.example",
            "SIGNING_TOKEN=[REDACTED — 64-char string matched]\nSERVICENOW_API_KEY=[REDACTED — looks live, not placeholder]",
            "secret-scan matches: 2 · regex: high-entropy · committed 2024-03-11",
          ),
          ev.file(
            "charlie-legacy-tools/.env.local",
            "[REDACTED in evidence — scan triggered on 'AZURE_STORAGE_KEY=...']",
            "secret-scan matches: 1 · committed 2023-08-02 · still present in HEAD",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.charlie-core.submoduleCrossOrg",
        "Cross-ADO-project submodule reference",
        "charlie-sdk → SharedLibs project",
        "Submodule points to a different ADO project. Cross-project references work in ADO but may need separate GH repo access grants.",
        [
          ev.config(
            "charlie-sdk/.gitmodules",
            '[submodule "core-dto"]\n  path = vendor/core-dto\n  url = https://dev.azure.com/contoso/SharedLibs/_git/core-dto',
            "target project: contoso/SharedLibs (distinct from contoso/CharlieCore)",
            "https://dev.azure.com/contoso/SharedLibs/_git/core-dto",
          ),
        ],
      ),
      anomaly(
        "Pipelines",
        "workflows.charlie-perf-nightly.agentPool",
        "charlie-perf-nightly uses specialized pool",
        "pool: contoso-perf-pool",
        "Pipeline requires perf-optimized runners. GH self-hosted runner pool for perf work doesn't currently exist.",
        [
          ev.config(
            "charlie-perf-nightly/azure-pipelines.yml:pool",
            "pool:\n  name: contoso-perf-pool\n  demands:\n    - Agent.OS -equals Linux\n    - machine.class -equals perf-xxl",
            "pool has 2 agents · machine class 'perf-xxl' = 32 vCPU / 128 GB / NVMe",
          ),
          ev.api(
            "GET /_apis/distributedtask/pools?poolName=contoso-perf-pool",
            '{\n  "value": [{\n    "id": 34,\n    "name": "contoso-perf-pool",\n    "size": 2,\n    "isHosted": false,\n    "poolType": "automation"\n  }]\n}',
            "self-hosted · 2 agents total",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.charlie-perf-tests.lfsScale",
        "charlie-perf-tests LFS scale",
        "18.4 GB LFS",
        "LFS volume is large enough that a naive migration will exceed rate limits. Requires pre-seeding strategy.",
        [
          ev.api(
            "GET /_apis/git/repositories/charlie-perf-tests/lfs",
            '{\n  "totalSize": 19756085248,\n  "objectCount": 4721,\n  "largestObjectBytes": 4194304000\n}',
            "total: 18.4 GB · 4,721 objects · largest single object: 3.9 GB (under GH 5 GB ceiling)",
          ),
          ev.url(
            "https://docs.github.com/en/migrations/using-github-enterprise-importer/migrating-from-azure-devops-to-github-enterprise-cloud/migrating-repositories-from-azure-devops-to-github-enterprise-cloud",
            "GEI migrates LFS pointer files but NOT the LFS object bytes. A separate LFS push is required post-migration.",
            "GitHub Docs",
          ),
        ],
      ),
      anomaly(
        "Customizations",
        "customizations.servicenow-gate.semanticDrift",
        "ServiceNow gate semantic mapping",
        "fidelity: partial",
        "Workflow_dispatch + webhook approach mimics the gate but loses ServiceNow's change-number linkage. Audit trail reduced.",
        [
          ev.config(
            "charlie-release-prod/gates.yml",
            "gates:\n  - task: ServiceNowApproval@1\n    inputs:\n      connectedServiceName: 'charlie-servicenow'\n      updateStatus: true\n      changeRequestNumber: '$(CHG_NUMBER)'",
            "gate publishes back to ServiceNow with CHG_NUMBER · GH webhook approach can POST but not update",
          ),
          ev.url(
            "https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch",
            "workflow_dispatch supports input payloads but has no first-class callback to external approval systems.",
            "GitHub Docs",
          ),
        ],
      ),
      anomaly(
        "Pipelines",
        "workflows.charlie-fedramp-audit.scanGaps",
        "FedRAMP audit may not cover all repos post-migration",
        "coverage: partial",
        "Audit pipeline targets specific paths in charlie-core. After migration, path structure may change; audit coverage could drift.",
        [
          ev.config(
            "charlie-fedramp-audit/audit-paths.yml",
            "paths:\n  - '/src/core/**'\n  - '/src/signing/**'\n  - '/config/fedramp/**'\n  - '/scripts/audit-*.ps1'",
            "audit scope ties to ADO repo path layout · any reorg on migration requires path spec rewrite",
          ),
          ev.log(
            "audit-run-2026-04-15.log",
            "[INFO] audit paths resolved: 4/4\n[INFO] repos scanned: 1 (charlie-core)\n[WARN] cross-repo dependencies not traversed (charlie-signer, charlie-sdk skipped)",
            "last audit run · 7 days ago · partial coverage warning present",
          ),
        ],
      ),
      anomaly(
        "Work items",
        "workItems.customFields.driftRisk",
        "Custom work item fields risk mapping drift",
        "fields: 14",
        "14 custom fields in ADO process template. GH Issues supports labels but not typed custom fields — mapping may lose fidelity.",
        [
          ev.api(
            "GET /_apis/wit/fields?$filter=referenceName startsWith 'Contoso.'",
            '[\n  { "referenceName": "Contoso.FedRAMPControl", "type": "String" },\n  { "referenceName": "Contoso.AcceptanceCriteria", "type": "HTML" },\n  { "referenceName": "Contoso.TestCase.RepeatCount", "type": "Integer" },\n  { "referenceName": "Contoso.Automation.TestCase", "type": "String" },\n  { "referenceName": "Contoso.Compliance.Owner", "type": "Identity" },\n  { "referenceName": "Contoso.ReleasePhase", "type": "PickList" },\n  { "referenceName": "Contoso.SigningRequired", "type": "Boolean" },\n  { "referenceName": "Contoso.DowntimeWindow", "type": "DateTime" },\n  { "referenceName": "Contoso.RegressionRisk", "type": "Double" },\n  { "referenceName": "Contoso.AuditLinked", "type": "PlainText" },\n  { "referenceName": "Contoso.JTBDCode", "type": "String" },\n  { "referenceName": "Contoso.CustomerImpact", "type": "PickList" },\n  { "referenceName": "Contoso.StagingApprover", "type": "Identity" },\n  { "referenceName": "Contoso.ProdApprover", "type": "Identity" }\n]',
            "ADO REST v7.1 · 14 custom fields · typed (String / HTML / Integer / PickList / Identity / Boolean / DateTime / Double)",
            "https://dev.azure.com/contoso/CharlieCore/_apis/wit/fields",
          ),
          ev.url(
            "https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues",
            "GitHub Issues supports labels and milestones but not typed custom fields. Typed fields map into Projects v2 custom fields, which exist per-project (not per-issue).",
            "GitHub Docs",
          ),
        ],
      ),
      anomaly(
        "Organization",
        "extensions.compliance-reporter.noDocumentation",
        "Compliance Reporter has no migration doc",
        "source: internal",
        "Internal extension with no public docs. Port requires reading source; not all of the extension's behavior is known.",
        [
          ev.file(
            "contoso-compliance-reporter/vss-extension.json",
            '{\n  "manifestVersion": 1,\n  "id": "contoso-compliance-reporter",\n  "publisher": "contoso-internal",\n  "version": "4.2.1",\n  "scopes": ["vso.work", "vso.code", "vso.release_execute"]\n}',
            "manifest captured · no README or CHANGELOG in the repo · extension publisher: contoso-internal",
          ),
          ev.url(
            "https://dev.azure.com/contoso/_settings/extensions/contoso-internal.contoso-compliance-reporter",
            "Extension admin page — no external docs link configured.",
          ),
        ],
      ),
      anomaly(
        "Auth & security",
        "serviceConnections.charlie-npm-internal.PATsharing",
        "NPM PAT shared across 2 pipelines",
        "shared: 2 pipelines",
        "Single PAT used by both sdk-publish workflows. Rotating will cause brief publish downtime for both.",
        [
          ev.api(
            "GET /_apis/distributedtask/variablegroups?groupName=charlie-npm-auth",
            '{\n  "name": "charlie-npm-auth",\n  "variables": {\n    "NPM_TOKEN": { "isSecret": true }\n  },\n  "consumedBy": [\n    "charlie-sdk-publish",\n    "charlie-sdk-cs-publish"\n  ]\n}',
            "single PAT · 2 consuming pipelines · rotation affects both simultaneously",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.charlie-infra.terraformStateDrift",
        "Terraform state drift risk at cutover",
        "state: eastus",
        "State lives in an Azure storage account. Cutover requires coordinating a terraform refresh or state migration.",
        [
          ev.config(
            "charlie-infra/main.tf:backend",
            'terraform {\n  backend "azurerm" {\n    resource_group_name  = "contoso-tfstate-rg"\n    storage_account_name = "contosotfstate"\n    container_name       = "charlie"\n    key                  = "charlie.tfstate"\n  }\n}',
            "state file: eastus · no state migration needed IF backend stays Azure · if moving to S3, full migration required",
          ),
        ],
      ),

      // Gap-fills from seed-validation (M1 realism pass): 13 documented pitfalls
      // sourced from public MS Learn / GitHub Docs / GitHub newsroom.

      anomaly(
        "Code & repos",
        "migration.orgRulesets.conflict",
        "Destination GitHub org has 'signed commits required' ruleset",
        "rulesets: strict",
        "Target Contoso-GH enterprise org enforces signed-commits on all repos. Charlie's historical commits are unsigned. The migration push will be rejected on the first ref-update unless the ruleset is temporarily exempted for the migration bot — a step teams frequently forget.",
      ),
      anomaly(
        "Code & repos",
        "repos.charlie-legacy-tools.mannequins",
        "Historical commits will attribute to unmapped 'mannequin' users",
        "mannequins: 3 contributors",
        "3 contributors on charlie-legacy-tools are former employees without GitHub identities. Their commits will render as mannequins in GH's blame/history views until reclaimed. Blame-based code search will underperform for those historical windows.",
      ),
      needsInput(
        "Artifacts & packages",
        "repos.charlie-sdk-cs.nugetConfigUrl",
        "nuget.config URL rewrite + credential swap",
        "charlie-sdk-cs has `pkgs.dev.azure.com/contoso/_packaging/charlie/nuget/v3/index.json` hard-coded in its nuget.config along with a PAT. Post-migration every consumer repo needs the URL rewritten to `nuget.pkg.github.com/contoso` and credentials swapped to a GH token. Champion to pick: commit a migration script, or coordinate with each consumer team.",
      ),
      needsInput(
        "Pipelines",
        "pipelines.templateLibrary.split",
        "ADO template library splits across composite actions and reusable workflows",
        "Charlie has a shared ADO template library at `contoso/pipelines-templates` referenced by multiple Charlie pipelines at both `steps:` and `jobs:` scope. GitHub Actions Importer emits `steps:` references as composite actions and `jobs:/stages:` references as reusable workflows — one template repo becomes two artifact types. Champion to decide: keep templates unified (single artifact, pick one) or accept the split.",
      ),
      anomaly(
        "Pipelines",
        "workflows.charlie-core-build.implicitCheckout",
        "Implicit checkout renders as unnamed GUID step",
        "step: guid-named",
        "ADO checks out source implicitly. GitHub Actions Importer emits this as a `uses: actions/checkout@...` step with a GUID-style name. Reviewers routinely miss renaming these, leaving workflow logs cluttered with GUIDs. Cosmetic but cumulative across 28 pipelines.",
      ),
      needsInput(
        "Pipelines",
        "workflows.charlie-release-prod.postDeployApprovals",
        "Post-deployment approvals do not migrate",
        "Actions Importer migrates pre-deployment approvals (partially) but does NOT migrate post-deployment approvals. charlie-release-prod currently has 2 post-deploy approvers gating promotion to Gov regions. Champion must manually recreate these as GitHub environment protection rules before the first prod deploy.",
      ),
      anomaly(
        "Pipelines",
        "environments.firstRunUnreviewedRisk",
        "Auto-created GitHub environments skip approvals on first run",
        "risk: first-run unreviewed deploy",
        "GitHub environments created on a workflow's first run have no approvals attached. If charlie-release-prod is migrated and fires before environments are pre-created-and-gated, the first post-migration prod deploy can ship without any approver review. Must pre-create + pre-configure all 4 prod environments.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.oidcRebuild",
        "Service connections must be rebuilt as OIDC federated credentials",
        "9 connections exist today. GitHub Actions Importer does NOT migrate service connections — they must be rebuilt. Best-practice path per GitHub Docs is to replace service-principal auth with OIDC federated identity (avoids long-lived secrets). Champion to approve: rebuild all 9 as OIDC, or stage (OIDC for Azure, keep PATs for NuGet short-term)?",
      ),
      needsInput(
        "Auth & security",
        "target.fedramp.gheComResidency",
        "FedRAMP High → must land on GHE.com, not github.com",
        "Charlie's FedRAMP High classification requires GitHub Enterprise Cloud with data residency (GHE.com tenant), not the commercial github.com. Some GH features lag GHE.com (actions, packages, marketplace). Champion to confirm: (a) enterprise has a GHE.com tenant, (b) all required GH Actions are available there, (c) legal/compliance has reviewed the tenant's controls.",
      ),
      needsInput(
        "Process / operational",
        "serviceHooks.migration",
        "ADO Service Hooks (Slack/Teams/ServiceNow) don't migrate",
        "Charlie has project-level Service Hooks wiring: #charlie-oncall Slack channel, Contoso Teams channel, ServiceNow incident creation. None of these migrate to GitHub automatically. Champion to catalog the hooks and assign owners to rewire as GitHub webhooks / GitHub Apps / workflow-dispatch integrations.",
      ),
      needsInput(
        "Observability & monitoring",
        "adoDashboards.replacement",
        "ADO Dashboards don't migrate — rebuild in Projects v2 / Insights",
        "Charlie's team page has 4 ADO dashboards (build health, release velocity, deploy-failure trend, FedRAMP audit status) that team members check daily. These do not migrate. Champion to decide: rebuild in GitHub Projects v2 with custom fields + views, use Insights, or accept reduced visibility.",
      ),
      needsInput(
        "Observability & monitoring",
        "pipelineRunHistory.fedRampRetention",
        "Pipeline run history doesn't migrate — FedRAMP retention needs ADO kept live",
        "GitHub Enterprise Importer does not migrate build/release run history, logs, or deployment audit trails. FedRAMP High requires 7-year retention of audit evidence. Champion must plan to keep the ADO project live read-only for the full retention window, or export + ingest run history to a separate audit system.",
      ),
      needsInput(
        "Extensions",
        "testPlans.noGhEquivalent",
        "Azure Test Plans have no GitHub equivalent",
        "Charlie's FedRAMP compliance suite uses ~40 manual test cases in Azure Test Plans for acceptance gates. GitHub has no native equivalent. Champion must pick: (a) keep ADO Test Plans live post-migration, (b) adopt a marketplace app like TestQuality, or (c) rewrite the manual cases as automated checks.",
      ),

      // Inferred findings (source=INFERRED, confidence=LOW — show as anomalies).
      // Each extends from a documented pitfall via adjacency, chain, or domain reasoning.
      // See docs/seed-validation.md "Inferred additions" for the reasoning chain.

      anomaly(
        "Code & repos",
        "migration.orgRulesets.squashMergeHistory",
        "Signed-commits ruleset may also reject historical squash-merge commits",
        "risk: adjacency to ruleset conflict",
        "INFERRED from 'org rulesets blocking migration push'. Historical squash-merges rewrite authorship; squash-commit authors won't match signed-commit identities either. Not independently documented but follows from how rulesets evaluate history.",
        [
          ev.log(
            "charlie-core/git-log-squash-sample",
            "commit 9f3a...1e\nAuthor: azure-devops-squash <noreply@dev.azure.com>\nDate:   2024-09-02\n    Squashed 7 commits from feature/auth-hardening",
            "3 of the last 20 squash-merges show 'azure-devops-squash' as author — unsigned + not a real identity",
          ),
        ],
      ),
      anomaly(
        "Artifacts & packages",
        "repos.charlie-sdk.npmrcRewrite",
        ".npmrc references ADO npm feed with same rewrite pattern",
        "feed: pkgs.dev.azure.com/contoso/_packaging/charlie-npm",
        "INFERRED from 'nuget.config URL rewrite'. Same team publishes an npm SDK; .npmrc has the same pkgs.dev.azure.com URL pattern that needs rewriting to npm.pkg.github.com. Adjacency: same rewrite applies to settings.xml for Maven projects if present.",
        [
          ev.config(
            "charlie-sdk/.npmrc",
            "@contoso:registry=https://pkgs.dev.azure.com/contoso/_packaging/charlie-npm/npm/registry/\n//pkgs.dev.azure.com/contoso/_packaging/charlie-npm/npm/registry/:always-auth=true\n//pkgs.dev.azure.com/contoso/_packaging/charlie-npm/npm/registry/:_authToken=${NPM_TOKEN}",
            "URL + token pattern identical to nuget.config · same rewrite approach applies",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "submodules.mannequinInheritance",
        "Submodule history inherits mannequin attribution if target repo is also migrated",
        "risk: cross-repo mannequin propagation",
        "INFERRED chain from 'mannequin users' + 'cross-ADO-project submodule'. charlie-sdk's submodule points to SharedLibs which is also in scope for migration — unmapped authors in the submodule will appear as mannequins across both repos' histories. Not independently documented.",
        [
          ev.config(
            "charlie-sdk/.gitmodules",
            '[submodule "core-dto"]\n  path = vendor/core-dto\n  url = https://dev.azure.com/contoso/SharedLibs/_git/core-dto',
            "target repo also in migration scope · check SharedLibs mannequin list",
          ),
        ],
      ),
      anomaly(
        "Pipelines",
        "templates.doubleBillingRisk",
        "Template split into composite + reusable may double workflow-minute billing",
        "risk: billing chain",
        "INFERRED from 'templates split'. Pipelines currently call the template library twice (once at steps scope, once at jobs scope). Post-split, that becomes a composite-action call inside a reusable-workflow call — GitHub Actions bills each reusable-workflow invocation as its own run. Not independently documented for this specific pattern but follows from published billing semantics.",
        [
          ev.config(
            "charlie-core/azure-pipelines.yml:template-refs",
            "# steps-scope reference (will become composite action):\n- template: templates/steps/restore-cache.yml@contoso-templates\n\n# jobs-scope reference (will become reusable workflow):\njobs:\n- template: templates/jobs/run-scans.yml@contoso-templates",
            "both references target same contoso-templates repo · importer will fragment",
          ),
          ev.url(
            "https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions",
            "GitHub Actions bills per reusable-workflow invocation; composite actions run inline.",
            "GitHub Docs",
          ),
        ],
      ),
      anomaly(
        "Auth & security",
        "target.fedramp.actionsMarketplaceRestrictions",
        "GHE.com (FedRAMP) tenants may restrict 3rd-party Actions marketplace",
        "impact: 6 marketplace actions used",
        "INFERRED domain reasoning from 'FedRAMP → GHE.com' + enterprise-tenant action allow-lists. Charlie's current workflows call ~6 marketplace actions (SonarCloud, Snyk, Veracode, etc.). GHE.com enterprise admins commonly restrict which publishers are allowed. Not independently documented for Charlie's specific extensions but a standard GHE.com posture.",
        [
          ev.config(
            "charlie-*/workflow-action-usage.aggregate",
            "SonarSource/sonarcloud-github-action@v2.0.0\nsnyk/actions/node@master\nveracode/veracode-flaws-to-issues@v2.2.21\nazure/login@v1\nazure/webapps-deploy@v2\nmicrosoft/security-devops-action@latest",
            "6 distinct marketplace publishers · 4 non-Microsoft publishers",
          ),
          ev.url(
            "https://government.github.com/fedramp/",
            "GitHub Enterprise Cloud FedRAMP Moderate lives on a separate GHE.com tenant with its own allow-list of Actions publishers.",
            "GitHub Government",
          ),
        ],
      ),
    ],
  };
}
