import { jtbdOverridesFor } from "./jtbd-scoping";

import {
  adoProject,
  anomaly,
  customization,
  daysAgo,
  daysFromNow,
  ev,
  extension,
  hoursAgo,
  allJtbds,
  member,
  needsInput,
  releaseDefinition,
  repo,
  serviceConnection,
  workflow,
  type CohortShape,
} from "./_helpers";

export function deltaConfig(orgId: string): CohortShape {
  return {
    orgId,
    name: "Delta Data Platform",
    slug: "delta",
    tagline: "The heavyweight",
    description:
      "Large Scala-heavy data platform: a 98 GB monorepo, a 38 GB LFS-tracked data repo, submodules pointing into other ADO projects, and canary deployments coordinated across four regions. Migration mid-flight; most decisions made, execution risk remains.",
    cohort: "DELTA",
    wave: 2,
    migrationState: "IN_PROGRESS",
    engineerCount: 14,
    tier: "TIER_1",
    securityClassification: "FedRAMP High",
    healthStatus: "ON_TRACK",
    effortEstimateLowWeeks: 30,
    effortEstimateHighWeeks: 40,
    effortConfidence: "MEDIUM",
    effortProgressWeeks: 20,
    targetCutoverAt: daysFromNow(56),
    slackWeeks: 0,
    workItemsActive: 418,
    workItemsClosed90d: 1124,
    buildArtifactCount: 982,
    wikiPageCount: 184,
    championEmail: "elena.volkov@contoso.com",
    members: [
      member(
        "Elena Volkov",
        "elena.volkov@contoso.com",
        "Engineering Director",
      ),
      member("Felix Zhou", "felix.zhou@contoso.com", "Principal Engineer"),
      member("Gina Anderson", "gina.anderson@contoso.com", "Staff Engineer"),
      member("Hiro Tanaka", "hiro.tanaka@contoso.com", "Senior Engineer"),
      member("Iris Patel", "iris.patel@contoso.com", "Senior Engineer"),
      member(
        "Jamal Washington",
        "jamal.washington@contoso.com",
        "Senior Engineer",
      ),
      member("Kenji Nakamura", "kenji.nakamura@contoso.com", "Senior SRE"),
      member("Lila Garcia", "lila.garcia@contoso.com", "Engineer"),
      member("Marcus Chen", "marcus.chen@contoso.com", "Engineer"),
      member(
        "Nadia Sokolov",
        "nadia.sokolov@contoso.com",
        "Engineering Manager",
      ),
      member("Oliver Schmidt", "oliver.schmidt@contoso.com", "Staff Engineer"),
      member("Priya Menon", "priya.menon@contoso.com", "Engineer"),
      member("Quinn O'Brien", "quinn.obrien@contoso.com", "Senior Engineer"),
      member("Ravi Deshmukh", "ravi.deshmukh@contoso.com", "Engineer"),
    ],
    codebase: {
      primaryLang: "Scala",
      usesLfs: true,
      totalSizeGb: 152.8,
    },
    repos: [
      repo("delta-monorepo", {
        sizeGb: 98.0,
        loc: 1240000,
        languageBreakdown: {
          Scala: 58,
          Java: 18,
          Python: 10,
          YAML: 6,
          SQL: 4,
          Markdown: 4,
        },
        contributorCount: 14,
        hasWiki: true,
        wikiPageCount: 92,
        commits90d: 2148,
        primaryOwner: "elena.volkov@contoso.com",
        lastCommitAt: hoursAgo(2),
        hasSubmodules: true,
        submoduleUrls: [
          "https://dev.azure.com/contoso/SharedLibs/_git/core-dto",
          "https://dev.azure.com/contoso/SharedLibs/_git/proto-defs",
        ],
      }),
      repo("delta-data-lfs", {
        sizeGb: 38.0,
        loc: 6800,
        languageBreakdown: { Binary: 84, JSON: 10, Markdown: 6 },
        contributorCount: 8,
        hasWiki: true,
        wikiPageCount: 12,
        commits90d: 182,
        primaryOwner: "felix.zhou@contoso.com",
        lastCommitAt: daysAgo(1),
        hasLfs: true,
        lfsSizeGb: 34.2,
      }),
      repo("delta-shared", {
        sizeGb: 4.2,
        loc: 82000,
        languageBreakdown: { Scala: 72, Java: 18, YAML: 6, Markdown: 4 },
        contributorCount: 12,
        hasWiki: true,
        wikiPageCount: 28,
        commits90d: 412,
        primaryOwner: "gina.anderson@contoso.com",
        lastCommitAt: hoursAgo(11),
      }),
      repo("delta-services", {
        sizeGb: 2.6,
        loc: 54000,
        languageBreakdown: { Scala: 68, Java: 22, YAML: 8, Markdown: 2 },
        contributorCount: 9,
        hasWiki: true,
        wikiPageCount: 18,
        commits90d: 298,
        primaryOwner: "hiro.tanaka@contoso.com",
        lastCommitAt: hoursAgo(6),
      }),
      repo("delta-ingestion", {
        sizeGb: 1.8,
        loc: 42000,
        languageBreakdown: { Scala: 78, Python: 14, YAML: 8 },
        contributorCount: 7,
        hasWiki: true,
        wikiPageCount: 14,
        commits90d: 224,
        primaryOwner: "iris.patel@contoso.com",
        lastCommitAt: hoursAgo(14),
      }),
      repo("delta-etl", {
        sizeGb: 1.6,
        loc: 38000,
        languageBreakdown: { Scala: 82, YAML: 10, Markdown: 8 },
        contributorCount: 6,
        hasWiki: true,
        wikiPageCount: 10,
        commits90d: 168,
        primaryOwner: "jamal.washington@contoso.com",
        lastCommitAt: daysAgo(1),
      }),
      repo("delta-query-engine", {
        sizeGb: 1.4,
        loc: 48000,
        languageBreakdown: { Scala: 84, Java: 12, YAML: 4 },
        contributorCount: 5,
        hasWiki: true,
        wikiPageCount: 16,
        commits90d: 142,
        primaryOwner: "oliver.schmidt@contoso.com",
        lastCommitAt: daysAgo(2),
      }),
      repo("delta-ml-models", {
        sizeGb: 2.8,
        loc: 28000,
        languageBreakdown: { Python: 72, Scala: 18, YAML: 10 },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 22,
        commits90d: 88,
        primaryOwner: "priya.menon@contoso.com",
        lastCommitAt: daysAgo(3),
      }),
      repo("delta-infra", {
        sizeGb: 0.9,
        loc: 22000,
        languageBreakdown: {
          "HCL (Terraform)": 68,
          YAML: 18,
          Shell: 12,
          Markdown: 2,
        },
        contributorCount: 5,
        hasWiki: true,
        wikiPageCount: 20,
        commits90d: 128,
        primaryOwner: "kenji.nakamura@contoso.com",
        lastCommitAt: hoursAgo(9),
      }),
      repo("delta-k8s-operators", {
        sizeGb: 0.6,
        loc: 18000,
        languageBreakdown: { Go: 82, YAML: 12, Markdown: 6 },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 8,
        commits90d: 64,
        primaryOwner: "kenji.nakamura@contoso.com",
        lastCommitAt: daysAgo(4),
      }),
      repo("delta-dashboards", {
        sizeGb: 0.7,
        loc: 24000,
        languageBreakdown: {
          TypeScript: 68,
          CSS: 14,
          HTML: 8,
          YAML: 6,
          Markdown: 4,
        },
        contributorCount: 6,
        hasWiki: false,
        commits90d: 142,
        primaryOwner: "lila.garcia@contoso.com",
        lastCommitAt: daysAgo(1),
      }),
      repo("delta-cli", {
        sizeGb: 0.4,
        loc: 14000,
        languageBreakdown: { Scala: 76, YAML: 14, Markdown: 10 },
        contributorCount: 4,
        hasWiki: false,
        commits90d: 58,
        primaryOwner: "marcus.chen@contoso.com",
        lastCommitAt: daysAgo(6),
      }),
      repo("delta-docs", {
        sizeGb: 0.5,
        loc: 18400,
        languageBreakdown: { Markdown: 92, YAML: 6, CSS: 2 },
        contributorCount: 12,
        hasWiki: false,
        commits90d: 184,
        primaryOwner: "nadia.sokolov@contoso.com",
        lastCommitAt: hoursAgo(16),
      }),
      repo("delta-e2e", {
        sizeGb: 1.2,
        loc: 32000,
        languageBreakdown: { Scala: 62, Python: 22, YAML: 16 },
        contributorCount: 8,
        hasWiki: true,
        wikiPageCount: 6,
        commits90d: 142,
        primaryOwner: "quinn.obrien@contoso.com",
        lastCommitAt: daysAgo(2),
      }),
      repo("delta-schemas", {
        sizeGb: 0.3,
        loc: 12000,
        languageBreakdown: { Protobuf: 78, Avro: 14, Markdown: 8 },
        contributorCount: 8,
        hasWiki: true,
        wikiPageCount: 14,
        commits90d: 68,
        primaryOwner: "oliver.schmidt@contoso.com",
        lastCommitAt: daysAgo(3),
      }),
      repo("delta-benchmarks", {
        sizeGb: 1.1,
        loc: 18000,
        languageBreakdown: { Scala: 62, Python: 22, JSON: 16 },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 8,
        commits90d: 42,
        primaryOwner: "felix.zhou@contoso.com",
        lastCommitAt: daysAgo(9),
      }),
      repo("delta-connectors", {
        sizeGb: 0.8,
        loc: 28000,
        languageBreakdown: { Scala: 78, Java: 14, YAML: 8 },
        contributorCount: 5,
        hasWiki: true,
        wikiPageCount: 12,
        commits90d: 92,
        primaryOwner: "hiro.tanaka@contoso.com",
        lastCommitAt: daysAgo(4),
      }),
      repo("delta-airflow-dags", {
        sizeGb: 0.3,
        loc: 8800,
        languageBreakdown: { Python: 88, YAML: 8, Markdown: 4 },
        contributorCount: 6,
        hasWiki: false,
        commits90d: 128,
        primaryOwner: "ravi.deshmukh@contoso.com",
        lastCommitAt: hoursAgo(20),
      }),
      repo("delta-examples", {
        sizeGb: 0.4,
        loc: 9200,
        languageBreakdown: { Scala: 48, Python: 32, Jupyter: 16, Markdown: 4 },
        contributorCount: 7,
        hasWiki: false,
        commits90d: 38,
        primaryOwner: "priya.menon@contoso.com",
        lastCommitAt: daysAgo(8),
      }),
      repo("delta-legacy-etl", {
        sizeGb: 0.8,
        loc: 22000,
        languageBreakdown: { Scala: 58, Java: 32, XML: 10 },
        contributorCount: 2,
        hasWiki: false,
        commits90d: 4,
        defaultBranch: "master",
        primaryOwner: "jamal.washington@contoso.com",
        lastCommitAt: daysAgo(78),
        branchProtected: false,
      }),
      repo("delta-proto-gen", {
        sizeGb: 0.2,
        loc: 6400,
        languageBreakdown: { Shell: 58, Makefile: 22, Python: 20 },
        contributorCount: 3,
        hasWiki: false,
        commits90d: 12,
        primaryOwner: "oliver.schmidt@contoso.com",
        lastCommitAt: daysAgo(14),
      }),
      repo("delta-retired-snapshot", {
        sizeGb: 0.2,
        loc: 4800,
        languageBreakdown: { Scala: 62, Markdown: 38 },
        contributorCount: 1,
        hasWiki: false,
        commits90d: 0,
        isArchived: true,
        primaryOwner: "felix.zhou@contoso.com",
        lastCommitAt: daysAgo(212),
        branchProtected: false,
      }),
    ],
    workflows: [
      workflow("delta-monorepo-build", "BUILD", {
        averageDurationMin: 52,
        triggersPerWeek: 142,
        failsLast30d: 18,
        stageCount: 5,
        usesVariableGroups: true,
        runnerType: "SELF_HOSTED",
        agentPool: "delta-build-pool",
      }),
      workflow("delta-monorepo-test", "TEST", {
        averageDurationMin: 68,
        triggersPerWeek: 142,
        failsLast30d: 22,
        stageCount: 4,
      }),
      workflow("delta-shared-build", "BUILD", {
        averageDurationMin: 22,
        triggersPerWeek: 98,
        failsLast30d: 6,
        stageCount: 3,
      }),
      workflow("delta-services-build", "BUILD", {
        averageDurationMin: 18,
        triggersPerWeek: 112,
        failsLast30d: 8,
        stageCount: 3,
      }),
      workflow("delta-ingestion-build", "BUILD", {
        averageDurationMin: 14,
        triggersPerWeek: 68,
        failsLast30d: 4,
      }),
      workflow("delta-etl-build", "BUILD", {
        averageDurationMin: 12,
        triggersPerWeek: 54,
        failsLast30d: 3,
      }),
      workflow("delta-query-engine-build", "BUILD", {
        averageDurationMin: 16,
        triggersPerWeek: 48,
        failsLast30d: 2,
      }),
      workflow("delta-ml-models-build", "BUILD", {
        averageDurationMin: 28,
        triggersPerWeek: 22,
        failsLast30d: 4,
        usesVariableGroups: true,
      }),
      workflow("delta-k8s-operators-build", "BUILD", {
        averageDurationMin: 11,
        triggersPerWeek: 34,
        failsLast30d: 1,
      }),
      workflow("delta-dashboards-build", "BUILD", {
        averageDurationMin: 8,
        triggersPerWeek: 62,
        failsLast30d: 2,
      }),
      workflow("delta-cli-build", "BUILD", {
        averageDurationMin: 6,
        triggersPerWeek: 18,
        failsLast30d: 0,
      }),
      workflow("delta-connectors-build", "BUILD", {
        averageDurationMin: 14,
        triggersPerWeek: 42,
        failsLast30d: 3,
      }),
      workflow("delta-schemas-compile", "BUILD", {
        averageDurationMin: 4,
        triggersPerWeek: 28,
        failsLast30d: 0,
      }),
      workflow("delta-infra-plan", "BUILD", {
        averageDurationMin: 9,
        triggersPerWeek: 38,
        failsLast30d: 2,
        usesVariableGroups: true,
      }),
      workflow("delta-proto-gen", "BUILD", {
        averageDurationMin: 3,
        triggersPerWeek: 14,
        failsLast30d: 0,
      }),
      workflow("delta-lfs-sync", "OTHER", {
        averageDurationMin: 42,
        triggersPerWeek: 7,
        failsLast30d: 2,
        runnerType: "SELF_HOSTED",
        agentPool: "delta-lfs-pool",
      }),
      workflow("delta-benchmarks-nightly", "TEST", {
        averageDurationMin: 184,
        triggersPerWeek: 7,
        failsLast30d: 1,
        runnerType: "SELF_HOSTED",
        agentPool: "delta-perf-pool",
      }),
      workflow("delta-e2e-nightly", "TEST", {
        averageDurationMin: 142,
        triggersPerWeek: 7,
        failsLast30d: 3,
        stageCount: 4,
        usesVariableGroups: true,
      }),
      workflow("delta-integration-smoke", "TEST", {
        averageDurationMin: 32,
        triggersPerWeek: 68,
        failsLast30d: 8,
        stageCount: 2,
      }),
      workflow("delta-e2e-prerelease", "TEST", {
        averageDurationMin: 218,
        triggersPerWeek: 3,
        failsLast30d: 2,
        stageCount: 5,
        usesVariableGroups: true,
      }),
      workflow("delta-release-trunk", "RELEASE", {
        stageCount: 6,
        averageDurationMin: 38,
        triggersPerWeek: 8,
        failsLast30d: 2,
        usesVariableGroups: true,
      }),
      workflow("delta-release-canary", "RELEASE", {
        stageCount: 4,
        averageDurationMin: 28,
        triggersPerWeek: 14,
        failsLast30d: 4,
        usesVariableGroups: true,
      }),
      workflow("delta-deploy-canary", "DEPLOY", {
        stageCount: 5,
        averageDurationMin: 42,
        triggersPerWeek: 12,
        failsLast30d: 2,
        usesVariableGroups: true,
      }),
      workflow("delta-deploy-eastus", "DEPLOY", {
        stageCount: 3,
        averageDurationMin: 24,
        triggersPerWeek: 8,
        failsLast30d: 1,
        usesVariableGroups: true,
      }),
      workflow("delta-deploy-westus2", "DEPLOY", {
        stageCount: 3,
        averageDurationMin: 24,
        triggersPerWeek: 8,
        failsLast30d: 1,
        usesVariableGroups: true,
      }),
      workflow("delta-deploy-eu", "DEPLOY", {
        stageCount: 3,
        averageDurationMin: 26,
        triggersPerWeek: 6,
        failsLast30d: 1,
        usesVariableGroups: true,
      }),
      workflow("delta-deploy-asia", "DEPLOY", {
        stageCount: 3,
        averageDurationMin: 28,
        triggersPerWeek: 6,
        failsLast30d: 2,
        usesVariableGroups: true,
      }),
      workflow("delta-infra-apply", "DEPLOY", {
        stageCount: 4,
        averageDurationMin: 18,
        triggersPerWeek: 8,
        failsLast30d: 1,
        usesVariableGroups: true,
      }),
      workflow("delta-dashboards-deploy", "DEPLOY", {
        averageDurationMin: 6,
        triggersPerWeek: 12,
        failsLast30d: 0,
      }),
      workflow("delta-airflow-deploy", "DEPLOY", {
        averageDurationMin: 8,
        triggersPerWeek: 14,
        failsLast30d: 1,
      }),
      workflow("delta-ml-model-publish", "DEPLOY", {
        averageDurationMin: 14,
        triggersPerWeek: 4,
        failsLast30d: 0,
        usesVariableGroups: true,
      }),
      workflow("delta-docs-deploy", "DEPLOY", {
        averageDurationMin: 4,
        triggersPerWeek: 18,
        failsLast30d: 0,
      }),
      workflow("delta-security-scan", "TEST", {
        averageDurationMin: 38,
        triggersPerWeek: 14,
        failsLast30d: 2,
      }),
      workflow("delta-dependency-scan", "TEST", {
        averageDurationMin: 18,
        triggersPerWeek: 7,
        failsLast30d: 0,
      }),
      workflow("delta-sast-scan", "TEST", {
        averageDurationMin: 52,
        triggersPerWeek: 7,
        failsLast30d: 1,
      }),
      workflow("delta-fedramp-audit", "TEST", {
        averageDurationMin: 68,
        triggersPerWeek: 1,
        failsLast30d: 0,
        usesVariableGroups: true,
      }),
      workflow("delta-compliance-check", "TEST", {
        averageDurationMin: 22,
        triggersPerWeek: 14,
        failsLast30d: 0,
      }),
      workflow("delta-licence-scan", "TEST", {
        averageDurationMin: 12,
        triggersPerWeek: 7,
        failsLast30d: 0,
      }),
      workflow("delta-deprecation-check", "TEST", {
        averageDurationMin: 8,
        triggersPerWeek: 7,
        failsLast30d: 0,
      }),
      workflow("delta-legacy-etl-build", "BUILD", {
        isClassic: true,
        averageDurationMin: 12,
        triggersPerWeek: 1,
        failsLast30d: 0,
        deprecatedTasks: ["AzureFileCopy@3"],
      }),
      workflow("delta-proto-publish", "DEPLOY", {
        averageDurationMin: 5,
        triggersPerWeek: 6,
        failsLast30d: 0,
      }),
      workflow("delta-k8s-deploy", "DEPLOY", {
        stageCount: 3,
        averageDurationMin: 16,
        triggersPerWeek: 14,
        failsLast30d: 2,
        usesVariableGroups: true,
      }),
    ],
    jtbds: allJtbds(jtbdOverridesFor("DELTA")),
    // Delta = "the heavyweight" — large monorepo, complex deploy graph.
    // Catalog mix biased toward Pipelines + Repos.
    customizations: [
      customization("C09", { status: "AGENT_HANDLED" }),
      customization("C13", { status: "AGENT_HANDLED" }),
      customization("C14", { status: "AGENT_HANDLED" }),
      customization("C22", { status: "NEEDS_HUMAN" }),
      customization("C29", { status: "NEEDS_HUMAN" }),
      customization("C35", {
        name: "LFS batching script",
        description:
          "LFS batching script for delta-data-lfs — pushes LFS objects in chunks to avoid rate-limiting.",
        status: "AGENT_HANDLED",
      }),
      customization("C34", {
        name: "Canary deploy orchestrator",
        description:
          "Canary deploy orchestrator coordinates staged rollouts across 4 services.",
        status: "AGENT_HANDLED",
      }),
      customization("C35", {
        name: "Monorepo change detection",
        description:
          "Monorepo change detection script — selective rebuild based on changed paths.",
        status: "AGENT_HANDLED",
      }),
      customization("C34", {
        name: "Cross-region deploy dependency graph",
        description:
          "Cross-region deploy dependency graph — ordering enforced via deployment environments.",
        status: "NEEDS_HUMAN",
      }),
      customization("C31", {
        name: "Schema compatibility gate",
        description:
          "Schema compatibility gate — blocks canary if proto changes break consumer.",
        status: "NEEDS_HUMAN",
      }),
    ],
    risks: [
      {
        title: "LFS migration duration estimated >24h",
        detail:
          "38 GB of LFS-tracked data across 200k+ objects. GitHub LFS migration will take an extended window; coordination with release cadence required.",
        confidence: "HIGH",
        mitigation:
          "Schedule cut-over during weekend release freeze. LFS pre-sync tool validated against 10% sample.",
        status: "MITIGATED",
        category: "Code & repos",
      },
      {
        title: "Submodule resolution after cut-over",
        detail:
          "delta-monorepo contains submodules pointing to internal ADO URLs. These references must be rewritten to GitHub URLs during migration.",
        confidence: "MEDIUM",
        mitigation: null,
        status: "OPEN",
        category: "Code & repos",
      },
      {
        title: "Canary deploy ordering is implicit",
        detail:
          "Canary stages rely on ADO-specific deployment-job ordering. Needs explicit modeling in GH environments.",
        confidence: "MEDIUM",
        mitigation: null,
        status: "OPEN",
        category: "Pipelines",
      },
    ],
    ownership: {
      primaryOwnerEmail: "elena.volkov@contoso.com",
      onCallGroup: "#delta-oncall",
      escalationContact: "felix.zhou@contoso.com",
    },
    adoProjects: [
      adoProject("DeltaPlatform", {
        description: "Core data platform",
        repoCount: 10,
        pipelineCount: 24,
        boardCount: 4,
      }),
      adoProject("DeltaML", {
        description: "ML models + training",
        repoCount: 4,
        pipelineCount: 8,
        boardCount: 2,
      }),
      adoProject("DeltaInfra", {
        description: "Infrastructure + K8s operators",
        repoCount: 5,
        pipelineCount: 8,
        boardCount: 2,
      }),
      adoProject("DeltaArchive", {
        description: "Archived / low-activity repos",
        visibility: "private",
        repoCount: 3,
        pipelineCount: 2,
        boardCount: 1,
      }),
    ],
    serviceConnections: [
      serviceConnection("delta-azure-prod-eastus", "AZURE_RM", {
        targetService: "Azure RM · delta-prod-eastus",
        authMethod: "OIDC",
        usedByCount: 6,
        lastRotatedAt: daysAgo(14),
      }),
      serviceConnection("delta-azure-prod-westus2", "AZURE_RM", {
        targetService: "Azure RM · delta-prod-westus2",
        authMethod: "OIDC",
        usedByCount: 6,
        lastRotatedAt: daysAgo(14),
      }),
      serviceConnection("delta-azure-prod-eu", "AZURE_RM", {
        targetService: "Azure RM · delta-prod-weu",
        authMethod: "OIDC",
        usedByCount: 5,
        lastRotatedAt: daysAgo(14),
      }),
      serviceConnection("delta-azure-prod-asia", "AZURE_RM", {
        targetService: "Azure RM · delta-prod-eastasia",
        authMethod: "OIDC",
        usedByCount: 5,
        lastRotatedAt: daysAgo(14),
      }),
      serviceConnection("delta-azure-staging", "AZURE_RM", {
        targetService: "Azure RM · delta-staging",
        authMethod: "service-principal",
        usedByCount: 3,
        lastRotatedAt: daysAgo(68),
      }),
      serviceConnection("delta-acr", "AZURE_CONTAINER_REGISTRY", {
        targetService: "contosodeltaacr.azurecr.io",
        authMethod: "managed-identity",
        usedByCount: 8,
        lastRotatedAt: daysAgo(14),
      }),
      serviceConnection("delta-k8s-prod", "KUBERNETES", {
        targetService: "aks-delta-prod",
        authMethod: "service-account",
        usedByCount: 4,
        lastRotatedAt: daysAgo(22),
      }),
      serviceConnection("delta-nuget-internal", "NUGET_FEED", {
        targetService: "Contoso internal NuGet",
        authMethod: "PAT",
        usedByCount: 3,
        lastRotatedAt: daysAgo(88),
      }),
      serviceConnection("delta-sonar", "GENERIC", {
        targetService: "SonarCloud",
        authMethod: "PAT",
        usedByCount: 3,
        lastRotatedAt: daysAgo(64),
      }),
      serviceConnection("delta-snyk", "GENERIC", {
        targetService: "Snyk org: contoso-delta",
        authMethod: "PAT",
        usedByCount: 2,
        lastRotatedAt: daysAgo(48),
      }),
      serviceConnection("delta-datadog", "GENERIC", {
        targetService: "Datadog EU",
        authMethod: "PAT",
        usedByCount: 4,
        lastRotatedAt: daysAgo(36),
      }),
    ],
    releaseDefinitions: [
      releaseDefinition("delta-trunk-release", {
        stages: 6,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["azure-monitor", "manual-approval"],
        deployTargets: ["eastus", "westus2", "weu", "eastasia"],
        lastRunAt: daysAgo(2),
      }),
      releaseDefinition("delta-canary-release", {
        stages: 4,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["azure-monitor"],
        deployTargets: ["eastus-canary"],
        lastRunAt: daysAgo(1),
      }),
      releaseDefinition("delta-schemas-release", {
        stages: 2,
        isClassic: true,
        hasManualGates: false,
        gateTypes: [],
        deployTargets: ["schema-registry"],
        lastRunAt: daysAgo(5),
      }),
      releaseDefinition("delta-ml-release", {
        stages: 3,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["manual-approval"],
        deployTargets: ["ml-inference-prod"],
        lastRunAt: daysAgo(6),
      }),
      releaseDefinition("delta-legacy-release", {
        stages: 2,
        isClassic: true,
        hasManualGates: false,
        gateTypes: [],
        deployTargets: ["legacy-etl"],
        lastRunAt: daysAgo(92),
      }),
    ],
    extensions: [
      extension("Azure Artifacts", "Microsoft", "artifacts", {
        hasGitHubEquivalent: true,
      }),
      extension("SonarCloud", "SonarSource", "code-quality", {
        hasGitHubEquivalent: true,
      }),
      extension("Snyk Security", "Snyk", "security", {
        hasGitHubEquivalent: true,
      }),
      extension("Datadog CI Visibility", "Datadog", "observability", {
        hasGitHubEquivalent: true,
        notes:
          "Datadog CI Visibility has a GH integration; reconfigure post-migration.",
      }),
      extension("Terraform Cloud", "HashiCorp", "infra", {
        hasGitHubEquivalent: true,
      }),
      extension("Schema Registry Sync", "Contoso Internal", "integration", {
        hasGitHubEquivalent: false,
        notes: "Internal extension — reimplementation needed.",
      }),
      extension("LFS Batching Tool", "Contoso Internal", "tooling", {
        hasGitHubEquivalent: false,
        notes: "Internal tool; reusable workflow in-flight.",
      }),
      extension("Canary Orchestrator", "Contoso Internal", "release-tooling", {
        hasGitHubEquivalent: false,
        notes: "Internal tool; GH Action in progress.",
      }),
    ],
    agentRun: {
      startedAt: hoursAgo(14),
      completedAt: new Date(hoursAgo(14).getTime() + 312_000),
      durationMs: 312_000,
    },
    curatedFindings: [
      // Needs-input (38)
      needsInput(
        "Code & repos",
        "repos.delta-monorepo.submoduleRewrite",
        "Submodule URL rewrite rules",
        "Submodules reference dev.azure.com/contoso URLs. Migration plan needs Champion-approved URL rewrite rules.",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-data-lfs.migrationStrategy",
        "LFS migration strategy",
        "38 GB LFS. Agent can propose git-lfs-migrate vs fresh LFS tracking; Champion must choose.",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-lfs-sync.schedule",
        "LFS sync schedule post-migration",
        "Current schedule is ADO-cron. GH Actions cron has subtle differences (UTC, 5-minute minimum). Champion to confirm.",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-monorepo-build.changeDetection",
        "Change detection approach",
        "Monorepo uses a custom script for path-based selective rebuild. Migrate to GH Actions path filters or reuse custom script?",
      ),
      needsInput(
        "Pipelines",
        "deployments.canaryOrdering",
        "Canary → prod deployment ordering",
        "Current ordering is implicit in ADO pipeline deployment-job dependencies. Model explicitly in GH environments?",
      ),
      needsInput(
        "Pipelines",
        "deployments.regionStaggering",
        "Region deploy staggering",
        "Current: eastus → westus2 → eu → asia with 30-min gaps. Preserve in GH environment protection rules?",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.delta-nuget-internal.rotation",
        "NuGet PAT rotation",
        "PAT is 88 days old. Rotate before cutover?",
      ),
      needsInput(
        "Auth & security",
        "secrets.datadog.migration",
        "Datadog API key migration",
        "Datadog keys stored in variable groups. Migrate to GH environment secrets or federate via Datadog GH App?",
      ),
      needsInput(
        "Organization",
        "extensions.schema-registry-sync.port",
        "Schema Registry Sync extension replacement",
        "Internal extension, no GH equivalent. Owner + timeline for reusable workflow rebuild?",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-e2e-prerelease.environments",
        "Pre-release E2E environment mapping",
        "5-stage pipeline references env-specific test data. Champion to enumerate GH environment list.",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-legacy-etl.migrationDecision",
        "delta-legacy-etl migration decision",
        "master branch, 78 days since commit, 4 commits in 90d. Archive, migrate as-is, or consolidate into delta-etl?",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-retired-snapshot.archive",
        "delta-retired-snapshot archive",
        "Already archived; confirm we skip migration.",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-benchmarks-nightly.agentPool",
        "Benchmarks runner pool",
        "Self-hosted perf pool. Network team provisioning GH equivalent — Champion to confirm timeline.",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-legacy-etl-build.retirement",
        "Retire delta-legacy-etl-build?",
        "1 run/week, no recent failures. Legacy; retire or keep?",
      ),
      needsInput(
        "JTBDs",
        "jtbds.lfs-sync.approach",
        "LFS sync JTBD future state",
        "Currently MIXED approach flagged. Champion to finalize: full GH LFS, or keep Azure Blob as cold tier?",
      ),
      needsInput(
        "Work items",
        "workItems.historyDepth",
        "Work item history depth",
        "1,124 closed items in 90d; total history much larger. Migrate all or last 180d?",
      ),
      needsInput(
        "Auth & security",
        "variableGroups.delta-secrets.count",
        "Variable group consolidation",
        "14 variable groups across pipelines. Flatten to GH environment secrets or create matching environment-scoped groups?",
      ),
      needsInput(
        "Ownership",
        "ownership.tierEscalation",
        "Tier 1 escalation chain",
        "Elena → Felix → ?. Third-level escalation not captured.",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-k8s-operators.deploymentAutomation",
        "K8s operator deploy path",
        "Operators deploy via delta-k8s-deploy workflow with manual steps. Formalize in GH environments or keep manual-first-deploy?",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-airflow-deploy.scheduler",
        "Airflow scheduler integration",
        "DAGs deployed to managed Airflow. Integration secrets TBD.",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-ml-model-publish.signing",
        "ML model signing requirement",
        "FedRAMP classification — does model publishing require signing? Champion to confirm with compliance.",
      ),
      needsInput(
        "Organization",
        "adoProjects.delta-archive.migration",
        "DeltaArchive project migration",
        "Low-activity project. Migrate as-is, consolidate with DeltaPlatform, or leave behind?",
      ),
      needsInput(
        "Auth & security",
        "secrets.nuget-rotation-cadence",
        "NuGet credential rotation cadence",
        "Current cadence inferred from one rotation point. Champion to confirm policy.",
      ),
      needsInput(
        "Customizations",
        "customizations.canary-orchestrator.handoff",
        "Canary orchestrator rewrite handoff",
        "Internal tool being rewritten as GH Action. Who owns? Status?",
      ),
      needsInput(
        "Customizations",
        "customizations.schema-compat-gate.approach",
        "Schema compatibility gate",
        "Blocks canary on proto-breaking changes. Reimplement as reusable workflow or keep as external check?",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-fedramp-audit.cutoverBlock",
        "Does FedRAMP audit block cutover?",
        "Weekly audit. Must pass pre-cutover or can it follow?",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-deploy-asia.latency",
        "Asia deploy runner latency",
        "Runners in eastasia region — set up GH self-hosted or rely on hosted + latency tolerance?",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-monorepo.workspaceStrategy",
        "GH monorepo workspace strategy",
        "Scala SBT multi-project build. Champion to confirm: single GH repo (current), OR split per-service?",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-proto-gen.codegenCheckin",
        "Proto codegen checkin strategy",
        "Currently auto-commits generated code. Preserve or move to artifact-only?",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-ml-models.datasetStorage",
        "ML model dataset storage",
        "Training datasets stored outside the repo. Migration of training pipelines requires confirmed dataset location.",
      ),
      needsInput(
        "Organization",
        "extensions.lfs-batching.port",
        "LFS Batching Tool reusable workflow",
        "Internal tool. Rewrite scope TBD.",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-release-canary.rollbackStrategy",
        "Canary rollback strategy",
        "Current rollback is ADO-specific. Map to GH environment rollback or deployment_status events?",
      ),
      needsInput(
        "JTBDs",
        "jtbds.region-deploy.environments",
        "Region deploy GH environments",
        "4 regions × 2 stages = 8 environments. Naming convention to confirm.",
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-integration-smoke.parallel",
        "Integration smoke parallelism",
        "6 parallel jobs; GH concurrency group needed to avoid conflicts.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.k8s-prod.authTransition",
        "K8s cluster auth transition",
        "Currently service-account. OIDC-to-AKS available; champion to approve.",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-monorepo.largeFileAudit",
        "Large-file audit result",
        "Scan found 12 files >50 MB not tracked by LFS. Move to LFS pre-migration or leave?",
      ),
      needsInput(
        "Code & repos",
        "repos.delta-benchmarks.dataGeneration",
        "Benchmark data generation",
        "Synthetic data generated on-demand. Verify GH runners can handle the workload.",
      ),
      needsInput(
        "Auth & security",
        "secrets.sast.licenseTransfer",
        "SAST tool license transfer",
        "Snyk license currently keyed to ADO org. Transfer to GH org ID required.",
      ),

      // Anomalies (22)
      anomaly(
        "Pipelines",
        "workflows.delta-lfs-sync.purpose",
        "delta-lfs-sync pipeline purpose inferred",
        "inferred: LFS batching",
        "Pipeline type OTHER; script contents suggest LFS batching but agent could not confirm intent without Champion review.",
      ),
      anomaly(
        "Code & repos",
        "repos.delta-monorepo.submoduleCrossProject",
        "Cross-project submodule references",
        "count: 2",
        "Submodules point to a different ADO project. Works today, but GH equivalent requires separate repo access grants.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-release-canary.rollbackImplicit",
        "Canary rollback mechanism implicit",
        "mechanism: inferred",
        "Rollback relies on ADO deployment-job ordering. No explicit rollback task.",
      ),
      anomaly(
        "Code & repos",
        "repos.delta-data-lfs.lfsScale",
        "LFS scale exceeds default limits",
        "34.2 GB / 200k+ objects",
        "Exceeds GH LFS default bandwidth quota. Migration plan requires coordination.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-legacy-etl-build.deprecated",
        "delta-legacy-etl-build uses deprecated task",
        "task: AzureFileCopy@3",
        "Deprecated by Microsoft. Still works today but may break independently of migration.",
      ),
      anomaly(
        "Customizations",
        "customizations.canary-orchestrator.semanticDrift",
        "Canary orchestrator custom behavior",
        "fidelity: partial",
        "Orchestrator reads ADO pipeline variables directly. GH equivalent may lose some context-sensitive branching.",
      ),
      anomaly(
        "Code & repos",
        "repos.delta-monorepo.changeDetection",
        "Change detection script complexity",
        "complexity: high",
        "Path-based selective rebuild script is 680 LOC. GH Actions path filters may not cover all cases.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-benchmarks-nightly.runnerAvailability",
        "Benchmarks runner pool scarcity",
        "available: 2",
        "Only 2 perf runners. Scheduling conflict risk during migration cutover.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-release-trunk.gateChain",
        "Release gate chain fragility",
        "stages: 6 · dependencies: implicit",
        "6-stage release with cross-stage dependencies. Graph not explicit; risk of mis-mapping to GH environments.",
      ),
      anomaly(
        "Code & repos",
        "repos.delta-legacy-etl.inactivity",
        "delta-legacy-etl inactivity",
        "commits90d: 4",
        "Marginal activity. May be zombie — or may be stable-and-working.",
      ),
      anomaly(
        "Auth & security",
        "serviceConnections.delta-nuget-internal.rotationDrift",
        "NuGet PAT approaching rotation policy",
        "age: 88d · policy: 90d",
        "PAT is 88 days old; rotating during cutover may cause brief publish outage.",
      ),
      anomaly(
        "Auth & security",
        "serviceConnections.delta-sonar.rotationDrift",
        "SonarCloud PAT rotation drift",
        "age: 64d",
        "Rotation cycle has drifted from the expected 90-day cadence.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-e2e-nightly.flakeRate",
        "e2e nightly flake rate elevated",
        "fails30d: 3 / runs: 7",
        "Flake rate of ~43% may be infra, test, or both. Migration window risks masking existing flake.",
      ),
      anomaly(
        "Organization",
        "extensions.canary-orchestrator.noDocumentation",
        "Canary Orchestrator lacks migration doc",
        "source: internal",
        "Internal extension. Port requires reading source; behavior may not be fully characterized.",
      ),
      anomaly(
        "Code & repos",
        "repos.delta-monorepo.submodulePinning",
        "Submodule pinning drift",
        "pinned: mixed",
        "Some submodules pinned to commits, others to branches. Inconsistent; migration should normalize.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-proto-gen.autoCommit",
        "Proto auto-commit to monorepo",
        "pattern: autocommit",
        "Pipeline commits generated protos to delta-monorepo. GH may require a different token pattern to commit back.",
      ),
      anomaly(
        "Work items",
        "workItems.crossProjectLinks",
        "Cross-project work item links",
        "count: 214",
        "Work items link across ADO projects. GH Issues can link across repos but not across orgs; rethink required if projects split across GH orgs.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-k8s-deploy.kubectlVersion",
        "K8s deploy uses old kubectl",
        "version: 1.24",
        "kubectl pinned to an older version that may not support newer cluster APIs. Noted during migration.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-release-trunk.failureRecovery",
        "Release trunk failure recovery",
        "mechanism: manual",
        "Failed release requires manual resume. Map to GH environment rerun semantics?",
      ),
      anomaly(
        "Customizations",
        "customizations.monorepo-change-detection.gaps",
        "Change detection gaps",
        "gaps: edge cases",
        "Script handles 95% of cases. 5% require manual trigger. Known behavior but brittle post-migration.",
      ),
      anomaly(
        "Code & repos",
        "repos.delta-monorepo.oversize",
        "Monorepo near GH soft limits",
        "size: 98 GB · limit: 100 GB",
        "Approaching GH's recommended 100 GB repo size. Future growth will require intervention.",
      ),
      anomaly(
        "Pipelines",
        "workflows.delta-fedramp-audit.brittleness",
        "FedRAMP audit pipeline fragility",
        "notes: tight coupling",
        "Audit pipeline tightly coupled to current ADO path structure. Migration may require audit rewrites to match new layout.",
      ),
      anomaly(
        "Code & repos",
        "repos.delta-data-lfs.gei-byte-migration",
        "GEI migrates LFS pointers but NOT the LFS object bytes",
        "34.2 GB / ~218k objects",
        "GitHub Enterprise Importer moves the repo and pointer files but does not transfer LFS object bytes — those must be re-pushed separately via a dedicated LFS push after the main migration. For a 34 GB corpus, this is a multi-hour secondary operation that must be scheduled alongside the cutover window.",
        [
          ev.api(
            "GET /_apis/git/repositories/delta-data-lfs/lfs",
            '{\n  "totalSize": 36722245728,\n  "objectCount": 218432,\n  "uniqueObjects": 211988\n}',
            "ADO REST v7.1 · 34.2 GB · 218k LFS objects",
          ),
          ev.url(
            "https://docs.github.com/en/migrations/using-github-enterprise-importer/migrating-from-azure-devops-to-github-enterprise-cloud/migrating-repositories-from-azure-devops-to-github-enterprise-cloud",
            "GEI migrates LFS pointers only. Re-push LFS object bytes separately after migration.",
            "GitHub Docs — GEI migration guide",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.delta-monorepo.gei-size-cap",
        "delta-monorepo exceeds GEI managed-migration size cap",
        "98 GB vs 40 GiB cap",
        "delta-monorepo at 98 GB exceeds GitHub Enterprise Importer's current managed-migration ceiling (40 GiB per repo as of the 2025 raise). Requires custom bundle-push approach or repo slimming via BFG before cutover.",
        [
          ev.api(
            "GET /_apis/git/repositories/delta-monorepo",
            '{\n  "name": "delta-monorepo",\n  "size": 105226698752\n}',
            "size: 98 GB · GEI ceiling: 40 GiB",
          ),
          ev.url(
            "https://github.blog/changelog/2025-06-03-increasing-github-enterprise-importers-repository-size-limits/",
            "GEI size cap was raised to 40 GiB public preview in June 2025. Still insufficient for delta-monorepo.",
            "GitHub Changelog",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.delta-data-lfs.lfs5gbCeiling",
        "LFS files above 5 GB per-file ceiling",
        "files: 4 · size: 3–6 GB",
        "Scan found 4 LFS-tracked files in the 3–6 GB range. GitHub LFS enforces a hard 5 GB per-file ceiling — at least one file will be rejected post-migration. Must be externalized (Azure Blob, S3) or sharded before cutover.",
        [
          ev.log(
            "lfs-scan-2026-04-22.log",
            "training-set-2024-q4.tar.zst    5.82 GB  ← exceeds 5 GB\ntraining-set-2024-q3.tar.zst    4.91 GB\nmodel-checkpoint-v4.bin         4.12 GB\nvalidation-corpus-ml.tar.zst    3.48 GB",
            "largest: 5.82 GB · 1 file above 5 GB ceiling · 3 files within 15% of ceiling",
          ),
          ev.url(
            "https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage",
            "GitHub LFS per-file limit is 5 GB. Above-ceiling files will be rejected.",
            "GitHub Docs — Git LFS",
          ),
        ],
      ),
      anomaly(
        "Code & repos",
        "repos.delta-legacy-etl.commitSizeBlocker",
        "Commit exceeding GitHub's 2 GB push ceiling",
        "commit: ~2.3 GB",
        "Historical commit in delta-legacy-etl contains ~2.3 GB of vendored binary dependencies. GitHub rejects any push where a single commit exceeds 2 GiB. Requires git filter-repo or BFG to rewrite history before migration.",
        [
          ev.log(
            "git-rev-list-sizes.log",
            "commit c7d2...4a (2020-03-14)\n  added vendor/oracle-client-12c.tar.gz  (1.18 GB)\n  added vendor/sap-hana-driver.tar.gz    (0.72 GB)\n  added vendor/ibm-mq-client.tar.gz      (0.38 GB)\n  total commit size: 2.34 GB",
            "single commit · 2.34 GB · GitHub push ceiling: 2 GB",
          ),
        ],
      ),
      needsInput(
        "Pipelines",
        "workflows.delta-e2e-nightly.matrixConversion",
        "Matrix strategy partial conversion",
        "delta-e2e-nightly uses an ADO matrix with maxParallel + fail-fast semantics. GitHub Actions Importer partially converts — maxParallel maps to max-parallel but fail-fast behavior differs subtly (GH's is more aggressive). Champion to confirm current behavior is desired post-migration.",
      ),
      needsInput(
        "Pipelines",
        "workflows.scheduleTriggerConversion",
        "Scheduled trigger conversion (cron + timezone)",
        "delta-benchmarks-nightly and delta-lfs-sync use ADO scheduled triggers. GitHub Actions Importer does not auto-convert `schedules:` to `on.schedule:` cleanly — cron strings need rewriting, and GH Actions cron is UTC-only (no ADO timezone). Champion to confirm target schedules.",
      ),
      anomaly(
        "Pipelines",
        "runners.hostedSpecMismatch",
        "Microsoft-hosted → GitHub-hosted runner spec change",
        "2vCPU/7GB → 4vCPU/16GB (default)",
        "Delta's hosted-runner pipelines are tuned for ADO's 2 vCPU / 7 GB RAM spec. Default GitHub-hosted runners are 4 vCPU / 16 GB. Timing-sensitive integration tests may behave differently; capacity is a win but consistency is a wash.",
      ),

      // Inferred findings (source=INFERRED, confidence=LOW).

      anomaly(
        "Code & repos",
        "lfs.submoduleLfsCascade",
        "Submodule LFS objects require a separate LFS push per submodule repo",
        "submodules: 2 (SharedLibs/core-dto, SharedLibs/proto-defs)",
        "INFERRED chain from 'GEI doesn't migrate LFS bytes' + 'submodule URL rewriting'. If SharedLibs repos are also migrated and contain LFS-tracked proto binaries, each submodule repo needs its own LFS byte push separately from delta-data-lfs's main push. Not independently documented but follows from GEI's one-repo-at-a-time model.",
      ),
      anomaly(
        "Pipelines",
        "matrix.perfPoolConcurrencyQueue",
        "Matrix fan-out on delta-perf-pool may exceed runner capacity",
        "matrix width: 8 · pool size: 2",
        "INFERRED chain from 'matrix strategy partial conversion' + 'perf runner scarcity'. delta-benchmarks-nightly fans out to 8 matrix jobs but the perf pool has 2 runners. On ADO this queued; on GH Actions with max-parallel not set, behavior depends on runner group config. Not independently documented but a standard self-hosted capacity trap.",
      ),
      anomaly(
        "Code & repos",
        "monorepo.bundlePushAuditGap",
        "Bundle-push around GEI size cap bypasses GEI's audit trail",
        "size: 98 GB · audit: bypassed",
        "INFERRED chain from 'GEI 40 GiB cap' + 'audit trail requirements'. To migrate delta-monorepo at 98 GB, team will need custom bundle-push tooling. GEI's migration audit log won't record the push — audit reviewers need an alternate evidence path. Not independently documented for this specific scenario.",
      ),
      anomaly(
        "Auth & security",
        "oidc.multiRegionCredentialDrift",
        "Per-region OIDC federated credentials may stagger during rollout",
        "regions: 4 (eastus, westus2, weu, eastasia)",
        "INFERRED chain from 'OIDC service connection rebuild' + 'multi-region deploys'. Each region's OIDC trust relationship must be re-established separately; staggered rollout across 4 regions creates a window where some regions auth via OIDC and others still via SP. Not independently documented but a standard federated-identity cutover pattern.",
      ),
    ],
  };
}
