import { jtbdOverridesFor } from "./jtbd-scoping";

import {
  adoProject,
  anomaly,
  customization,
  daysAgo,
  daysFromNow,
  extension,
  hoursAgo,
  allJtbds,
  member,
  needsInput,
  releaseDefinition,
  repo,
  serviceConnection,
  workflow,
  type CohortShape,
} from "./_helpers";

export function echoConfig(orgId: string): CohortShape {
  return {
    orgId,
    name: "Echo Mobile",
    slug: "echo",
    tagline: "The Champion still has work",
    description:
      "Cross-platform mobile team (iOS + Android) mid-review. Discovery left several needs-input findings around signing keys, App Center integration, and mobile-specific CI gates. Champion hasn't answered most yet; completion sits well below peers.",
    cohort: "ECHO",
    wave: 3,
    migrationState: "NOT_STARTED",
    engineerCount: 4,
    tier: "TIER_2",
    securityClassification: null,
    healthStatus: "BLOCKED",
    effortEstimateLowWeeks: null,
    effortEstimateHighWeeks: null,
    effortConfidence: "LOW",
    effortProgressWeeks: 0,
    targetCutoverAt: daysFromNow(120),
    slackWeeks: null,
    workItemsActive: 84,
    workItemsClosed90d: 218,
    buildArtifactCount: 162,
    wikiPageCount: 28,
    championEmail: "karen.lee@contoso.com",
    members: [
      member("Karen Lee", "karen.lee@contoso.com", "Mobile Lead"),
      member("Liam Sato", "liam.sato@contoso.com", "Senior iOS Engineer"),
      member("Mina Park", "mina.park@contoso.com", "Senior Android Engineer"),
      member("Nils Erikson", "nils.erikson@contoso.com", "Mobile QA Engineer"),
    ],
    codebase: {
      primaryLang: null,
      usesLfs: false,
      totalSizeGb: 18.4,
    },
    repos: [
      repo("echo-app", {
        sizeGb: 6.1,
        loc: 124000,
        languageBreakdown: {
          Swift: 42,
          Kotlin: 32,
          TypeScript: 14,
          YAML: 6,
          Markdown: 6,
        },
        contributorCount: 4,
        hasWiki: true,
        wikiPageCount: 14,
        commits90d: 284,
        primaryOwner: "karen.lee@contoso.com",
        lastCommitAt: hoursAgo(18),
      }),
      repo("echo-ios", {
        sizeGb: 4.8,
        loc: 82000,
        languageBreakdown: {
          Swift: 86,
          "Objective-C": 8,
          YAML: 4,
          Markdown: 2,
        },
        contributorCount: 3,
        hasWiki: true,
        wikiPageCount: 8,
        commits90d: 168,
        primaryOwner: "liam.sato@contoso.com",
        lastCommitAt: daysAgo(1),
      }),
      repo("echo-android", {
        sizeGb: 5.2,
        loc: 92000,
        languageBreakdown: { Kotlin: 74, Java: 16, YAML: 6, Markdown: 4 },
        contributorCount: 3,
        hasWiki: true,
        wikiPageCount: 10,
        commits90d: 212,
        primaryOwner: "mina.park@contoso.com",
        lastCommitAt: daysAgo(2),
      }),
      repo("echo-tests", {
        sizeGb: 2.3,
        loc: 42000,
        languageBreakdown: { Swift: 38, Kotlin: 32, TypeScript: 22, YAML: 8 },
        contributorCount: 4,
        hasWiki: false,
        commits90d: 124,
        primaryOwner: "nils.erikson@contoso.com",
        lastCommitAt: daysAgo(4),
      }),
    ],
    workflows: [
      workflow("echo-ios-build", "BUILD", {
        isClassic: true,
        customTasks: ["XamarinIOS@2 — deprecated"],
        deprecatedTasks: ["XamarinIOS@2"],
        runnerType: "SELF_HOSTED",
        agentPool: "echo-mac-pool",
        stageCount: 3,
        averageDurationMin: 24,
        triggersPerWeek: 48,
        failsLast30d: 6,
      }),
      workflow("echo-android-build", "BUILD", {
        isClassic: true,
        customTasks: ["Gradle@3"],
        runnerType: "MICROSOFT_HOSTED",
        stageCount: 3,
        averageDurationMin: 18,
        triggersPerWeek: 54,
        failsLast30d: 3,
      }),
      workflow("echo-app-test", "TEST", {
        averageDurationMin: 22,
        triggersPerWeek: 68,
        failsLast30d: 4,
      }),
    ],
    jtbds: allJtbds(jtbdOverridesFor("ECHO")),
    // Echo = "champion still has work" — partial inventory; some catalog
    // items the agent flagged but couldn't fully classify.
    customizations: [
      customization("C13", { status: "NEEDS_HUMAN" }),
      customization("C29", { status: "NEEDS_HUMAN" }),
      customization("C31", {
        name: "Mobile release gate (mechanism unknown)",
        description:
          "Mobile release gate — agent detected a gating step but could not identify the underlying mechanism (App Center? Internal?).",
        status: "NEEDS_HUMAN",
      }),
      customization("C33", {
        name: "iOS signing cert storage",
        description:
          "iOS signing cert storage — inferred Azure Key Vault but Champion needs to confirm access pattern.",
        status: "NEEDS_HUMAN",
      }),
    ],
    risks: [
      {
        title: "Signing key storage location unclear",
        detail:
          "echo-app builds invoke a signing step but the key source is not visible in pipeline metadata. Migration blocked until Champion confirms storage and rotation.",
        confidence: "HIGH",
        mitigation: null,
        status: "OPEN",
        category: "Auth",
      },
    ],
    ownership: {
      primaryOwnerEmail: "karen.lee@contoso.com",
      onCallGroup: null,
      escalationContact: null,
    },
    adoProjects: [
      adoProject("EchoMobile", {
        description: "iOS + Android app platform",
        repoCount: 4,
        pipelineCount: 3,
        boardCount: 2,
      }),
    ],
    serviceConnections: [
      serviceConnection("echo-azure-prod", "AZURE_RM", {
        targetService: "Azure RM · echo-backend",
        authMethod: "service-principal",
        usedByCount: 1,
        lastRotatedAt: daysAgo(64),
      }),
      serviceConnection("echo-app-center", "GENERIC", {
        targetService: "Visual Studio App Center",
        authMethod: "PAT",
        usedByCount: 2,
        lastRotatedAt: null,
      }),
      serviceConnection("echo-signing-kv", "GENERIC", {
        targetService: "Azure Key Vault · echo-signing (inferred)",
        authMethod: "managed-identity",
        usedByCount: 1,
        lastRotatedAt: null,
      }),
    ],
    releaseDefinitions: [
      releaseDefinition("echo-app-release", {
        stages: 3,
        isClassic: true,
        hasManualGates: true,
        gateTypes: ["manual-approval"],
        deployTargets: ["app-center-beta", "app-store-connect", "google-play"],
        lastRunAt: daysAgo(8),
      }),
    ],
    extensions: [
      extension("Visual Studio App Center", "Microsoft", "mobile-release", {
        hasGitHubEquivalent: false,
        notes:
          "App Center being sunset; migration targets Firebase App Distribution or similar.",
      }),
      extension("Detox Test Runner", "Wix", "mobile-testing", {
        hasGitHubEquivalent: true,
        notes:
          "Detox is OSS; runs on GH Actions with self-hosted Mac/Linux runners.",
      }),
    ],
    agentRun: {
      startedAt: hoursAgo(6),
      completedAt: new Date(hoursAgo(6).getTime() + 29_000),
      durationMs: 29_000,
    },
    curatedFindings: [
      // Needs-input (24 for a team that hasn't done much review yet)
      needsInput(
        "Code & repos",
        "codebase.primaryLang",
        "Primary language",
        "Mixed Swift / Kotlin / TS detected; no single dominant language. Champion input needed to classify.",
      ),
      needsInput(
        "Pipelines",
        "workflows.additional",
        "Additional pipelines beyond the 3 detected",
        "Only 3 pipelines visible to agent, but App Center workflows suggest release automation. Champion may need to point at additional pipelines.",
      ),
      needsInput(
        "Ownership",
        "ownership.onCallGroup",
        "On-call group",
        "No on-call group found in team metadata. Champion must confirm (or confirm none exists).",
      ),
      needsInput(
        "Ownership",
        "ownership.escalationContact",
        "Escalation contact",
        "No escalation contact captured in ADO team settings.",
      ),
      needsInput(
        "Customizations",
        "customizations.release-gate.mechanism",
        "Release gate mechanism",
        "Release gate step detected in pipeline but underlying service (App Center? custom?) not identifiable.",
      ),
      needsInput(
        "Auth & security",
        "secrets.signingKeyStorage",
        "Signing key storage location",
        "Signing step present but key source opaque. High-risk finding — blocks migration until resolved.",
      ),
      needsInput(
        "Auth & security",
        "secrets.androidSigningJks",
        "Android JKS keystore location",
        "Gradle signing config references a JKS file path but file isn't in source. Location unknown.",
      ),
      needsInput(
        "Auth & security",
        "secrets.iosCertsStorage",
        "iOS signing certs storage",
        "Xcode build uses local keychain entries. Storage and rotation path TBD.",
      ),
      needsInput(
        "Pipelines",
        "workflows.echo-ios-build.macRunnerPool",
        "Mac runner pool post-migration",
        "echo-mac-pool is self-hosted ADO pool. GH equivalent requires separate Mac runner provisioning.",
      ),
      needsInput(
        "Organization",
        "extensions.app-center.migration",
        "App Center migration path",
        "App Center is being sunset. Migrate to Firebase App Distribution, Apple TestFlight native, or keep App Center until EOL?",
      ),
      needsInput(
        "JTBDs",
        "jtbds.sign-release.approach",
        "Signing JTBD approach",
        "Currently unassigned. Stays ADO? Moves GH with new signing flow? Both during transition?",
      ),
      needsInput(
        "JTBDs",
        "jtbds.deploy-beta.approach",
        "Beta deploy approach",
        "Currently via App Center. Unassigned because App Center migration itself is TBD.",
      ),
      needsInput(
        "JTBDs",
        "jtbds.deploy-store.approach",
        "Store deploy approach",
        "Production store release automation unassigned. Champion to define.",
      ),
      needsInput(
        "Work items",
        "workItems.mobileLabels",
        "Mobile-specific work item labels",
        "ADO board uses mobile-specific categorization (platform, build variant). Map to GH labels how?",
      ),
      needsInput(
        "Pipelines",
        "workflows.echo-ios-build.xamarin",
        "Deprecated XamarinIOS@2 usage",
        "Task deprecated by Microsoft. Upgrade in-place before migration, or rewrite as GH Action?",
      ),
      needsInput(
        "Code & repos",
        "repos.echo-ios.xcodeProject",
        "Xcode project format",
        "echo-ios uses legacy .xcodeproj. Xcode project surgery during migration?",
      ),
      needsInput(
        "Code & repos",
        "repos.echo-android.gradleVersion",
        "Gradle version",
        "Gradle 6.x inferred; 8.x is current. Upgrade scope?",
      ),
      needsInput(
        "Pipelines",
        "workflows.echo-android-build.gradleTaskVersion",
        "Gradle task version",
        "Pipeline uses Gradle@3 ADO task. GH equivalent is actions/setup-java + gradle/gradle-build-action.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.echo-app-center.rotation",
        "App Center PAT rotation",
        "No rotation date. Rotate before cutover since the whole service is moving.",
      ),
      needsInput(
        "Auth & security",
        "serviceConnections.echo-signing-kv.access",
        "Signing Key Vault access model",
        "Managed identity inferred. Need to verify which pipelines have access.",
      ),
      needsInput(
        "Organization",
        "adoProjects.echo-mobile.visibility",
        "Team project visibility",
        "Currently private. Confirm post-migration visibility (likely stays private).",
      ),
      needsInput(
        "Code & repos",
        "repos.echo-tests.detoxConfig",
        "Detox test runner config",
        "Currently references local simulator configs. GH runners need equivalent.",
      ),
      needsInput(
        "Pipelines",
        "workflows.echo-app-test.coverageReporting",
        "Test coverage reporting",
        "Coverage reporter output goes to App Center. Destination post-migration?",
      ),
      needsInput(
        "Ownership",
        "ownership.secondaryOnCall",
        "Secondary on-call",
        "Team has no on-call rotation captured. Mobile team size (4) makes 24/7 on-call unusual; Champion to confirm intended pattern.",
      ),

      // Anomalies (6)
      anomaly(
        "Code & repos",
        "repos.echo-app.languageBreakdown",
        "echo-app language breakdown",
        "Swift 42% · Kotlin 32% · TS 14%",
        "Partial file scan; Champion should confirm before using for decisions.",
      ),
      anomaly(
        "Pipelines",
        "risks.signing.severity",
        "Signing risk severity",
        "HIGH (heuristic)",
        "Severity inferred from opacity of signing flow; Champion may upgrade or downgrade.",
      ),
      anomaly(
        "Pipelines",
        "workflows.echo-ios-build.deprecatedTask",
        "Deprecated XamarinIOS@2 in active use",
        "deprecated: true",
        "Task deprecated but still running. May fail in a future ADO update even before migration.",
      ),
      anomaly(
        "Auth & security",
        "serviceConnections.echo-app-center.noRotationRecord",
        "App Center PAT has no rotation record",
        "rotated: never",
        "PAT has never been rotated in this system's records. Likely rotated externally or never rotated.",
      ),
      anomaly(
        "Code & repos",
        "repos.echo-ios.simulatorFiles",
        "Committed simulator snapshots",
        "files: 48 · ~220 MB",
        "48 large binary files (simulator snapshots) committed outside LFS. Noted for size optimization.",
      ),
      anomaly(
        "Organization",
        "extensions.app-center.sunset",
        "App Center scheduled for sunset",
        "eol: announced",
        "Microsoft announced App Center EOL. Migration target must account for this regardless of ADO migration timing.",
      ),
      needsInput(
        "Auth & security",
        "secureFiles.keystoresAndCerts",
        "Secure Files (keystores, .p12, .mobileprovision) not migrated by GEI",
        "Echo's ADO Library > Secure Files holds the iOS signing .p12, provisioning profiles, and echo-android-upload.jks. GEI does not migrate Secure Files. These must be base64-encoded and uploaded as GitHub secrets. Champion to confirm rotation cadence post-migration.",
      ),
      needsInput(
        "Organization",
        "extensions.appCenterTest.replacement",
        "App Center Test replacement (BrowserStack or drop)",
        "Echo uses App Center Test for device-grid runs. Microsoft recommends BrowserStack App Automate as the replacement — commercial, per-minute pricing, separate account. Champion to approve procurement OR accept reduced device coverage.",
      ),
      needsInput(
        "Organization",
        "extensions.appCenterDistribute.fragmentation",
        "App Center Distribute fragments into 3 services",
        "Current single-click 'beta → prod' flow splits into: TestFlight (iOS beta), Google Play internal track (Android beta), and store submission workflows per platform. Champion to pick a unified wrapper (e.g. Fastlane) or accept per-platform workflows.",
      ),
      anomaly(
        "Auth & security",
        "runners.echo-mac-pool.keychainPersistence",
        "Self-hosted macOS runners may leak keychain entries between jobs",
        "pool: echo-mac-pool",
        "GitHub documents that self-hosted macOS runners don't auto-clean temp keychains / mobileprovision files between jobs. iOS signing secrets could leak across pipeline runs unless workflows add explicit teardown.",
      ),

      // Inferred findings (source=INFERRED, confidence=LOW).

      anomaly(
        "Pipelines",
        "ios.privacyManifestRequirement",
        "Apple privacy manifest workflow step not present in current pipeline",
        "iOS 17+ requirement",
        "INFERRED domain reasoning from 'App Center retirement' + iOS platform trends. Apps distributed via TestFlight post-migration need privacy manifests (PrivacyInfo.xcprivacy) per Apple policy. echo-ios pipeline currently has no manifest-validation step — may fail store review after migration even if build itself succeeds. Not independently documented for this team.",
      ),
      anomaly(
        "Auth & security",
        "runners.mixedTrustArtifacts",
        "Mac runner handling both iOS .p12 and Android JKS creates mixed-trust artifact generation",
        "shared runner: echo-mac-pool",
        "INFERRED chain from 'self-hosted keychain persistence' + 'Android JKS on same runner'. If the Android keystore and iOS signing cert live on the same self-hosted runner's temp filesystem, a compromised build step could access both. Standard compartmentalization practice says use separate runner pools per platform. Not independently documented for Echo specifically.",
      ),
    ],
  };
}
